; PLENA ISA  --  kernel: residual_gate
; generated by tilelang_tvm_compiler (PreIsaIR v2 → MIR path)
; ============================================================
S_LUI_INT gp1, 2048   ; %9=S_LUI_INT(2048)
S_ADDI_INT gp2, gp0, 2048   ; %10=S_ADDI_INT(%0_gp0,2048)
S_LUI_INT gp3, 74016   ; %44=S_LUI_INT(74016)
S_LUI_INT gp4, 34560   ; %85=S_LUI_INT(34560)
S_LUI_INT gp5, 36864   ; %144=S_LUI_INT(36864)
S_LUI_INT gp6, 256   ; %63=S_LUI_INT(256)
S_LUI_INT gp7, 512   ; %104=S_LUI_INT(512)
S_LUI_INT gp8, 768   ; %124=S_LUI_INT(768)
S_LUI_INT gp9, 1024   ; %134=S_LUI_INT(1024)
; for 1_bx in [0, 4) -- hw counter gp10, idx gp11
S_ADDI_INT gp11, gp0, 0
C_LOOP_START gp10, 4
S_SLLI_INT gp12, gp11, 21   ; %25=S_SLLI_INT(%1_bx,21)
; for 2_by_number in [0, 2) -- hw counter gp13, idx gp14
S_ADDI_INT gp14, gp0, 0
C_LOOP_START gp13, 2
; dma_h2v_slice X_hbm -> X_sh  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a0, gp0, gp0   ; %7=C_SET_ADDR_REG(gp0,%0_gp0)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%9)
C_SET_STRIDE_REG gp2   ; C_SET_STRIDE_REG(%10)
S_SLLI_INT gp15, gp14, 10   ; %31=S_SLLI_INT(%2_by_number,10)
; for 12_h2v_inner_8bc0 in [0, 4) -- hw counter gp16, idx gp17
S_ADDI_INT gp17, gp0, 0
C_LOOP_START gp16, 4
S_SLLI_INT gp18, gp17, 18   ; %22=S_SLLI_INT(%12_h2v_inner_8bc0,18)
S_SLLI_INT gp19, gp17, 19   ; %29=S_SLLI_INT(%12_h2v_inner_8bc0,19)
S_ADD_INT gp20, gp12, gp19   ; %30=S_ADD_INT(%25,%29)
S_ADD_INT gp19, gp20, gp15   ; %32=S_ADD_INT(%30,%31)
H_PREFETCH_V gp18, gp19, a0, 1, 0   ; H_PREFETCH_V(%22,%32,%7,1,0)
; idx 12_h2v_inner_8bc0 += 1 (gp17)
S_ADDI_INT gp17, gp17, 1
C_LOOP_END gp16
; dma_h2v_slice GATE_hbm -> GATE_sh  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a1, gp0, gp3   ; %45=C_SET_ADDR_REG(gp0,%44)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%9)
C_SET_STRIDE_REG gp2   ; C_SET_STRIDE_REG(%10)
S_ADD_INT gp16, gp12, gp15   ; %192=S_ADD_INT(%25,%31)
S_ADD_INT gp17, gp12, gp15   ; %193=S_ADD_INT(%25,%31)
; for 50_h2v_inner_8e00 in [0, 4) -- hw counter gp18, idx gp19
S_ADDI_INT gp19, gp0, 0
C_LOOP_START gp18, 4
S_SLLI_INT gp20, gp19, 18   ; %60=S_SLLI_INT(%50_h2v_inner_8e00,18)
S_ADD_INT gp21, gp20, gp6   ; %64=S_ADD_INT(%60,%63)
S_SLLI_INT gp20, gp19, 19   ; %70=S_SLLI_INT(%50_h2v_inner_8e00,19)
S_ADD_INT gp22, gp17, gp20   ; %73=S_ADD_INT(%193,%70)
H_PREFETCH_V gp21, gp22, a1, 1, 0   ; H_PREFETCH_V(%64,%73,%45,1,0)
; idx 50_h2v_inner_8e00 += 1 (gp19)
S_ADDI_INT gp19, gp19, 1
C_LOOP_END gp18
; dma_h2v_slice Y_hbm -> Y_sh  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a2, gp0, gp4   ; %86=C_SET_ADDR_REG(gp0,%85)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%9)
C_SET_STRIDE_REG gp2   ; C_SET_STRIDE_REG(%10)
; for 91_h2v_inner_9040 in [0, 4) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 4
S_SLLI_INT gp19, gp18, 18   ; %101=S_SLLI_INT(%91_h2v_inner_9040,18)
S_ADD_INT gp20, gp19, gp7   ; %105=S_ADD_INT(%101,%104)
S_SLLI_INT gp19, gp18, 19   ; %111=S_SLLI_INT(%91_h2v_inner_9040,19)
S_ADD_INT gp21, gp19, gp12   ; %112=S_ADD_INT(%111,%25)
S_ADD_INT gp19, gp21, gp15   ; %114=S_ADD_INT(%112,%31)
H_PREFETCH_V gp20, gp19, a2, 1, 0   ; H_PREFETCH_V(%105,%114,%86,1,0)
; idx 91_h2v_inner_9040 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; for 121_row1 in [0, 1024) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 1024
; v binary v_mul V_MUL_VV dst.parent=TMP_sh starts=[0, row1, 0, 0] extents=[1, 1, 8, 128]
S_SLLI_INT gp19, gp18, 10   ; %122=S_SLLI_INT(%121_row1,10)
S_ADD_INT gp20, gp19, gp8   ; %125=S_ADD_INT(%122,%124)
S_ADD_INT gp21, gp19, gp6   ; %128=S_ADD_INT(%122,%63)
S_ADD_INT gp22, gp7, gp19   ; %131=S_ADD_INT(%104,%122)
V_MUL_VV gp20, gp21, gp22, 0   ; V_MUL_VV(%125,%128,%131,0)
; v binary v_add V_ADD_VV dst.parent=OUT_sh starts=[0, row1, 0, 0] extents=[1, 1, 8, 128]
S_ADD_INT gp21, gp19, gp9   ; %135=S_ADD_INT(%122,%134)
V_ADD_VV gp21, gp19, gp20, 0   ; V_ADD_VV(%135,%122,%125,0)
; idx 121_row1 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; dma_v2h_slice OUT_sh -> OUT_hbm  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a3, gp0, gp5   ; %145=C_SET_ADDR_REG(gp0,%144)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%9)
C_SET_STRIDE_REG gp2   ; C_SET_STRIDE_REG(%10)
; for 150_v2h_inner_9550 in [0, 4) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 4
S_SLLI_INT gp19, gp18, 18   ; %160=S_SLLI_INT(%150_v2h_inner_9550,18)
S_ADD_INT gp20, gp9, gp19   ; %164=S_ADD_INT(%134,%160)
S_SLLI_INT gp19, gp18, 19   ; %170=S_SLLI_INT(%150_v2h_inner_9550,19)
S_ADD_INT gp21, gp19, gp12   ; %171=S_ADD_INT(%170,%25)
S_ADD_INT gp19, gp21, gp15   ; %173=S_ADD_INT(%171,%31)
H_STORE_V gp20, gp19, a3, 1, 0   ; H_STORE_V(%164,%173,%145,1,0)
; idx 150_v2h_inner_9550 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; idx 2_by_number += 1 (gp14)
S_ADDI_INT gp14, gp14, 1
C_LOOP_END gp13
; idx 1_bx += 1 (gp11)
S_ADDI_INT gp11, gp11, 1
C_LOOP_END gp10
