# ruff: noqa: E402
"""GPT-OSS MoE device-side gather/scatter bring-up.

Stage ``address`` is the first L2 gate: a runtime token-row offset is loaded
from int SRAM, converted into an HBM vector prefetch address on device, and the
gathered row is compared against the hardware-aware HBM MXFP8 golden.  Later
stages extend this same file to expert execution and scatter/combine.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
from pathlib import Path

import torch
import torch.nn.functional as F

_TESTBENCH_ROOT = Path(__file__).resolve().parents[1]
_ATEN_BUILD_DIR = _TESTBENCH_ROOT / "aten" / "build"
# Make the `compiler` package importable when this script is run directly.
# Prefer the pinned in-repo submodule (PLENA_Simulator/PLENA_Compiler) over a
# sibling AICrossSim-workspace checkout: a sibling may be on a different branch
# and would otherwise silently shadow the submodule on sys.path.
_REPO_ROOT = Path(__file__).resolve().parents[3]
for _compiler_root in (_REPO_ROOT / "PLENA_Compiler", _REPO_ROOT.parent / "PLENA_Compiler"):
    if (_compiler_root / "aten" / "plena" / "compiler.py").exists():
        sys.path.insert(0, str(_compiler_root))
        break

from aten.models.gpt_oss.moe_reference import compare_stats
from aten.models.gpt_oss.moe_reference import split_packed_gate_up
from aten.models.gpt_oss.real_layer_utils import load_layer_tensors
from compiler.aten.plena import PlenaCompiler
from compiler.aten.plena.vars import VRAMMatrixVar
from transactional_emulator.testbench.aten.configurable import add_hw_args, setup_hw
from transactional_emulator.testbench.routed_moe.gpt_oss_real_layer0_test import _stats_dict
from transactional_emulator.testbench.routed_moe.gpt_oss_real_layer0_test import _strict_elementwise_details
from transactional_emulator.testbench.routed_moe.gpt_oss_real_layer0_test import _tail_gate_details
from transactional_emulator.testbench.routed_moe.gpt_oss_router_gemm_test import _align_to
from transactional_emulator.testbench.routed_moe.gpt_oss_router_gemm_test import _rank_stability
from transactional_emulator.testbench.routed_moe.gpt_oss_router_gemm_test import _router_vector_bf16_golden
from transactional_emulator.testbench.routed_moe.gpt_oss_router_gemm_test import _vram_layout_size
from transactional_emulator.testbench.emulator_runner import compare_emulator_output, run_and_assert, run_emulator
from transactional_emulator.testbench.layout_utils import infer_hbm_tensor_layouts, prestage_bf16_vram_matrix
from transactional_emulator.testbench.routed_moe._reference import ensure_reference
from transactional_emulator.testbench.sim_env_utils import create_mem_for_sim
from transactional_emulator.testbench.sliced_layer_test_builder import quantize_to_mxfp
from transactional_emulator.tools.create_sim_env import create_sim_env
from plena_quant.mxfp.utils import bin_2_fp
from transactional_emulator.testbench.gpt_oss_testkit import (
    _activation_golden,
    _bf16,
    _comparison_params_for,
    _decode_bf16_dump,
    _decode_u32_dump,
    _expanded_bias,
    _linear_projection_golden,
)


def _load_tok8_reference(reference_path: Path) -> dict:
    # Shared tok8/layer-0 bundle, generated from the real checkpoint on first
    # use (see routed_moe/_reference.py).
    reference = ensure_reference(reference_path, layer_index=0, rows=8, seed=1)
    return {
        "x": reference["x"].to(torch.bfloat16),
        "topk_indices": reference["topk_indices"].to(torch.long),
        "topk_weights": reference["topk_weights"].to(torch.bfloat16),
    }


def _load_l1_golden(path: Path) -> torch.Tensor:
    """Load the L1 emulator-stamp golden used by the non-default stages.

    Unlike the reference bundle (auto-generated by ``ensure_reference``), this
    artifact is a raw emulator output that has no in-repo generator: it must be
    produced out-of-band by first running the tok8/L1 emulator stamp. Raise an
    actionable error instead of a bare ``FileNotFoundError`` when it is absent.
    """
    path = Path(path).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(
            f"L1 golden not found: {path}\n"
            "The --stage modes 'full_vram', 'hbm_store_*' and 'device_routing_*' "
            "require an out-of-band emulator-stamp artifact that this repo does not "
            "generate automatically. Produce it first (run the tok8/L1 emulator stamp "
            "so a 'golden_output.pt' is written to that directory), or pass "
            "--l1-golden-path to an existing stamp. The default '--stage address' "
            "and 'four' stages are self-contained and need no L1 golden."
        )
    return torch.load(path, map_location="cpu").to(torch.bfloat16)


def _decode_e8m0_scale(byte: int) -> float:
    """Decode unsigned E8M0 scale as used by the Rust HBM MX path."""
    return 2.0 ** (int(byte) - 127)


def _decode_hbm_mxfp8_row(
    hbm_path: Path,
    *,
    tensor_base: int,
    tensor_rows: int,
    tensor_cols: int,
    row_element_offset: int,
) -> torch.Tensor:
    """Decode one row from the exact generated HBM preload bytes."""
    return _decode_hbm_mxfp8_row_from_bytes(
        hbm_path.read_bytes(),
        tensor_base=tensor_base,
        tensor_rows=tensor_rows,
        tensor_cols=tensor_cols,
        row_element_offset=row_element_offset,
    )


def _hbm_byte(hbm: bytes, idx: int) -> int:
    return hbm[idx] if 0 <= idx < len(hbm) else 0


def _hbm_range(hbm: bytes, start: int, length: int) -> bytes:
    if length <= 0:
        return b""
    if start >= len(hbm):
        return b"\x00" * length
    chunk = hbm[start : min(start + length, len(hbm))]
    if len(chunk) < length:
        chunk += b"\x00" * (length - len(chunk))
    return chunk


def _decode_hbm_mxfp8_row_from_bytes(
    hbm: bytes,
    *,
    tensor_base: int,
    tensor_rows: int,
    tensor_cols: int,
    row_element_offset: int,
) -> torch.Tensor:
    """Decode one MXFP8 HBM row from a byte buffer, zero-extending missing bytes."""
    element_base = tensor_base + row_element_offset
    scale_base = tensor_base + tensor_rows * tensor_cols + (row_element_offset // 8)
    values = []
    for col in range(tensor_cols):
        element = _hbm_byte(hbm, element_base + col)
        scale = _hbm_byte(hbm, scale_base + (col // 8))
        values.append(float(bin_2_fp(element, 4, 3)) * _decode_e8m0_scale(scale))
    return torch.tensor(values, dtype=torch.float32).reshape(1, tensor_cols).to(torch.bfloat16)


def _decode_hbm_mxfp8_output_slots(
    hbm: bytes,
    *,
    slot_base: int,
    slot_stride: int,
    rows: int,
    hidden: int,
    blen: int,
) -> torch.Tensor:
    decoded = torch.zeros(rows, hidden, dtype=torch.bfloat16)
    for token_idx in range(rows):
        decoded[token_idx : token_idx + 1] = _decode_hbm_mxfp8_row_from_bytes(
            hbm,
            tensor_base=slot_base + token_idx * slot_stride,
            tensor_rows=blen,
            tensor_cols=hidden,
            row_element_offset=0,
        )
    return decoded


def _hbm_slot_padding_zero(
    hbm: bytes,
    *,
    slot_base: int,
    slot_stride: int,
    token_indices: list[int],
    hidden: int,
    blen: int,
) -> dict:
    nonzero_rows = []
    for token_idx in token_indices:
        token_base = slot_base + token_idx * slot_stride
        for pad_row in range(1, blen):
            decoded = _decode_hbm_mxfp8_row_from_bytes(
                hbm,
                tensor_base=token_base,
                tensor_rows=blen,
                tensor_cols=hidden,
                row_element_offset=pad_row * hidden,
            )
            max_abs = float(decoded.float().abs().max().item())
            if max_abs != 0.0:
                nonzero_rows.append({"token_index": token_idx, "padding_row": pad_row, "max_abs": max_abs})
    return {
        "checked_tokens": token_indices,
        "padding_rows_per_token": blen - 1,
        "nonzero_rows": nonzero_rows,
        "passed": not nonzero_rows,
    }


def _hbm_unwritten_slots_unchanged(
    before: bytes,
    after: bytes,
    *,
    slot_base: int,
    slot_stride: int,
    rows: int,
    written_tokens: list[int],
) -> dict:
    written = set(written_tokens)
    changed = []
    for token_idx in range(rows):
        if token_idx in written:
            continue
        start = slot_base + token_idx * slot_stride
        before_slot = _hbm_range(before, start, slot_stride)
        after_slot = _hbm_range(after, start, slot_stride)
        if before_slot != after_slot:
            first_diff = next((idx for idx, (a, b) in enumerate(zip(before_slot, after_slot)) if a != b), None)
            changed.append(
                {
                    "token_index": token_idx,
                    "first_diff_byte": first_diff,
                    "absolute_hbm_byte": None if first_diff is None else start + first_diff,
                }
            )
    return {
        "written_tokens": written_tokens,
        "unchanged_tokens_checked": [token for token in range(rows) if token not in written],
        "changed_unwritten_slots": changed,
        "passed": not changed,
    }


def _rewrite_compact_golden(build_dir: Path, golden: torch.Tensor) -> None:
    torch.save(golden.detach().cpu().float(), build_dir / "golden_output.pt")
    summary = {
        "format": "compact",
        "reason": "exact HBM-byte decoded gather golden",
        "golden_output_file": "golden_output.pt",
        "original_output": {
            "shape": list(golden.shape),
            "dtype": str(golden.dtype),
            "numel": int(golden.numel()),
        },
    }
    (build_dir / "golden_result.txt").write_text("Compact Golden Result\n" + json.dumps(summary, indent=2) + "\n")


def _expert_golden_from_gathered_vram(
    x_slots: torch.Tensor,
    w_gate: torch.Tensor,
    w_up: torch.Tensor,
    w_down: torch.Tensor,
    *,
    b_gate: torch.Tensor,
    b_up: torch.Tensor,
    b_down: torch.Tensor,
    mlen: int,
) -> torch.Tensor:
    gate = _linear_projection_golden(x_slots, w_gate, mlen=mlen, hbm_input=False)
    up = _linear_projection_golden(x_slots, w_up, mlen=mlen, hbm_input=False)
    gate = _bf16(gate.float() + b_gate.float())
    up = _bf16(up.float() + b_up.float())
    hidden = _activation_golden(gate, up)
    out = _linear_projection_golden(hidden, w_down, mlen=mlen, hbm_input=False)
    return _bf16(out.float() + b_down.float())


def _active_row_indices(pair_count: int, blen: int) -> list[int]:
    return [pair_idx * blen for pair_idx in range(pair_count)]


def _slot_route_matrix(
    *,
    slot_rows: int,
    hidden: int,
    blen: int,
    token_indices: list[int],
    topk_positions: list[int],
    topk_weights: torch.Tensor,
) -> torch.Tensor:
    route = torch.zeros(slot_rows, hidden, dtype=torch.bfloat16)
    for pair_idx, (token_idx, topk_pos) in enumerate(zip(token_indices, topk_positions, strict=True)):
        route[pair_idx * blen] = topk_weights[token_idx, topk_pos].to(torch.bfloat16)
    return route


def _expert_hbm_stride(prog: PlenaCompiler, shape: tuple[int, int]) -> int:
    raw_size = int(shape[0] * shape[1] * prog.real_data_ratio)
    return _align_to(raw_size, prog.mlen)


def _build_true_expert_weight_table(
    prog: PlenaCompiler,
    *,
    prefix: str,
    weights: torch.Tensor,
    input_tensors: dict[str, torch.Tensor],
) -> tuple[list, int, int]:
    """Register all 32 true expert weights as one stride-addressable HBM table."""
    num_experts, rows, cols = weights.shape
    stride = _expert_hbm_stride(prog, (rows, cols))
    base = prog._allocate_hbm(stride * num_experts)
    inputs = []
    for expert_id in range(num_experts):
        name = f"{prefix}_true_e{expert_id}"
        inputs.append(prog.input(name, shape=(rows, cols), hbm_addr=base + expert_id * stride))
        input_tensors[name] = weights[expert_id].to(torch.bfloat16).contiguous().clone()
    return inputs, base, stride


def _build_true_expert_bias_table(
    *,
    prog: PlenaCompiler,
    name: str,
    bias: torch.Tensor,
    width: int,
    blen: int,
    vram_addr: int,
    vram_preload: torch.Tensor,
) -> VRAMMatrixVar:
    num_experts = int(bias.shape[0])
    table = torch.zeros(num_experts * blen, width, dtype=torch.bfloat16)
    for expert_id in range(num_experts):
        table[expert_id * blen : (expert_id + 1) * blen] = bias[expert_id].to(torch.bfloat16).reshape(1, -1)
    return prestage_bf16_vram_matrix(
        prog=prog,
        name=name,
        tensor=table,
        vram_addr=vram_addr,
        physical_shape=(num_experts * blen, width),
        vram_preload=vram_preload,
    )


def _device_routing_exact_golden(
    *,
    hbm_path: Path,
    x_input,
    x: torch.Tensor,
    device_indices: torch.Tensor,
    device_weights: torch.Tensor,
    split,
    down_weight: torch.Tensor,
    down_bias: torch.Tensor,
    rows: int,
    hidden: int,
    blen: int,
    mlen: int,
    pair_count: int | None = None,
) -> tuple[torch.Tensor, dict]:
    exact_golden = torch.zeros(rows, hidden, dtype=torch.bfloat16)
    clamp_counts = {
        "gate_gt_7": 0,
        "gate_lt_neg_7": 0,
        "up_gt_7": 0,
        "up_lt_neg_7": 0,
        "per_token": [
            {"token_index": token_idx, "gate_gt_7": 0, "gate_lt_neg_7": 0, "up_gt_7": 0, "up_lt_neg_7": 0}
            for token_idx in range(rows)
        ],
    }
    hbm_bytes = hbm_path.read_bytes()
    top_k = device_indices.shape[1]
    total_pairs = rows * top_k if pair_count is None else pair_count
    for pair_idx in range(total_pairs):
        token_idx = pair_idx // top_k
        topk_pos = pair_idx % top_k
        expert_id = int(device_indices[token_idx, topk_pos].item())
        weight = device_weights[token_idx, topk_pos].to(torch.bfloat16)
        x_slots = torch.zeros(blen, hidden, dtype=torch.bfloat16)
        x_slots[0:1] = _decode_hbm_mxfp8_row_from_bytes(
            hbm_bytes,
            tensor_base=x_input.hbm_addr,
            tensor_rows=rows,
            tensor_cols=hidden,
            row_element_offset=token_idx * hidden,
        )

        b_gate = _expanded_bias(split.gate_bias[expert_id], blen)
        b_up = _expanded_bias(split.up_bias[expert_id], blen)
        b_down = _expanded_bias(down_bias[expert_id], blen)
        gate_pre = _linear_projection_golden(
            x_slots,
            split.gate_weight[expert_id],
            mlen=mlen,
            hbm_input=False,
        )
        up_pre = _linear_projection_golden(
            x_slots,
            split.up_weight[expert_id],
            mlen=mlen,
            hbm_input=False,
        )
        gate_pre = _bf16(gate_pre.float() + b_gate.float())
        up_pre = _bf16(up_pre.float() + b_up.float())
        local_clamp = _clamp_counts_from_slots(
            token_indices=[token_idx],
            gate=gate_pre,
            up=up_pre,
            blen=blen,
            rows=rows,
        )
        for key in ("gate_gt_7", "gate_lt_neg_7", "up_gt_7", "up_lt_neg_7"):
            clamp_counts[key] += local_clamp[key]
        for idx, item in enumerate(local_clamp["per_token"]):
            for key in ("gate_gt_7", "gate_lt_neg_7", "up_gt_7", "up_lt_neg_7"):
                clamp_counts["per_token"][idx][key] += item[key]

        expert_out = _expert_golden_from_gathered_vram(
            x_slots,
            split.gate_weight[expert_id],
            split.up_weight[expert_id],
            down_weight[expert_id],
            b_gate=b_gate,
            b_up=b_up,
            b_down=b_down,
            mlen=mlen,
        )
        exact_golden[token_idx] = _bf16(
            exact_golden[token_idx].float() + _bf16(expert_out[0].float() * weight.float()).float()
        )
    return exact_golden, clamp_counts


def _device_routing_vram_exact_golden(
    *,
    x: torch.Tensor,
    device_indices: torch.Tensor,
    device_weights: torch.Tensor,
    split,
    down_weight: torch.Tensor,
    down_bias: torch.Tensor,
    rows: int,
    hidden: int,
    blen: int,
    mlen: int,
    pair_count: int | None = None,
) -> tuple[torch.Tensor, dict]:
    """Exact golden for decoder-block MoE input already resident in BF16 VRAM."""
    exact_golden = torch.zeros(rows, hidden, dtype=torch.bfloat16)
    clamp_counts = {
        "gate_gt_7": 0,
        "gate_lt_neg_7": 0,
        "up_gt_7": 0,
        "up_lt_neg_7": 0,
        "per_token": [
            {"token_index": token_idx, "gate_gt_7": 0, "gate_lt_neg_7": 0, "up_gt_7": 0, "up_lt_neg_7": 0}
            for token_idx in range(rows)
        ],
    }
    top_k = device_indices.shape[1]
    total_pairs = rows * top_k if pair_count is None else pair_count
    for pair_idx in range(total_pairs):
        token_idx = pair_idx // top_k
        topk_pos = pair_idx % top_k
        expert_id = int(device_indices[token_idx, topk_pos].item())
        weight = device_weights[token_idx, topk_pos].to(torch.bfloat16)
        x_slots = torch.zeros(blen, hidden, dtype=torch.bfloat16)
        x_slots[0:1] = x[token_idx : token_idx + 1].to(torch.bfloat16)

        b_gate = _expanded_bias(split.gate_bias[expert_id], blen)
        b_up = _expanded_bias(split.up_bias[expert_id], blen)
        b_down = _expanded_bias(down_bias[expert_id], blen)
        gate_pre = _linear_projection_golden(
            x_slots,
            split.gate_weight[expert_id],
            mlen=mlen,
            hbm_input=False,
        )
        up_pre = _linear_projection_golden(
            x_slots,
            split.up_weight[expert_id],
            mlen=mlen,
            hbm_input=False,
        )
        gate_pre = _bf16(gate_pre.float() + b_gate.float())
        up_pre = _bf16(up_pre.float() + b_up.float())
        local_clamp = _clamp_counts_from_slots(
            token_indices=[token_idx],
            gate=gate_pre,
            up=up_pre,
            blen=blen,
            rows=rows,
        )
        for key in ("gate_gt_7", "gate_lt_neg_7", "up_gt_7", "up_lt_neg_7"):
            clamp_counts[key] += local_clamp[key]
        for idx, item in enumerate(local_clamp["per_token"]):
            for key in ("gate_gt_7", "gate_lt_neg_7", "up_gt_7", "up_lt_neg_7"):
                clamp_counts["per_token"][idx][key] += item[key]

        expert_out = _expert_golden_from_gathered_vram(
            x_slots,
            split.gate_weight[expert_id],
            split.up_weight[expert_id],
            down_weight[expert_id],
            b_gate=b_gate,
            b_up=b_up,
            b_down=b_down,
            mlen=mlen,
        )
        exact_golden[token_idx] = _bf16(
            exact_golden[token_idx].float() + _bf16(expert_out[0].float() * weight.float()).float()
        )
    return exact_golden, clamp_counts


def _device_topk_contract(
    *,
    hf_indices: torch.Tensor,
    hf_weights: torch.Tensor,
    device_indices: torch.Tensor,
    device_weights: torch.Tensor,
    device_logits: torch.Tensor,
    rank_gate: dict,
) -> dict:
    boundary_safe = [bool(v) for v in rank_gate["gap_gt_measured_error_by_token"]]
    internal_order_safe = [bool(v) for v in rank_gate["internal_order_gap_gt_measured_error_by_token"]]
    boundary_ambiguous_tokens = {idx for idx, safe in enumerate(boundary_safe) if not safe}
    internal_order_ambiguous_tokens = {idx for idx, safe in enumerate(internal_order_safe) if not safe}
    set_matches = []
    order_matches = []
    weights_by_expert_close = []
    tie_break_matches = []
    for token_idx in range(hf_indices.shape[0]):
        hf_row = [int(v) for v in hf_indices[token_idx].tolist()]
        dev_row = [int(v) for v in device_indices[token_idx].tolist()]
        # V_TOPK contract: descending logit value, exact ties by smaller expert id.
        sorted_by_device_context = sorted(
            range(device_logits.shape[1]),
            key=lambda expert_id: (-float(device_logits[token_idx, expert_id].float().item()), expert_id),
        )[: device_indices.shape[1]]
        set_match = set(hf_row) == set(dev_row)
        order_match = hf_row == dev_row
        tie_break_matches.append(dev_row == [int(v) for v in sorted_by_device_context])
        set_matches.append(set_match)
        order_matches.append(order_match)
        hf_map = {int(expert): hf_weights[token_idx, pos].float() for pos, expert in enumerate(hf_row)}
        dev_map = {int(expert): device_weights[token_idx, pos].float() for pos, expert in enumerate(dev_row)}
        common = sorted(set(hf_map) & set(dev_map))
        if common:
            hf_vals = torch.stack([hf_map[e] for e in common])
            dev_vals = torch.stack([dev_map[e] for e in common])
            weights_by_expert_close.append(bool(torch.allclose(dev_vals, hf_vals, atol=0.003, rtol=0.0)))
        else:
            weights_by_expert_close.append(False)
    safe_set_pass = all(
        match for token_idx, match in enumerate(set_matches) if token_idx not in boundary_ambiguous_tokens
    )
    safe_order_pass = all(
        match
        for token_idx, match in enumerate(order_matches)
        if token_idx not in boundary_ambiguous_tokens | internal_order_ambiguous_tokens
    )
    weight_diff = (device_weights.float() - hf_weights.float()).abs()
    weight_rel_rms = torch.linalg.vector_norm(device_weights.float() - hf_weights.float()) / torch.clamp(
        torch.linalg.vector_norm(hf_weights.float()),
        min=1e-12,
    )
    return {
        "boundary_ambiguous_tokens": sorted(boundary_ambiguous_tokens),
        "internal_order_ambiguous_tokens": sorted(internal_order_ambiguous_tokens),
        "hf_indices": hf_indices.cpu().tolist(),
        "device_indices": device_indices.cpu().tolist(),
        "hf_weights": hf_weights.cpu().float().tolist(),
        "device_weights": device_weights.cpu().float().tolist(),
        "weight_rel_rms": float(weight_rel_rms.item()),
        "weight_max_abs_error": float(weight_diff.max().item()),
        "weight_max_abs_error_by_token": weight_diff.max(dim=1).values.cpu().float().tolist(),
        "set_matches_by_token": set_matches,
        "order_matches_by_token": order_matches,
        "tie_break_matches_device_logits_by_token": tie_break_matches,
        "tie_break_matches_device_logits": all(tie_break_matches),
        "weights_by_expert_close_by_token": weights_by_expert_close,
        "rank4_rank5_gap": rank_gate["rank4_rank5_gap"],
        "min_internal_topk_gap": rank_gate["min_internal_topk_gap"],
        "device_max_abs_error_by_token": rank_gate["device_max_abs_error_by_token"],
        "gap_safe_by_token": boundary_safe,
        "internal_order_safe_by_token": internal_order_safe,
        "ambiguity_policy": (
            "Tokens are classified per sample/layer. A token is gap-safe when "
            "rank4-rank5 gap exceeds that token's measured BF16 router logit "
            "error; safe tokens must match HF top-4 sets. Internal order is "
            "required only when the minimum adjacent in-top-k gap exceeds the "
            "same measured error. Unsafe tokens are recorded and checked for "
            "deterministic device-logit tie-break behavior, not forced to match HF."
        ),
        "gap_safe_set_pass": safe_set_pass,
        "gap_safe_order_pass": safe_order_pass,
        "passed": safe_set_pass and safe_order_pass and all(tie_break_matches),
    }


def _clamp_counts_from_slots(
    *,
    token_indices: list[int],
    gate: torch.Tensor,
    up: torch.Tensor,
    blen: int,
    rows: int,
) -> dict:
    per_token = [
        {
            "token_index": token_idx,
            "gate_gt_7": 0,
            "gate_lt_neg_7": 0,
            "up_gt_7": 0,
            "up_lt_neg_7": 0,
        }
        for token_idx in range(rows)
    ]
    for pair_idx, token_idx in enumerate(token_indices):
        active = pair_idx * blen
        per_token[token_idx]["gate_gt_7"] += int((gate[active] > 7).sum().item())
        per_token[token_idx]["gate_lt_neg_7"] += int((gate[active] < -7).sum().item())
        per_token[token_idx]["up_gt_7"] += int((up[active] > 7).sum().item())
        per_token[token_idx]["up_lt_neg_7"] += int((up[active] < -7).sum().item())
    return {
        "gate_gt_7": sum(item["gate_gt_7"] for item in per_token),
        "gate_lt_neg_7": sum(item["gate_lt_neg_7"] for item in per_token),
        "up_gt_7": sum(item["up_gt_7"] for item in per_token),
        "up_lt_neg_7": sum(item["up_lt_neg_7"] for item in per_token),
        "per_token": per_token,
    }


def run_address_stage(args: argparse.Namespace) -> dict:
    mlen = args.mlen
    blen = args.blen
    build_dir = args.build_dir.expanduser().resolve()
    build_dir.mkdir(parents=True, exist_ok=True)
    hw = setup_hw(args, build_dir)

    ref = _load_tok8_reference(args.reference_path)
    x = ref["x"]
    rows, hidden = x.shape
    if hidden % mlen != 0:
        raise ValueError(f"hidden={hidden} must be divisible by MLEN={mlen}")
    if args.token_index < 0 or args.token_index >= rows:
        raise ValueError(f"token_index={args.token_index} out of range [0, {rows})")

    slot_rows = blen
    token_offsets = torch.tensor([args.token_index * hidden], dtype=torch.int32)
    golden = quantize_to_mxfp(x[args.token_index : args.token_index + 1]).to(torch.bfloat16)

    prog = PlenaCompiler(mlen=mlen, blen=blen, real_data_ratio=hw.real_data_ratio)
    _zero = prog.fp_var("zero", size=1)
    _limit_pos = prog.fp_var("gpt_oss_limit_pos", size=slot_rows)
    _limit_neg = prog.fp_var("gpt_oss_limit_neg", size=slot_rows)
    _one = prog.fp_var("one", size=slot_rows)
    _neg_alpha = prog.fp_var("neg_alpha", size=slot_rows)

    x_input = prog.input("X", shape=(rows, hidden))
    gathered = prog.moe_gather_token_rows_from_hbm_v0(
        x_input,
        token_offsets_int_base=0,
        pair_count=1,
        hidden=hidden,
        name="gather_address_strict_x",
    )
    isa = prog.compile()
    scale_reg_count = isa.count("C_SET_SCALE_REG")
    if scale_reg_count <= 0:
        raise AssertionError("gather path must set C_SET_SCALE_REG for MXFP8 HBM activation loads")

    input_tensors = {"X": x}
    tensor_layouts = infer_hbm_tensor_layouts(input_tensors)
    create_sim_env(
        input_tensors,
        isa,
        {"original_output": golden},
        fp_preload=[0.0],
        int_preload=token_offsets,
        build_dir=str(build_dir),
        tensor_layouts=tensor_layouts,
    )
    hbm_addrs = {name: prog._compiler.get_hbm_layout(name).hbm_base_addr for name in input_tensors}
    create_mem_for_sim(
        data_size=256,
        mode="behave_sim",
        asm="gpt_oss_moe_gather_address",
        data=None,
        specified_data_order=list(input_tensors),
        build_path=build_dir,
        input_tensors=input_tensors,
        hbm_addrs=hbm_addrs,
        tensor_layouts=tensor_layouts,
    )

    # The strict address gate should compare against the exact HBM bytes the
    # DMA reads, not a parallel high-level quantizer.  A few E4M3/E8M0 boundary
    # values differ between those views; the generated preload is the source of
    # truth for this address test.
    golden = _decode_hbm_mxfp8_row(
        build_dir / "hbm_for_behave_sim.bin",
        tensor_base=x_input.hbm_addr,
        tensor_rows=rows,
        tensor_cols=hidden,
        row_element_offset=int(token_offsets[0].item()),
    )
    _rewrite_compact_golden(build_dir, golden)

    comparison_params = _comparison_params_for(gathered, rows=1, hidden=hidden, mlen=mlen, golden=golden)
    (build_dir / "comparison_params.json").write_text(json.dumps(comparison_params, indent=2) + "\n")
    (build_dir / "generated_asm_code.asm").write_text(isa)

    manifest = {
        "stage": "address",
        "reference_path": str(args.reference_path.expanduser().resolve()),
        "token_index": args.token_index,
        "token_offsets_int_base": 0,
        "token_offsets": token_offsets.tolist(),
        "rows": rows,
        "hidden": hidden,
        "mlen": mlen,
        "blen": blen,
        "h_prefetch_v_granularity_elements": blen * mlen,
        "scale_reg_count": scale_reg_count,
        "x_hbm_base_addr": x_input.hbm_addr,
        "expected_hbm_element_offset": int(token_offsets[0].item()),
        "expected_hbm_absolute_element_addr": int(x_input.hbm_addr + token_offsets[0].item()),
        "output_vram_row": prog._compiler.get_vram_addr(gathered.name) // mlen,
        "comparison_params": comparison_params,
        "asm_lines": len(isa.splitlines()),
    }
    (build_dir / "gather_scatter_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))
    if args.no_run:
        return {"build_dir": str(build_dir), "ran": False, "manifest": manifest}

    metrics = run_and_assert(
        build_dir,
        "gpt_oss_moe_gather_address",
        mlen=mlen,
        blen=blen,
        threads=args.emu_threads,
    )
    results, params = compare_emulator_output(build_dir)
    emu_output = results["simulated_values"].reshape(1, hidden).to(torch.bfloat16)
    stats = compare_stats(emu_output, golden, rtol=0.0)
    if stats.max_abs_error != 0.0 or not stats.allclose:
        raise AssertionError(
            "single-token gather address strict failed: "
            f"max_abs={stats.max_abs_error:.6g}, rel_rms={stats.rel_rms:.6g}, allclose={stats.allclose}"
        )

    summary = {
        **manifest,
        "run_metrics": metrics,
        "comparison_params_runtime": params,
        "emulator_compare_raw": {
            key: results[key]
            for key in (
                "mse",
                "mae",
                "max_error",
                "relative_error",
                "relative_match_rate",
                "allclose_match_rate",
                "match_rate",
                "allclose_pass",
                "atol",
                "rtol",
                "golden_shape",
                "simulated_shape",
            )
            if key in results
        },
        "emulator_vs_gather_golden": {
            "rel_rms": stats.rel_rms,
            "allclose": stats.allclose,
            "pass_rate": stats.pass_rate,
            "max_abs_error": stats.max_abs_error,
            "atol": stats.atol,
            "rtol": stats.rtol,
        },
        "address_gate": {
            "device_address_matches_host_formula": True,
            "gathered_row_strict": stats.max_abs_error == 0.0 and stats.allclose,
            "scale_reg_count_nonzero": scale_reg_count > 0,
            "passed": stats.max_abs_error == 0.0 and stats.allclose and scale_reg_count > 0,
        },
    }
    (build_dir / "gather_scatter_results.json").write_text(json.dumps(summary, indent=2) + "\n")
    print(json.dumps(summary, indent=2))
    return {"build_dir": str(build_dir), "ran": True, "summary": summary}


def run_four_pair_stage(args: argparse.Namespace) -> dict:
    mlen = args.mlen
    blen = args.blen
    build_dir = args.build_dir.expanduser().resolve()
    build_dir.mkdir(parents=True, exist_ok=True)
    hw = setup_hw(args, build_dir)

    ref = _load_tok8_reference(args.reference_path)
    x = ref["x"]
    topk_indices = ref["topk_indices"]
    rows, hidden = x.shape
    tensors = load_layer_tensors(args.layer_index)
    split = split_packed_gate_up(tensors["gate_up_weight"], tensors["gate_up_bias"])
    down_weight = tensors["down_weight"]
    down_bias = tensors["down_bias"]

    token_idx, _ = torch.where(topk_indices == args.expert_id)
    token_indices = [int(v) for v in token_idx.tolist()]
    if not token_indices:
        raise ValueError(f"expert {args.expert_id} has no routed rows in this reference")

    pair_count = len(token_indices)
    slot_rows = pair_count * blen
    token_offsets = torch.tensor([token * hidden for token in token_indices], dtype=torch.int32)

    w_gate = split.gate_weight[args.expert_id].to(torch.bfloat16).contiguous().clone()
    w_up = split.up_weight[args.expert_id].to(torch.bfloat16).contiguous().clone()
    w_down = down_weight[args.expert_id].to(torch.bfloat16).contiguous().clone()
    b_gate = _expanded_bias(split.gate_bias[args.expert_id], slot_rows)
    b_up = _expanded_bias(split.up_bias[args.expert_id], slot_rows)
    b_down = _expanded_bias(down_bias[args.expert_id], slot_rows)

    prog = PlenaCompiler(mlen=mlen, blen=blen, real_data_ratio=hw.real_data_ratio)
    zero = prog.fp_var("zero", size=1)
    limit_pos = prog.fp_var("gpt_oss_limit_pos", size=slot_rows)
    limit_neg = prog.fp_var("gpt_oss_limit_neg", size=slot_rows)
    one = prog.fp_var("one", size=slot_rows)
    neg_alpha = prog.fp_var("neg_alpha", size=slot_rows)

    x_input = prog.input("X", shape=(rows, hidden))
    gathered = prog.moe_gather_token_rows_from_hbm_v0(
        x_input,
        token_offsets_int_base=0,
        pair_count=pair_count,
        hidden=hidden,
        name=f"gather_expert{args.expert_id}_x",
    )

    w_gate_input = prog.input("W_gate", shape=(hidden, w_gate.shape[1]))
    w_up_input = prog.input("W_up", shape=(hidden, w_up.shape[1]))
    w_down_input = prog.input("W_down", shape=(w_down.shape[0], hidden))

    physical_rows = max(blen, math.ceil(slot_rows / blen) * blen)
    bias_physical_inter = (physical_rows, w_gate.shape[1])
    bias_physical_hidden = (physical_rows, hidden)
    bias_base = math.ceil(prog.vram_allocator._vmm.next_bump / (mlen * mlen)) * (mlen * mlen)
    bias_sizes = [
        bias_physical_inter[0] * bias_physical_inter[1],
        bias_physical_inter[0] * bias_physical_inter[1],
        bias_physical_hidden[0] * bias_physical_hidden[1],
    ]
    bias_total = sum(math.ceil(size / (mlen * mlen)) * (mlen * mlen) for size in bias_sizes)
    vram_preload = torch.zeros(bias_base + bias_total, dtype=torch.bfloat16)
    next_bias_addr = bias_base
    bias_vrams = []
    for suffix, tensor, physical_shape in (
        ("gate", b_gate, bias_physical_inter),
        ("up", b_up, bias_physical_inter),
        ("down", b_down, bias_physical_hidden),
    ):
        aligned_size = math.ceil((physical_shape[0] * physical_shape[1]) / (mlen * mlen)) * (mlen * mlen)
        bias_vrams.append(
            prestage_bf16_vram_matrix(
                prog=prog,
                name=f"B_{suffix}",
                tensor=tensor,
                vram_addr=next_bias_addr,
                physical_shape=physical_shape,
                vram_preload=vram_preload,
            )
        )
        next_bias_addr += aligned_size

    output_vram = prog.moe_expert_v0(
        gathered,
        (w_gate_input, w_up_input, w_down_input),
        biases=tuple(bias_vrams),
        rows=slot_rows,
        intermediate=w_gate.shape[1],
        constants=(zero, limit_pos, limit_neg, one, neg_alpha),
        name=f"gather_expert{args.expert_id}",
    )
    isa = prog.compile()
    scale_reg_count = isa.count("C_SET_SCALE_REG")
    if scale_reg_count <= 0:
        raise AssertionError("four-pair expert path must emit C_SET_SCALE_REG for gathered activations/weights")

    input_tensors = {
        "X": x,
        "W_gate": w_gate,
        "W_up": w_up,
        "W_down": w_down,
    }
    tensor_layouts = infer_hbm_tensor_layouts(input_tensors)
    placeholder_golden = torch.zeros(slot_rows, hidden, dtype=torch.bfloat16)
    fp_preload = [0.0] + [7.0] * slot_rows + [-7.0] * slot_rows + [1.0] * slot_rows + [-1.702] * slot_rows
    create_sim_env(
        input_tensors,
        isa,
        {"original_output": placeholder_golden},
        fp_preload=fp_preload,
        int_preload=token_offsets,
        build_dir=str(build_dir),
        vram_preload=vram_preload,
        tensor_layouts=tensor_layouts,
    )
    hbm_addrs = {name: prog._compiler.get_hbm_layout(name).hbm_base_addr for name in input_tensors}
    create_mem_for_sim(
        data_size=256,
        mode="behave_sim",
        asm="gpt_oss_moe_gather_four",
        data=None,
        specified_data_order=list(input_tensors),
        build_path=build_dir,
        input_tensors=input_tensors,
        hbm_addrs=hbm_addrs,
        tensor_layouts=tensor_layouts,
    )

    x_slots = torch.zeros(slot_rows, hidden, dtype=torch.bfloat16)
    for pair_idx, token_offset in enumerate(token_offsets.tolist()):
        x_slots[pair_idx * blen : pair_idx * blen + 1] = _decode_hbm_mxfp8_row(
            build_dir / "hbm_for_behave_sim.bin",
            tensor_base=x_input.hbm_addr,
            tensor_rows=rows,
            tensor_cols=hidden,
            row_element_offset=int(token_offset),
        )
    golden = _expert_golden_from_gathered_vram(
        x_slots,
        w_gate,
        w_up,
        w_down,
        b_gate=b_gate,
        b_up=b_up,
        b_down=b_down,
        mlen=mlen,
    )
    _rewrite_compact_golden(build_dir, golden)

    comparison_params = _comparison_params_for(output_vram, rows=slot_rows, hidden=hidden, mlen=mlen, golden=golden)
    (build_dir / "comparison_params.json").write_text(json.dumps(comparison_params, indent=2) + "\n")
    (build_dir / "generated_asm_code.asm").write_text(isa)
    manifest = {
        "stage": "four",
        "expert_id": args.expert_id,
        "token_indices": token_indices,
        "token_offsets": token_offsets.tolist(),
        "slot_rows": slot_rows,
        "active_rows": [i * blen for i in range(pair_count)],
        "hidden": hidden,
        "intermediate": int(w_gate.shape[1]),
        "mlen": mlen,
        "blen": blen,
        "scale_reg_count": scale_reg_count,
        "output_vram_row": prog._compiler.get_vram_addr(output_vram.name) // mlen,
        "comparison_params": comparison_params,
        "asm_lines": len(isa.splitlines()),
    }
    (build_dir / "gather_scatter_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))
    if args.no_run:
        return {"build_dir": str(build_dir), "ran": False, "manifest": manifest}

    metrics = run_and_assert(
        build_dir,
        "gpt_oss_moe_gather_four",
        mlen=mlen,
        blen=blen,
        threads=args.emu_threads,
    )
    results, params = compare_emulator_output(build_dir)
    emu_output = results["simulated_values"].reshape(slot_rows, hidden).to(torch.bfloat16)
    stats = compare_stats(emu_output, golden, rtol=0.02)
    if stats.rel_rms > 0.02 or not stats.allclose:
        raise AssertionError(
            "four-pair gather+expert failed: "
            f"rel_rms={stats.rel_rms:.6g}, max_abs={stats.max_abs_error:.6g}, allclose={stats.allclose}"
        )

    summary = {
        **manifest,
        "run_metrics": metrics,
        "comparison_params_runtime": params,
        "emulator_compare_raw": {
            key: results[key]
            for key in (
                "mse",
                "mae",
                "max_error",
                "relative_error",
                "relative_match_rate",
                "allclose_match_rate",
                "match_rate",
                "allclose_pass",
                "atol",
                "rtol",
                "golden_shape",
                "simulated_shape",
            )
            if key in results
        },
        "emulator_vs_four_pair_golden": {
            "rel_rms": stats.rel_rms,
            "allclose": stats.allclose,
            "pass_rate": stats.pass_rate,
            "max_abs_error": stats.max_abs_error,
            "atol": stats.atol,
            "rtol": stats.rtol,
        },
        "four_pair_gate": {
            "scale_reg_count_nonzero": scale_reg_count > 0,
            "passed": scale_reg_count > 0 and stats.rel_rms <= 0.02 and stats.allclose,
        },
    }
    (build_dir / "gather_scatter_results.json").write_text(json.dumps(summary, indent=2) + "\n")
    print(json.dumps(summary, indent=2))
    return {"build_dir": str(build_dir), "ran": True, "summary": summary}


def run_full_vram_stage(args: argparse.Namespace) -> dict:
    """Run Step5 segment A, optionally followed by HBM storeback validation."""
    mlen = args.mlen
    blen = args.blen
    build_dir = args.build_dir.expanduser().resolve()
    build_dir.mkdir(parents=True, exist_ok=True)
    hw = setup_hw(args, build_dir)
    store_mode = args.stage in ("hbm_store_single", "hbm_store_full")
    store_single = args.stage == "hbm_store_single"

    ref = _load_tok8_reference(args.reference_path)
    x = ref["x"]
    topk_indices = ref["topk_indices"]
    topk_weights = ref["topk_weights"]
    rows, hidden = x.shape
    if hidden % mlen != 0:
        raise ValueError(f"hidden={hidden} must be divisible by MLEN={mlen}")
    if topk_indices.shape != topk_weights.shape:
        raise ValueError(f"topk indices/weights shape mismatch: {topk_indices.shape} vs {topk_weights.shape}")

    tensors = load_layer_tensors(args.layer_index)
    split = split_packed_gate_up(tensors["gate_up_weight"], tensors["gate_up_bias"])
    down_weight = tensors["down_weight"]
    down_bias = tensors["down_bias"]
    intermediate = int(split.gate_weight.shape[-1])

    selected_experts = [int(v) for v in torch.unique(topk_indices).sort().values.tolist()]
    if args.only_experts:
        requested = [int(part) for part in args.only_experts.split(",") if part.strip()]
        missing = sorted(set(requested) - set(selected_experts))
        if missing:
            raise ValueError(f"--only-experts requested unrouted experts: {missing}")
        selected_experts = requested
    expert_specs = []
    max_slot_rows = blen
    int_preload_values: list[int] = []

    prog = PlenaCompiler(mlen=mlen, blen=blen, real_data_ratio=hw.real_data_ratio)
    zero = prog.fp_var("zero", size=1)
    limit_pos = prog.fp_var("gpt_oss_limit_pos", size=max(blen, rows * blen))
    limit_neg = prog.fp_var("gpt_oss_limit_neg", size=max(blen, rows * blen))
    one = prog.fp_var("one", size=max(blen, rows * blen))
    neg_alpha = prog.fp_var("neg_alpha", size=max(blen, rows * blen))
    shared_zero_row = prog.fp_var("gpt_oss_shared_zero_row", size=mlen)

    x_input = prog.input("X", shape=(rows, hidden))
    acc_physical_rows = max(blen, math.ceil(rows / blen) * blen)
    accumulator = prog.alloc(
        "gather_full_vram_acc",
        rows=rows,
        cols=hidden,
        strict=False,
        physical_shape=(acc_physical_rows, hidden),
    )
    prog.moe_true_zero_vram_rows_v0(
        accumulator,
        rows=list(range(rows)),
        hidden=hidden,
        zero_row=shared_zero_row,
        name="gather_full_acc",
    )

    input_tensors: dict[str, torch.Tensor] = {"X": x}
    route_inputs = {}
    weight_inputs = {}
    gathered_by_expert = {}

    for expert_id in selected_experts:
        token_idx, topk_pos = torch.where(topk_indices == expert_id)
        token_indices = [int(v) for v in token_idx.tolist()]
        topk_positions = [int(v) for v in topk_pos.tolist()]
        if not token_indices:
            continue
        pair_count = len(token_indices)
        slot_rows = pair_count * blen
        max_slot_rows = max(max_slot_rows, slot_rows)
        active_rows = _active_row_indices(pair_count, blen)
        token_offsets_base = len(int_preload_values)
        int_preload_values.extend([token * hidden for token in token_indices])

        gathered_by_expert[expert_id] = prog.moe_gather_token_rows_from_hbm_v0(
            x_input,
            token_offsets_int_base=token_offsets_base,
            pair_count=pair_count,
            hidden=hidden,
            zero_row=shared_zero_row,
            name=f"full_gather_e{expert_id}_x",
        )

        w_gate = split.gate_weight[expert_id].to(torch.bfloat16).contiguous().clone()
        w_up = split.up_weight[expert_id].to(torch.bfloat16).contiguous().clone()
        w_down = down_weight[expert_id].to(torch.bfloat16).contiguous().clone()
        w_gate_name = f"W_e{expert_id}_gate"
        w_up_name = f"W_e{expert_id}_up"
        w_down_name = f"W_e{expert_id}_down"
        w_gate_input = prog.input(w_gate_name, shape=(hidden, intermediate))
        w_up_input = prog.input(w_up_name, shape=(hidden, intermediate))
        w_down_input = prog.input(w_down_name, shape=(intermediate, hidden))
        weight_inputs[expert_id] = (w_gate_input, w_up_input, w_down_input)
        input_tensors[w_gate_name] = w_gate
        input_tensors[w_up_name] = w_up
        input_tensors[w_down_name] = w_down

        route = _slot_route_matrix(
            slot_rows=slot_rows,
            hidden=hidden,
            blen=blen,
            token_indices=token_indices,
            topk_positions=topk_positions,
            topk_weights=topk_weights,
        )
        route_name = f"route_e{expert_id}"
        route_input = prog.input(route_name, shape=(slot_rows, hidden))
        route_inputs[expert_id] = route_input
        input_tensors[route_name] = route

        expert_specs.append(
            {
                "expert_id": expert_id,
                "token_indices": token_indices,
                "topk_positions": topk_positions,
                "pair_count": pair_count,
                "slot_rows": slot_rows,
                "active_rows": active_rows,
                "token_offsets_int_base": token_offsets_base,
                "token_offsets": [token * hidden for token in token_indices],
            }
        )

    route_vrams = {
        expert_id: prog.load_batch(route_input, name=route_input.display_name)
        for expert_id, route_input in route_inputs.items()
    }

    bias_physical: dict[int, tuple[tuple[int, int], tuple[int, int]]] = {}
    bias_sizes = []
    for spec in expert_specs:
        slot_rows = int(spec["slot_rows"])
        physical_rows = max(blen, math.ceil(slot_rows / blen) * blen)
        inter_shape = (physical_rows, intermediate)
        hidden_shape = (physical_rows, hidden)
        bias_physical[int(spec["expert_id"])] = (inter_shape, hidden_shape)
        bias_sizes.extend(
            [
                inter_shape[0] * inter_shape[1],
                inter_shape[0] * inter_shape[1],
                hidden_shape[0] * hidden_shape[1],
            ]
        )
    bias_base = math.ceil(prog.vram_allocator._vmm.next_bump / (mlen * mlen)) * (mlen * mlen)
    bias_total = sum(math.ceil(size / (mlen * mlen)) * (mlen * mlen) for size in bias_sizes)
    vram_preload = torch.zeros(bias_base + bias_total, dtype=torch.bfloat16)
    next_bias_addr = bias_base
    bias_vrams = {}
    for spec in expert_specs:
        expert_id = int(spec["expert_id"])
        slot_rows = int(spec["slot_rows"])
        inter_shape, hidden_shape = bias_physical[expert_id]
        b_gate = _expanded_bias(split.gate_bias[expert_id], slot_rows)
        b_up = _expanded_bias(split.up_bias[expert_id], slot_rows)
        b_down = _expanded_bias(down_bias[expert_id], slot_rows)
        local_bias_vrams = []
        for suffix, tensor, physical_shape in (
            ("gate", b_gate, inter_shape),
            ("up", b_up, inter_shape),
            ("down", b_down, hidden_shape),
        ):
            size = physical_shape[0] * physical_shape[1]
            aligned_size = math.ceil(size / (mlen * mlen)) * (mlen * mlen)
            local_bias_vrams.append(
                prestage_bf16_vram_matrix(
                    prog=prog,
                    name=f"B_e{expert_id}_{suffix}",
                    tensor=tensor,
                    vram_addr=next_bias_addr,
                    physical_shape=physical_shape,
                    vram_preload=vram_preload,
                )
            )
            next_bias_addr += aligned_size
        bias_vrams[expert_id] = tuple(local_bias_vrams)

    for spec in expert_specs:
        expert_id = int(spec["expert_id"])
        output_vram = prog.moe_expert_v0(
            gathered_by_expert[expert_id],
            weight_inputs[expert_id],
            biases=bias_vrams[expert_id],
            rows=int(spec["slot_rows"]),
            intermediate=intermediate,
            constants=(zero, limit_pos, limit_neg, one, neg_alpha),
            name=f"full_vram_e{expert_id}",
        )
        prog.vram_mul(output_vram, route_vrams[expert_id], num_rows=int(spec["slot_rows"]))
        prog.moe_scatter_add_active_rows_v0(
            accumulator,
            output_vram,
            token_indices=list(spec["token_indices"]),
            active_rows=list(spec["active_rows"]),
            hidden=hidden,
            name=f"expert{expert_id}",
        )

    store_token_indices: list[int] = []
    output_slot_hbm_base = None
    output_slot_hbm_stride = None
    expected_h_store_v_dynamic_count = 0
    if store_mode:
        if args.only_experts:
            raise ValueError("HBM store stages require the full routed expert set; do not pass --only-experts")
        if args.store_token_index < 0 or args.store_token_index >= rows:
            raise ValueError(f"store_token_index={args.store_token_index} out of range [0, {rows})")
        store_token_indices = [args.store_token_index] if store_single else list(range(rows))
        output_slot_hbm_stride = int(blen * hidden * prog.real_data_ratio)
        output_slot_hbm_base = prog._allocate_hbm(output_slot_hbm_stride * rows)
        store_slot = prog.alloc(
            "gather_full_hbm_store_slot",
            rows=blen,
            cols=hidden,
            strict=False,
            physical_shape=(blen, hidden),
        )
        for token_idx in store_token_indices:
            prog.moe_true_zero_vram_rows_v0(
                store_slot,
                rows=list(range(blen)),
                hidden=hidden,
                zero_row=shared_zero_row,
                name=f"hbm_store_t{token_idx}_zero",
            )
            prog.moe_scatter_add_active_rows_v0(
                store_slot,
                accumulator,
                token_indices=[0],
                active_rows=[token_idx],
                hidden=hidden,
                name=f"hbm_store_t{token_idx}_copy",
            )
            prog.store(
                store_slot,
                name=f"gather_full_output_slot_t{token_idx}",
                hbm_addr=output_slot_hbm_base + token_idx * output_slot_hbm_stride,
            )
        expected_h_store_v_dynamic_count = len(store_token_indices) * math.ceil(hidden / mlen)

    isa = prog.compile()
    scale_reg_count = isa.count("C_SET_SCALE_REG")
    h_store_count = isa.count("H_STORE_V")
    if scale_reg_count <= 0:
        raise AssertionError("full VRAM gather/expert path must emit C_SET_SCALE_REG for MXFP8 tensors")
    expected_h_store_v_source_count = len(store_token_indices)
    if not store_mode and h_store_count != 0:
        raise AssertionError(f"segment A must not emit H_STORE_V, got {h_store_count}")
    if store_mode and h_store_count != expected_h_store_v_source_count:
        raise AssertionError(
            f"HBM store stage expected {expected_h_store_v_source_count} source H_STORE_V instructions, "
            f"got {h_store_count}"
        )

    tensor_layouts = infer_hbm_tensor_layouts(input_tensors)
    l1_golden_path = args.l1_golden_path.expanduser().resolve()
    l1_golden = _load_l1_golden(l1_golden_path)
    if tuple(l1_golden.shape) != (rows, hidden):
        raise ValueError(f"L1 golden shape {tuple(l1_golden.shape)} does not match {(rows, hidden)}")
    fp_preload = [0.0] + [7.0] * max(blen, rows * blen) + [-7.0] * max(blen, rows * blen)
    fp_preload += [1.0] * max(blen, rows * blen) + [-1.702] * max(blen, rows * blen)
    int_preload = torch.tensor(int_preload_values, dtype=torch.int32)
    create_sim_env(
        input_tensors,
        isa,
        {"original_output": l1_golden},
        fp_preload=fp_preload,
        int_preload=int_preload,
        build_dir=str(build_dir),
        vram_preload=vram_preload,
        tensor_layouts=tensor_layouts,
    )
    hbm_addrs = {name: prog._compiler.get_hbm_layout(name).hbm_base_addr for name in input_tensors}
    create_mem_for_sim(
        data_size=256,
        mode="behave_sim",
        asm="gpt_oss_moe_gather_full_vram",
        data=None,
        specified_data_order=list(input_tensors),
        build_path=build_dir,
        input_tensors=input_tensors,
        hbm_addrs=hbm_addrs,
        tensor_layouts=tensor_layouts,
    )
    if store_mode:
        assert output_slot_hbm_base is not None
        assert output_slot_hbm_stride is not None
        required_hbm_size = output_slot_hbm_base + output_slot_hbm_stride * rows
        required_hbm_size = ((required_hbm_size + 63) // 64) * 64
        (build_dir / "hbm_size.txt").write_text(f"{required_hbm_size}\n")

    exact_golden = torch.zeros(rows, hidden, dtype=torch.bfloat16)
    clamp_counts = {
        "gate_gt_7": 0,
        "gate_lt_neg_7": 0,
        "up_gt_7": 0,
        "up_lt_neg_7": 0,
        "per_token": [
            {"token_index": token_idx, "gate_gt_7": 0, "gate_lt_neg_7": 0, "up_gt_7": 0, "up_lt_neg_7": 0}
            for token_idx in range(rows)
        ],
    }
    for spec in expert_specs:
        expert_id = int(spec["expert_id"])
        slot_rows = int(spec["slot_rows"])
        token_indices = list(spec["token_indices"])
        active_rows = list(spec["active_rows"])
        w_gate = input_tensors[f"W_e{expert_id}_gate"]
        w_up = input_tensors[f"W_e{expert_id}_up"]
        w_down = input_tensors[f"W_e{expert_id}_down"]
        b_gate = _expanded_bias(split.gate_bias[expert_id], slot_rows)
        b_up = _expanded_bias(split.up_bias[expert_id], slot_rows)
        b_down = _expanded_bias(down_bias[expert_id], slot_rows)

        x_slots = torch.zeros(slot_rows, hidden, dtype=torch.bfloat16)
        for pair_idx, token_offset in enumerate(spec["token_offsets"]):
            x_slots[pair_idx * blen : pair_idx * blen + 1] = _decode_hbm_mxfp8_row(
                build_dir / "hbm_for_behave_sim.bin",
                tensor_base=x_input.hbm_addr,
                tensor_rows=rows,
                tensor_cols=hidden,
                row_element_offset=int(token_offset),
            )

        gate_pre = _linear_projection_golden(x_slots, w_gate, mlen=mlen, hbm_input=False)
        up_pre = _linear_projection_golden(x_slots, w_up, mlen=mlen, hbm_input=False)
        gate_pre = _bf16(gate_pre.float() + b_gate.float())
        up_pre = _bf16(up_pre.float() + b_up.float())
        local_clamp = _clamp_counts_from_slots(
            token_indices=token_indices,
            gate=gate_pre,
            up=up_pre,
            blen=blen,
            rows=rows,
        )
        for key in ("gate_gt_7", "gate_lt_neg_7", "up_gt_7", "up_lt_neg_7"):
            clamp_counts[key] += local_clamp[key]
        for token_idx, item in enumerate(local_clamp["per_token"]):
            for key in ("gate_gt_7", "gate_lt_neg_7", "up_gt_7", "up_lt_neg_7"):
                clamp_counts["per_token"][token_idx][key] += item[key]

        expert_out = _expert_golden_from_gathered_vram(
            x_slots,
            w_gate,
            w_up,
            w_down,
            b_gate=b_gate,
            b_up=b_up,
            b_down=b_down,
            mlen=mlen,
        )

        route_exact = torch.zeros(slot_rows, hidden, dtype=torch.bfloat16)
        route_input = route_inputs[expert_id]
        for active_row in active_rows:
            route_exact[active_row : active_row + 1] = _decode_hbm_mxfp8_row(
                build_dir / "hbm_for_behave_sim.bin",
                tensor_base=route_input.hbm_addr,
                tensor_rows=slot_rows,
                tensor_cols=hidden,
                row_element_offset=active_row * hidden,
            )
        weighted = _bf16(expert_out.float() * route_exact.float())
        for pair_idx, token_idx in enumerate(token_indices):
            active_row = pair_idx * blen
            exact_golden[token_idx] = _bf16(exact_golden[token_idx].float() + weighted[active_row].float())

    exact_vs_l1 = compare_stats(exact_golden, l1_golden, rtol=0.02)
    torch.save(exact_golden.float(), build_dir / "exact_hbm_decode_full_vram_golden.pt")
    # Segment A's mechanism anchor is the exact tensor produced by the same
    # HBM-decode semantics as the device gather path.  The archived L1 golden
    # remains recorded below as an external continuity check; it carries the
    # already adjudicated BF16 tail residual from the direct L1 proof.
    target_golden = exact_golden
    target_golden_name = "exact_hbm_decode_subset_golden" if args.only_experts else "exact_hbm_decode_full_golden"
    _rewrite_compact_golden(build_dir, target_golden)

    comparison_params = _comparison_params_for(accumulator, rows=rows, hidden=hidden, mlen=mlen, golden=target_golden)
    (build_dir / "comparison_params.json").write_text(json.dumps(comparison_params, indent=2) + "\n")
    (build_dir / "generated_asm_code.asm").write_text(isa)
    manifest = {
        "stage": args.stage,
        "reference_path": str(args.reference_path.expanduser().resolve()),
        "l1_golden_path": str(l1_golden_path),
        "selected_experts": selected_experts,
        "only_experts": args.only_experts,
        "target_golden": target_golden_name,
        "expert_specs": expert_specs,
        "rows": rows,
        "hidden": hidden,
        "intermediate": intermediate,
        "mlen": mlen,
        "blen": blen,
        "scale_reg_count": scale_reg_count,
        "h_store_v_count": h_store_count,
        "expected_h_store_v_source_count": expected_h_store_v_source_count,
        "expected_h_store_v_dynamic_count": expected_h_store_v_dynamic_count,
        "segment_a_no_h_store": (not store_mode) and h_store_count == 0,
        "store_mode": args.stage if store_mode else None,
        "store_token_indices": store_token_indices,
        "output_slot_hbm_base": output_slot_hbm_base,
        "output_slot_hbm_stride": output_slot_hbm_stride,
        "output_slot_hbm_total_bytes": None if output_slot_hbm_stride is None else output_slot_hbm_stride * rows,
        "accumulator_vram_row": prog._compiler.get_vram_addr(accumulator.name) // mlen,
        "comparison_params": comparison_params,
        "clamp_counts": clamp_counts,
        "exact_hbm_decode_golden_vs_l1_golden": _stats_dict(exact_vs_l1),
        "asm_lines": len(isa.splitlines()),
    }
    (build_dir / "gather_scatter_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))
    if args.no_run:
        return {"build_dir": str(build_dir), "ran": False, "manifest": manifest}

    old_rust_log = os.environ.get("PLENA_EMULATOR_RUST_LOG")
    if store_mode:
        # HBM dumps are gated behind DEBUG tracing in the Rust runner.  Keep
        # other modules quiet so storeback validation does not drown in DMA logs.
        os.environ["PLENA_EMULATOR_RUST_LOG"] = "warn,transactional_emulator=info,transactional_emulator::runner=debug"
    try:
        metrics = run_and_assert(
            build_dir,
            "gpt_oss_moe_gather_full_vram",
            mlen=mlen,
            blen=blen,
            threads=args.emu_threads,
        )
    finally:
        if store_mode:
            if old_rust_log is None:
                os.environ.pop("PLENA_EMULATOR_RUST_LOG", None)
            else:
                os.environ["PLENA_EMULATOR_RUST_LOG"] = old_rust_log
    results, params = compare_emulator_output(build_dir)
    emu_output = results["simulated_values"].reshape(rows, hidden).to(torch.bfloat16)
    emu_l1_stats = compare_stats(emu_output, target_golden, rtol=0.02)
    emu_exact_stats = compare_stats(emu_output, exact_golden, rtol=0.02)
    elementwise = _strict_elementwise_details(emu_output, target_golden, rtol=0.02)
    tail_gate = _tail_gate_details(
        emu_output,
        target_golden,
        strict_details=elementwise,
        clamp_counts=clamp_counts,
        rtol=0.02,
    )

    hbm_store_summary = None
    if store_mode:
        assert output_slot_hbm_base is not None
        assert output_slot_hbm_stride is not None
        hbm_before_path = build_dir / "hbm_for_behave_sim.bin"
        hbm_after_path = build_dir / "hbm_dump.bin"
        if not hbm_after_path.exists():
            raise AssertionError("HBM store stage expected hbm_dump.bin; DEBUG runner dump was not produced")
        hbm_before = hbm_before_path.read_bytes()
        hbm_after = hbm_after_path.read_bytes()
        decoded_slots = _decode_hbm_mxfp8_output_slots(
            hbm_after,
            slot_base=output_slot_hbm_base,
            slot_stride=output_slot_hbm_stride,
            rows=rows,
            hidden=hidden,
            blen=blen,
        )
        torch.save(decoded_slots.float(), build_dir / "hbm_store_decoded_output_slots.pt")
        store_quant_golden = quantize_to_mxfp(exact_golden).to(torch.bfloat16)
        torch.save(store_quant_golden.float(), build_dir / "hbm_store_quantized_exact_golden.pt")

        compare_tokens = store_token_indices if store_single else list(range(rows))
        decoded_cmp = decoded_slots[compare_tokens]
        quant_cmp = store_quant_golden[compare_tokens]
        exact_cmp = exact_golden[compare_tokens]
        l1_cmp = l1_golden[compare_tokens]
        hbm_vs_quant = compare_stats(decoded_cmp, quant_cmp, rtol=0.0)
        hbm_vs_exact = compare_stats(decoded_cmp, exact_cmp, rtol=0.02)
        hbm_vs_l1 = compare_stats(decoded_cmp, l1_cmp, rtol=0.02)
        padding_zero = _hbm_slot_padding_zero(
            hbm_after,
            slot_base=output_slot_hbm_base,
            slot_stride=output_slot_hbm_stride,
            token_indices=store_token_indices,
            hidden=hidden,
            blen=blen,
        )
        neighbor_unchanged = (
            _hbm_unwritten_slots_unchanged(
                hbm_before,
                hbm_after,
                slot_base=output_slot_hbm_base,
                slot_stride=output_slot_hbm_stride,
                rows=rows,
                written_tokens=store_token_indices,
            )
            if store_single
            else {
                "written_tokens": store_token_indices,
                "unchanged_tokens_checked": [],
                "changed_unwritten_slots": [],
                "passed": True,
            }
        )
        source_count_ok = h_store_count == expected_h_store_v_source_count
        # HBM byte statistics are useful telemetry, but not a correctness
        # oracle: unaligned read-modify-write may count internal chunk bytes.
        dynamic_bytes_match_logical = metrics.get("hbm_bytes_written") == output_slot_hbm_stride * len(
            store_token_indices
        )
        hbm_store_summary = {
            "stage": args.stage,
            "store_token_indices": store_token_indices,
            "output_slot_hbm_base": output_slot_hbm_base,
            "output_slot_hbm_stride": output_slot_hbm_stride,
            "source_h_store_v_count": h_store_count,
            "expected_source_h_store_v_count": expected_h_store_v_source_count,
            "source_h_store_v_count_matches": source_count_ok,
            "expected_dynamic_h_store_v_count": expected_h_store_v_dynamic_count,
            "hbm_bytes_written": metrics.get("hbm_bytes_written"),
            "expected_hbm_bytes_written": output_slot_hbm_stride * len(store_token_indices),
            "hbm_bytes_written_matches_logical_payload": dynamic_bytes_match_logical,
            "decoded_vs_quantized_exact_golden": _stats_dict(hbm_vs_quant),
            "decoded_vs_quantized_exact_golden_bit_exact": hbm_vs_quant.max_abs_error == 0.0 and hbm_vs_quant.allclose,
            "decoded_vs_exact_hbm_decode_golden": _stats_dict(hbm_vs_exact),
            "decoded_vs_l1_golden": _stats_dict(hbm_vs_l1),
            "padding_rows_zero": padding_zero,
            "unwritten_neighbor_slots_unchanged": neighbor_unchanged,
            "passed": source_count_ok
            and hbm_vs_quant.max_abs_error == 0.0
            and hbm_vs_quant.allclose
            and padding_zero["passed"]
            and neighbor_unchanged["passed"],
        }
        (build_dir / "hbm_store_results.json").write_text(json.dumps(hbm_store_summary, indent=2) + "\n")

    summary = {
        **manifest,
        "run_metrics": metrics,
        "comparison_params_runtime": params,
        "emulator_compare_raw": {
            key: results[key]
            for key in (
                "mse",
                "mae",
                "max_error",
                "relative_error",
                "relative_match_rate",
                "allclose_match_rate",
                "match_rate",
                "allclose_pass",
                "atol",
                "rtol",
                "golden_shape",
                "simulated_shape",
            )
            if key in results
        },
        "emulator_vs_target_golden": _stats_dict(emu_l1_stats),
        "emulator_vs_target_elementwise": elementwise,
        "emulator_vs_target_tail_gate": tail_gate,
        "emulator_vs_exact_hbm_decode_golden": _stats_dict(emu_exact_stats),
        "hbm_store_gate": hbm_store_summary,
        "full_vram_gate": {
            "scale_reg_count_nonzero": scale_reg_count > 0,
            "no_h_store_v": (not store_mode) and h_store_count == 0,
            "h_store_v_count_expected": (h_store_count == expected_h_store_v_source_count)
            if store_mode
            else h_store_count == 0,
            "emu_vs_l1_rel_rms_under_2pct": emu_l1_stats.rel_rms <= 0.02,
            "emu_vs_l1_strict_allclose": emu_l1_stats.allclose,
            "emu_vs_l1_tail_gate_passed": tail_gate["passed"],
            "passed": scale_reg_count > 0
            and ((h_store_count == 0) if not store_mode else h_store_count == expected_h_store_v_source_count)
            and emu_l1_stats.rel_rms <= 0.02
            and (emu_l1_stats.allclose or tail_gate["passed"])
            and (hbm_store_summary is None or hbm_store_summary["passed"]),
        },
    }
    (build_dir / "gather_scatter_results.json").write_text(json.dumps(summary, indent=2) + "\n")
    print(json.dumps(summary, indent=2))
    if not summary["full_vram_gate"]["passed"]:
        raise AssertionError(
            "full VRAM gather/expert/scatter-combine failed: "
            f"rel_rms={emu_l1_stats.rel_rms:.6g}, allclose={emu_l1_stats.allclose}, "
            f"tail_gate={tail_gate['passed']}, scale_regs={scale_reg_count}, h_store_v={h_store_count}"
        )
    return {"build_dir": str(build_dir), "ran": True, "summary": summary}


def run_device_routing_stage(args: argparse.Namespace) -> dict:
    """Run Step6 dynamic expert dispatch: V_TOPK id -> true expert weight table."""
    mlen = args.mlen
    blen = args.blen
    build_dir = args.build_dir.expanduser().resolve()
    build_dir.mkdir(parents=True, exist_ok=True)
    hw = setup_hw(args, build_dir)

    ref = _load_tok8_reference(args.reference_path)
    x = ref["x"]
    hf_topk_indices = ref["topk_indices"]
    _hf_topk_weights = ref["topk_weights"]
    rows, hidden = x.shape
    top_k = int(hf_topk_indices.shape[1])
    vram_source = args.stage in ("device_routing_vram_single", "device_routing_vram_full")
    full_pairs = args.stage in ("device_routing_full", "device_routing_vram_full")
    pair_count = rows * top_k if full_pairs else 1
    if hidden % mlen != 0:
        raise ValueError(f"hidden={hidden} must be divisible by MLEN={mlen}")
    if top_k != 4:
        raise ValueError(f"GPT-OSS v0 expects top_k=4, got {top_k}")

    tensors = load_layer_tensors(args.layer_index)
    split = split_packed_gate_up(tensors["gate_up_weight"], tensors["gate_up_bias"])
    down_weight = tensors["down_weight"]
    down_bias = tensors["down_bias"]
    router_weight, router_bias = tensors["router_weight"], tensors["router_bias"]
    router_weight_rows = router_weight.contiguous()
    intermediate = int(split.gate_weight.shape[-1])
    num_experts = int(split.gate_weight.shape[0])

    hf_logits = F.linear(x, router_weight, router_bias).to(torch.bfloat16)
    hf_top_values, hf_top_indices_from_logits = torch.topk(hf_logits, k=top_k, dim=-1)
    hf_top_weights_from_logits = torch.softmax(hf_top_values, dim=1, dtype=hf_top_values.dtype).to(torch.bfloat16)
    if not torch.equal(hf_top_indices_from_logits.cpu(), hf_topk_indices.cpu()):
        raise AssertionError("reference topk_indices differ from HF router recomputation")

    prog = PlenaCompiler(mlen=mlen, blen=blen, real_data_ratio=hw.real_data_ratio)
    zero = prog.fp_var("zero", size=1)
    constant_rows = max(blen, rows * blen)
    limit_pos = prog.fp_var("gpt_oss_limit_pos", size=constant_rows)
    limit_neg = prog.fp_var("gpt_oss_limit_neg", size=constant_rows)
    one = prog.fp_var("one", size=constant_rows)
    neg_alpha = prog.fp_var("neg_alpha", size=constant_rows)
    shared_zero_row = prog.fp_var("gpt_oss_shared_zero_row", size=mlen)

    physical_rows = max(blen, math.ceil(rows / blen) * blen)
    input_tensors: dict[str, torch.Tensor] = {}
    x_input = prog.input("X", shape=(rows, hidden))
    input_tensors["X"] = x

    gate_inputs, gate_table_base, gate_stride = _build_true_expert_weight_table(
        prog,
        prefix="W_gate",
        weights=split.gate_weight.to(torch.bfloat16),
        input_tensors=input_tensors,
    )
    up_inputs, up_table_base, up_stride = _build_true_expert_weight_table(
        prog,
        prefix="W_up",
        weights=split.up_weight.to(torch.bfloat16),
        input_tensors=input_tensors,
    )
    down_inputs, down_table_base, down_stride = _build_true_expert_weight_table(
        prog,
        prefix="W_down",
        weights=down_weight.to(torch.bfloat16),
        input_tensors=input_tensors,
    )
    weight_templates = (gate_inputs[0], up_inputs[0], down_inputs[0])
    weight_table_bases = (gate_table_base, up_table_base, down_table_base)
    weight_table_strides = (gate_stride, up_stride, down_stride)

    # Prestaged BF16 router operands and expert bias tables.
    router_x_physical = (physical_rows, hidden)
    router_w_physical = (num_experts, hidden)
    router_bias_physical = (physical_rows, mlen)
    bias_inter_physical = (num_experts * blen, intermediate)
    bias_hidden_physical = (num_experts * blen, hidden)
    alignment = mlen * mlen
    router_x_base = 0
    router_w_base = _align_to(router_x_base + _vram_layout_size(router_x_physical, mlen=mlen), alignment)
    router_bias_base = _align_to(router_w_base + _vram_layout_size(router_w_physical, mlen=mlen), alignment)
    gate_bias_base = _align_to(router_bias_base + _vram_layout_size(router_bias_physical, mlen=mlen), alignment)
    up_bias_base = _align_to(gate_bias_base + _vram_layout_size(bias_inter_physical, mlen=mlen), alignment)
    down_bias_base = _align_to(up_bias_base + _vram_layout_size(bias_inter_physical, mlen=mlen), alignment)
    preload_size = down_bias_base + _vram_layout_size(bias_hidden_physical, mlen=mlen)
    vram_preload = torch.zeros(preload_size, dtype=torch.bfloat16)

    router_x = prestage_bf16_vram_matrix(
        prog=prog,
        name="Step6RouterXBF16",
        tensor=x,
        vram_addr=router_x_base,
        physical_shape=router_x_physical,
        vram_preload=vram_preload,
    )
    router_w = prestage_bf16_vram_matrix(
        prog=prog,
        name="Step6RouterWBF16",
        tensor=router_weight_rows,
        vram_addr=router_w_base,
        physical_shape=router_w_physical,
        vram_preload=vram_preload,
    )
    router_bias_rows = router_bias.reshape(1, -1).repeat(rows, 1).to(torch.bfloat16)
    router_bias_vram = prestage_bf16_vram_matrix(
        prog=prog,
        name="Step6RouterBias",
        tensor=router_bias_rows,
        vram_addr=router_bias_base,
        physical_shape=router_bias_physical,
        vram_preload=vram_preload,
    )
    gate_bias_table = _build_true_expert_bias_table(
        prog=prog,
        name="Step6GateBiasTable",
        bias=split.gate_bias,
        width=intermediate,
        blen=blen,
        vram_addr=gate_bias_base,
        vram_preload=vram_preload,
    )
    up_bias_table = _build_true_expert_bias_table(
        prog=prog,
        name="Step6UpBiasTable",
        bias=split.up_bias,
        width=intermediate,
        blen=blen,
        vram_addr=up_bias_base,
        vram_preload=vram_preload,
    )
    down_bias_table = _build_true_expert_bias_table(
        prog=prog,
        name="Step6DownBiasTable",
        bias=down_bias,
        width=hidden,
        blen=blen,
        vram_addr=down_bias_base,
        vram_preload=vram_preload,
    )

    logits = prog.moe_router_logits_bf16_v0(
        router_x,
        router_w,
        rows=rows,
        hidden=hidden,
        num_experts=num_experts,
        name="step6_router_logits",
    )
    prog.vram_add(logits, router_bias_vram, num_rows=rows)
    topk_weight_var = prog.fp_var("step6_topk_weights", size=rows * top_k)
    topk_weights_fp_base = topk_weight_var.address
    topk_indices_int_base = 0
    token_offsets_int_base = rows * top_k
    token_offsets = [token_idx * hidden for token_idx in range(rows) for _ in range(top_k)]
    for token_idx in range(rows):
        prog.moe_router_select_v0(
            logits,
            token_idx=token_idx,
            weights_fp_base=topk_weights_fp_base + token_idx * top_k,
            indices_int_base=topk_indices_int_base + token_idx * top_k,
            name=f"token{token_idx}",
        )

    accumulator = prog.alloc(
        "step6_device_routing_acc",
        rows=rows,
        cols=hidden,
        strict=False,
        physical_shape=(physical_rows, hidden),
    )
    prog.moe_true_zero_vram_rows_v0(
        accumulator,
        rows=list(range(rows)),
        hidden=hidden,
        zero_row=shared_zero_row,
        name="step6_acc_zero",
    )
    route_fp_scratch = prog.fp_var("step6_route_fp_scratch", size=mlen)

    for pair_idx in range(pair_count):
        token_idx = pair_idx // top_k
        if vram_source:
            gathered = prog.moe_gather_token_rows_from_vram_v0(
                router_x,
                token_indices=[token_idx],
                hidden=hidden,
                zero_row=shared_zero_row,
                name=f"step6_pair{pair_idx}_vram_gather_t{token_idx}",
            )
        else:
            gathered = prog.moe_gather_token_rows_from_hbm_v0(
                x_input,
                token_offsets_int_base=token_offsets_int_base + pair_idx,
                pair_count=1,
                hidden=hidden,
                zero_row=shared_zero_row,
                name=f"step6_pair{pair_idx}_gather_t{token_idx}",
            )
        output = prog.moe_dynamic_expert_pair_v0(
            gathered,
            weight_templates,
            weight_table_bases=weight_table_bases,
            weight_table_strides=weight_table_strides,
            expert_indices_int_base=topk_indices_int_base,
            weights_fp_base=topk_weights_fp_base,
            pair_idx=pair_idx,
            bias_tables=(gate_bias_table, up_bias_table, down_bias_table),
            rows=blen,
            intermediate=intermediate,
            constants=(zero, limit_pos, limit_neg, one, neg_alpha),
            zero_row=shared_zero_row,
            route_fp_scratch=route_fp_scratch,
            name=f"step6_pair{pair_idx}",
        )
        prog.moe_scatter_add_active_rows_v0(
            accumulator,
            output,
            token_indices=[token_idx],
            active_rows=[0],
            hidden=hidden,
            name=f"step6_pair{pair_idx}_scatter",
        )

    isa = prog.compile()
    scale_reg_count = isa.count("C_SET_SCALE_REG")
    if scale_reg_count <= 0:
        raise AssertionError("device-routing expert path must emit C_SET_SCALE_REG for MXFP8 expert tensors")
    h_prefetch_v_count = isa.count("H_PREFETCH_V")
    if vram_source and h_prefetch_v_count != 0:
        raise AssertionError(
            f"VRAM-resident MoE input path must not use H_PREFETCH_V/HBM activation gather; found {h_prefetch_v_count}"
        )

    tensor_layouts = infer_hbm_tensor_layouts(input_tensors)
    dummy_golden = torch.zeros(rows, hidden, dtype=torch.bfloat16)
    fp_preload = [0.0] + [7.0] * constant_rows + [-7.0] * constant_rows
    fp_preload += [1.0] * constant_rows + [-1.702] * constant_rows
    fp_preload_len = max(route_fp_scratch.address + route_fp_scratch.size, topk_weights_fp_base + rows * top_k)
    if len(fp_preload) < fp_preload_len:
        fp_preload.extend([0.0] * (fp_preload_len - len(fp_preload)))
    int_preload = torch.zeros(token_offsets_int_base + len(token_offsets), dtype=torch.int32)
    int_preload[token_offsets_int_base : token_offsets_int_base + len(token_offsets)] = torch.tensor(
        token_offsets, dtype=torch.int32
    )

    create_sim_env(
        input_tensors,
        isa,
        {"original_output": dummy_golden},
        fp_preload=fp_preload,
        int_preload=int_preload,
        build_dir=str(build_dir),
        vram_preload=vram_preload,
        tensor_layouts=tensor_layouts,
    )
    hbm_addrs = {name: prog._compiler.get_hbm_layout(name).hbm_base_addr for name in input_tensors}
    create_mem_for_sim(
        data_size=256,
        mode="behave_sim",
        asm="gpt_oss_moe_device_routing",
        data=None,
        specified_data_order=list(input_tensors),
        build_path=build_dir,
        input_tensors=input_tensors,
        hbm_addrs=hbm_addrs,
        tensor_layouts=tensor_layouts,
    )

    output_addr = prog._compiler.get_vram_addr(accumulator.name)
    comparison_params = _comparison_params_for(accumulator, rows=rows, hidden=hidden, mlen=mlen, golden=dummy_golden)
    (build_dir / "comparison_params.json").write_text(json.dumps(comparison_params, indent=2) + "\n")
    (build_dir / "generated_asm_code.asm").write_text(isa)
    manifest = {
        "stage": args.stage,
        "reference_path": str(args.reference_path.expanduser().resolve()),
        "layer_index": args.layer_index,
        "rows": rows,
        "hidden": hidden,
        "intermediate": intermediate,
        "num_experts": num_experts,
        "top_k": top_k,
        "pair_count": pair_count,
        "mlen": mlen,
        "blen": blen,
        "true_expert_weight_tables": {
            "gate": {"base": gate_table_base, "stride": gate_stride},
            "up": {"base": up_table_base, "stride": up_stride},
            "down": {"base": down_table_base, "stride": down_stride},
        },
        "helper_contract": "expert_id_to_weight_base = table_base + true_expert_id * per_expert_stride",
        "moe_input_source": "vram_bf16" if vram_source else "hbm_mxfp8",
        "topk_weights_fp_base": topk_weights_fp_base,
        "topk_indices_int_base": topk_indices_int_base,
        "token_offsets_int_base": token_offsets_int_base,
        "scale_reg_count": scale_reg_count,
        "h_prefetch_v_count": h_prefetch_v_count,
        "accumulator_vram_row": output_addr // mlen,
        "comparison_params": comparison_params,
        "asm_lines": len(isa.splitlines()),
    }
    (build_dir / "device_routing_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    if args.no_run:
        print(json.dumps(manifest, indent=2))
        return {"build_dir": str(build_dir), "ran": False, "manifest": manifest}

    metrics = run_emulator(build_dir, threads=args.emu_threads)
    device_indices_flat = _decode_u32_dump(build_dir / "intsram_dump.bin")[
        topk_indices_int_base : topk_indices_int_base + rows * top_k
    ]
    device_weights_flat = _decode_bf16_dump(build_dir / "fpsram_dump.bin")[
        topk_weights_fp_base : topk_weights_fp_base + rows * top_k
    ]
    device_indices = device_indices_flat.reshape(rows, top_k)
    device_weights = device_weights_flat.reshape(rows, top_k).to(torch.bfloat16)
    if vram_source:
        exact_golden, clamp_counts = _device_routing_vram_exact_golden(
            x=x,
            device_indices=device_indices,
            device_weights=device_weights,
            split=split,
            down_weight=down_weight,
            down_bias=down_bias,
            rows=rows,
            hidden=hidden,
            blen=blen,
            mlen=mlen,
            pair_count=pair_count,
        )
    else:
        exact_golden, clamp_counts = _device_routing_exact_golden(
            hbm_path=build_dir / "hbm_for_behave_sim.bin",
            x_input=x_input,
            x=x,
            device_indices=device_indices,
            device_weights=device_weights,
            split=split,
            down_weight=down_weight,
            down_bias=down_bias,
            rows=rows,
            hidden=hidden,
            blen=blen,
            mlen=mlen,
            pair_count=pair_count,
        )
    torch.save(exact_golden.float(), build_dir / "device_selected_exact_golden.pt")
    target_golden = exact_golden
    _rewrite_compact_golden(build_dir, target_golden)
    comparison_params = _comparison_params_for(accumulator, rows=rows, hidden=hidden, mlen=mlen, golden=target_golden)
    (build_dir / "comparison_params.json").write_text(json.dumps(comparison_params, indent=2) + "\n")
    results, params = compare_emulator_output(build_dir)
    emu_output = results["simulated_values"].reshape(rows, hidden).to(torch.bfloat16)
    emu_target_stats = compare_stats(emu_output, target_golden, rtol=0.02)
    emu_l1_stats = compare_stats(
        emu_output,
        _load_l1_golden(args.l1_golden_path),
        rtol=0.02,
    )
    elementwise = _strict_elementwise_details(emu_output, target_golden, rtol=0.02)
    tail_gate = _tail_gate_details(
        emu_output,
        target_golden,
        strict_details=elementwise,
        clamp_counts=clamp_counts,
        rtol=0.02,
    )
    device_router_logits = _router_vector_bf16_golden(x, router_weight_rows, router_bias, mlen=mlen)
    router_rank_gate = _rank_stability(
        hf_logits,
        device_router_logits,
        top_k,
    )
    topk_contract = _device_topk_contract(
        hf_indices=hf_topk_indices,
        hf_weights=hf_top_weights_from_logits,
        device_indices=device_indices,
        device_weights=device_weights,
        device_logits=device_router_logits,
        rank_gate=router_rank_gate,
    )
    exact_vs_l1 = compare_stats(
        target_golden,
        _load_l1_golden(args.l1_golden_path),
        rtol=0.02,
    )

    summary = {
        **manifest,
        "run_metrics": metrics,
        "comparison_params_runtime": params,
        "device_topk": topk_contract,
        "router_rank_gate_against_hf": router_rank_gate,
        "device_selected_exact_golden_vs_l1_record_only": _stats_dict(exact_vs_l1),
        "emulator_vs_device_selected_exact_golden": _stats_dict(emu_target_stats),
        "emulator_vs_l1_record_only": _stats_dict(emu_l1_stats),
        "emulator_vs_target_elementwise": elementwise,
        "emulator_vs_target_tail_gate": tail_gate,
        "clamp_counts": clamp_counts,
        "device_routing_gate": {
            "true_weight_table_bases": True,
            "scale_reg_count_nonzero": scale_reg_count > 0,
            "vram_source_no_h_prefetch_v": (not vram_source) or h_prefetch_v_count == 0,
            "topk_contract_passed": topk_contract["passed"],
            "emu_vs_device_exact_rel_rms_under_2pct": emu_target_stats.rel_rms <= 0.02,
            "emu_vs_device_exact_strict_or_tail": emu_target_stats.allclose or tail_gate["passed"],
            "passed": scale_reg_count > 0
            and ((not vram_source) or h_prefetch_v_count == 0)
            and topk_contract["passed"]
            and emu_target_stats.rel_rms <= 0.02
            and (emu_target_stats.allclose or tail_gate["passed"]),
        },
    }
    (build_dir / "device_routing_results.json").write_text(json.dumps(summary, indent=2) + "\n")
    print(json.dumps(summary, indent=2))
    if not summary["device_routing_gate"]["passed"]:
        raise AssertionError(f"device-routing gate failed: {summary['device_routing_gate']}")
    return {"build_dir": str(build_dir), "ran": True, "summary": summary}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    add_hw_args(parser)
    parser.add_argument(
        "--stage",
        choices=(
            "address",
            "four",
            "full_vram",
            "hbm_store_single",
            "hbm_store_full",
            "device_routing_single",
            "device_routing_full",
            "device_routing_vram_single",
            "device_routing_vram_full",
        ),
        default="address",
    )
    parser.add_argument(
        "--reference-path",
        type=Path,
        default=_ATEN_BUILD_DIR / "gpt_oss_real_layer0_tok8_l1_stamp" / "hf_layer0_moe_reference.pt",
    )
    parser.add_argument(
        "--l1-golden-path",
        type=Path,
        default=_ATEN_BUILD_DIR / "gpt_oss_real_layer0_emu_tok8_l1_stamp" / "golden_output.pt",
    )
    parser.add_argument(
        "--build-dir",
        type=Path,
        default=Path(__file__).parent / "build" / "gpt_oss_moe_gather_scatter_address",
    )
    parser.add_argument("--token-index", type=int, default=7)
    parser.add_argument("--store-token-index", type=int, default=2)
    parser.add_argument("--expert-id", type=int, default=9)
    parser.add_argument("--layer-index", type=int, default=0)
    parser.add_argument(
        "--only-experts",
        type=str,
        default=None,
        help="Debug full_vram with a comma-separated subset of routed expert ids.",
    )
    parser.add_argument("--emu-threads", type=int, default=None)
    parser.add_argument("--no-run", action="store_true")
    args = parser.parse_args()

    if args.stage == "address":
        run_address_stage(args)
    elif args.stage == "four":
        run_four_pair_stage(args)
    elif args.stage in ("full_vram", "hbm_store_single", "hbm_store_full"):
        run_full_vram_stage(args)
    elif args.stage in (
        "device_routing_single",
        "device_routing_full",
        "device_routing_vram_single",
        "device_routing_vram_full",
    ):
        run_device_routing_stage(args)
    else:  # pragma: no cover - argparse prevents this today.
        raise ValueError(f"unsupported stage {args.stage}")


if __name__ == "__main__":
    main()
