; PLENA ISA  --  kernel: T_mod2
; generated by tilelang_tvm_compiler (PreIsaIR v2 → MIR path)
; ============================================================
S_LUI_INT gp1, 47232   ; %8=S_LUI_INT(47232)
S_LUI_INT gp2, 1024   ; %11=S_LUI_INT(1024)
S_ADDI_INT gp3, gp0, 2048   ; %12=S_ADDI_INT(%0_gp0,2048)
S_LUI_INT gp4, 100512   ; %46=S_LUI_INT(100512)
S_LUI_INT gp5, 101664   ; %87=S_LUI_INT(101664)
S_LUI_INT gp6, 48384   ; %146=S_LUI_INT(48384)
S_LUI_INT gp7, 256   ; %65=S_LUI_INT(256)
S_LUI_INT gp8, 512   ; %106=S_LUI_INT(512)
S_LUI_INT gp9, 768   ; %126=S_LUI_INT(768)
; for 1_bx in [0, 2) -- hw counter gp10, idx gp11
S_ADDI_INT gp11, gp0, 0
C_LOOP_START gp10, 2
S_SLLI_INT gp12, gp11, 21   ; %27=S_SLLI_INT(%1_bx,21)
; for 2_by_number in [0, 2) -- hw counter gp13, idx gp14
S_ADDI_INT gp14, gp0, 0
C_LOOP_START gp13, 2
; dma_h2v_slice X_hbm -> X_sh  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a0, gp0, gp1   ; %9=C_SET_ADDR_REG(gp0,%8)
C_SET_SCALE_REG gp2   ; C_SET_SCALE_REG(%11)
C_SET_STRIDE_REG gp3   ; C_SET_STRIDE_REG(%12)
S_SLLI_INT gp15, gp14, 10   ; %33=S_SLLI_INT(%2_by_number,10)
; for 14_h2v_inner_4c50 in [0, 4) -- hw counter gp16, idx gp17
S_ADDI_INT gp17, gp0, 0
C_LOOP_START gp16, 4
S_SLLI_INT gp18, gp17, 18   ; %24=S_SLLI_INT(%14_h2v_inner_4c50,18)
S_SLLI_INT gp19, gp17, 19   ; %31=S_SLLI_INT(%14_h2v_inner_4c50,19)
S_ADD_INT gp20, gp12, gp19   ; %32=S_ADD_INT(%27,%31)
S_ADD_INT gp19, gp20, gp15   ; %34=S_ADD_INT(%32,%33)
H_PREFETCH_V gp18, gp19, a0, 1, 0   ; H_PREFETCH_V(%24,%34,%9,1,0)
; idx 14_h2v_inner_4c50 += 1 (gp17)
S_ADDI_INT gp17, gp17, 1
C_LOOP_END gp16
; dma_h2v_slice SCALE1P_hbm -> SCALE1P_sh  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a1, gp0, gp4   ; %47=C_SET_ADDR_REG(gp0,%46)
C_SET_SCALE_REG gp2   ; C_SET_SCALE_REG(%11)
C_SET_STRIDE_REG gp3   ; C_SET_STRIDE_REG(%12)
S_ADD_INT gp16, gp12, gp15   ; %194=S_ADD_INT(%27,%33)
S_ADD_INT gp17, gp12, gp15   ; %195=S_ADD_INT(%27,%33)
; for 52_h2v_inner_4e90 in [0, 4) -- hw counter gp18, idx gp19
S_ADDI_INT gp19, gp0, 0
C_LOOP_START gp18, 4
S_SLLI_INT gp20, gp19, 18   ; %62=S_SLLI_INT(%52_h2v_inner_4e90,18)
S_ADD_INT gp21, gp20, gp7   ; %66=S_ADD_INT(%62,%65)
S_SLLI_INT gp20, gp19, 19   ; %72=S_SLLI_INT(%52_h2v_inner_4e90,19)
S_ADD_INT gp22, gp17, gp20   ; %75=S_ADD_INT(%195,%72)
H_PREFETCH_V gp21, gp22, a1, 1, 0   ; H_PREFETCH_V(%66,%75,%47,1,0)
; idx 52_h2v_inner_4e90 += 1 (gp19)
S_ADDI_INT gp19, gp19, 1
C_LOOP_END gp18
; dma_h2v_slice SHIFT_hbm -> SHIFT_sh  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a2, gp0, gp5   ; %88=C_SET_ADDR_REG(gp0,%87)
C_SET_SCALE_REG gp2   ; C_SET_SCALE_REG(%11)
C_SET_STRIDE_REG gp3   ; C_SET_STRIDE_REG(%12)
; for 93_h2v_inner_50d0 in [0, 4) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 4
S_SLLI_INT gp19, gp18, 18   ; %103=S_SLLI_INT(%93_h2v_inner_50d0,18)
S_ADD_INT gp20, gp19, gp8   ; %107=S_ADD_INT(%103,%106)
S_SLLI_INT gp19, gp18, 19   ; %113=S_SLLI_INT(%93_h2v_inner_50d0,19)
S_ADD_INT gp21, gp19, gp12   ; %114=S_ADD_INT(%113,%27)
S_ADD_INT gp19, gp21, gp15   ; %116=S_ADD_INT(%114,%33)
H_PREFETCH_V gp20, gp19, a2, 1, 0   ; H_PREFETCH_V(%107,%116,%88,1,0)
; idx 93_h2v_inner_50d0 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; for 123_row1 in [0, 1024) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 1024
; v binary v_mul V_MUL_VV dst.parent=TMP_sh starts=[0, row1, 0, 0] extents=[1, 1, 8, 128]
S_SLLI_INT gp19, gp18, 10   ; %124=S_SLLI_INT(%123_row1,10)
S_ADD_INT gp20, gp19, gp9   ; %127=S_ADD_INT(%124,%126)
S_ADD_INT gp21, gp19, gp7   ; %130=S_ADD_INT(%124,%65)
V_MUL_VV gp20, gp21, gp19, 0   ; V_MUL_VV(%127,%130,%124,0)
; v binary v_add V_ADD_VV dst.parent=Y_sh starts=[0, row1, 0, 0] extents=[1, 1, 8, 128]
S_ADD_INT gp21, gp2, gp19   ; %134=S_ADD_INT(%11,%124)
S_ADD_INT gp22, gp8, gp19   ; %140=S_ADD_INT(%106,%124)
V_ADD_VV gp21, gp20, gp22, 0   ; V_ADD_VV(%134,%127,%140,0)
; idx 123_row1 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; dma_v2h_slice Y_sh -> Y_hbm  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a3, gp0, gp6   ; %147=C_SET_ADDR_REG(gp0,%146)
C_SET_SCALE_REG gp2   ; C_SET_SCALE_REG(%11)
C_SET_STRIDE_REG gp3   ; C_SET_STRIDE_REG(%12)
; for 152_v2h_inner_5640 in [0, 4) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 4
S_SLLI_INT gp19, gp18, 18   ; %162=S_SLLI_INT(%152_v2h_inner_5640,18)
S_ADD_INT gp20, gp2, gp19   ; %166=S_ADD_INT(%11,%162)
S_SLLI_INT gp19, gp18, 19   ; %172=S_SLLI_INT(%152_v2h_inner_5640,19)
S_ADD_INT gp21, gp19, gp12   ; %173=S_ADD_INT(%172,%27)
S_ADD_INT gp19, gp21, gp15   ; %175=S_ADD_INT(%173,%33)
H_STORE_V gp20, gp19, a3, 1, 0   ; H_STORE_V(%166,%175,%147,1,0)
; idx 152_v2h_inner_5640 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; idx 2_by_number += 1 (gp14)
S_ADDI_INT gp14, gp14, 1
C_LOOP_END gp13
; idx 1_bx += 1 (gp11)
S_ADDI_INT gp11, gp11, 1
C_LOOP_END gp10
