; PLENA ISA  --  kernel: rope_k
; generated by tilelang_tvm_compiler (PreIsaIR v2 → MIR path)
; ============================================================
S_LUI_INT gp29, 18432   ; %8=S_LUI_INT(18432)
; STBACK %8 gp29 -> slot 0
S_ST_INT gp29, gp0, 0
S_LUI_INT gp1, 2048   ; %11=S_LUI_INT(2048)
S_ADDI_INT gp29, gp0, 2048   ; %12=S_ADDI_INT(%0_gp0,2048)
; STBACK %12 gp29 -> slot 1
S_ST_INT gp29, gp0, 1
S_LUI_INT gp29, 69120   ; %45=S_LUI_INT(69120)
; STBACK %45 gp29 -> slot 2
S_ST_INT gp29, gp0, 2
S_LUI_INT gp2, 256   ; %48=S_LUI_INT(256)
S_ADDI_INT gp29, gp0, 1024   ; %49=S_ADDI_INT(%0_gp0,1024)
; STBACK %49 gp29 -> slot 3
S_ST_INT gp29, gp0, 3
S_LUI_INT gp3, 2560   ; %54=S_LUI_INT(2560)
S_LUI_INT gp29, 64512   ; %60=S_LUI_INT(64512)
; STBACK %60 gp29 -> slot 4
S_ST_INT gp29, gp0, 4
S_LUI_INT gp29, 66816   ; %101=S_LUI_INT(66816)
; STBACK %101 gp29 -> slot 5
S_ST_INT gp29, gp0, 5
S_LUI_INT gp4, 512   ; %146=S_LUI_INT(512)
S_LUI_INT gp29, 23040   ; %227=S_LUI_INT(23040)
; STBACK %227 gp29 -> slot 6
S_ST_INT gp29, gp0, 6
S_LUI_INT gp5, 2816   ; %79=S_LUI_INT(2816)
S_LUI_INT gp6, 3072   ; %120=S_LUI_INT(3072)
S_LUI_INT gp7, 3584   ; %150=S_LUI_INT(3584)
S_LUI_INT gp8, 768   ; %160=S_LUI_INT(768)
S_LUI_INT gp9, 1024   ; %167=S_LUI_INT(1024)
S_LUI_INT gp10, 1280   ; %174=S_LUI_INT(1280)
S_LUI_INT gp11, 1536   ; %181=S_LUI_INT(1536)
S_LUI_INT gp12, 1792   ; %188=S_LUI_INT(1792)
S_LUI_INT gp13, 2304   ; %202=S_LUI_INT(2304)
S_LUI_INT gp14, 3328   ; %217=S_LUI_INT(3328)
; for 1_bx in [0, 2) -- hw counter gp15, idx gp16
S_ADDI_INT gp16, gp0, 0
C_LOOP_START gp15, 2
S_SLLI_INT gp17, gp16, 10   ; %38=S_SLLI_INT(%1_bx,10)
; for 2_by in [0, 4) -- hw counter gp18, idx gp19
S_ADDI_INT gp19, gp0, 0
C_LOOP_START gp18, 4
; dma_h2v_slice XQ_hbm -> X_sh  (grid d=1 s=1 h=1 b=1)
; RELOAD %8 (slot 0) -> gp29
S_LD_INT gp29, gp0, 0
C_SET_ADDR_REG a0, gp0, gp29   ; %9=C_SET_ADDR_REG(gp0,%8)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%11)
; RELOAD %12 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%12)
S_SLLI_INT gp20, gp19, 21   ; %30=S_SLLI_INT(%2_by,21)
; for 14_h2v_inner_96d0 in [0, 4) -- hw counter gp21, idx gp22
S_ADDI_INT gp22, gp0, 0
C_LOOP_START gp21, 4
S_SLLI_INT gp23, gp22, 18   ; %24=S_SLLI_INT(%14_h2v_inner_96d0,18)
S_ADD_INT gp24, gp23, gp3   ; %28=S_ADD_INT(%24,%54)
S_SLLI_INT gp23, gp22, 19   ; %34=S_SLLI_INT(%14_h2v_inner_96d0,19)
S_ADD_INT gp29, gp20, gp23   ; %35=S_ADD_INT(%30,%34)
; STBACK %35 gp29 -> slot 7
S_ST_INT gp29, gp0, 7
; RELOAD %35 (slot 7) -> gp29
S_LD_INT gp29, gp0, 7
S_ADD_INT gp23, gp29, gp17   ; %39=S_ADD_INT(%35,%38)
H_PREFETCH_V gp24, gp23, a0, 1, 0   ; H_PREFETCH_V(%28,%39,%9,1,0)
; idx 14_h2v_inner_96d0 += 1 (gp22)
S_ADDI_INT gp22, gp22, 1
C_LOOP_END gp21
; dma_h2m tile  P_hbm[hbm+0] -> P_sh[mram+0]
; RELOAD %45 (slot 2) -> gp29
S_LD_INT gp29, gp0, 2
C_SET_ADDR_REG a1, gp0, gp29   ; %46=C_SET_ADDR_REG(gp0,%45)
C_SET_SCALE_REG gp2   ; C_SET_SCALE_REG(%48)
; RELOAD %49 (slot 3) -> gp29
S_LD_INT gp29, gp0, 3
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%49)
H_PREFETCH_M gp0, gp0, a1, 1, 0   ; H_PREFETCH_M(%0_gp0,%0_gp0,%46,1,0)
C_SET_SCALE_REG gp2   ; C_SET_SCALE_REG(%48)
; RELOAD %49 (slot 3) -> gp29
S_LD_INT gp29, gp0, 3
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%49)
; btmm_mm compute btmm_mm lhs_packed=vram[10485760] rhs_mram=0 (accumulate into hm_accum; drained by bmm_wo)
M_BTMM gp0, gp0, gp3   ; M_BTMM(gp0,%0_gp0,%54)
; dma_h2v_slice COS_hbm -> COS_sh  (grid d=1 s=1 h=1 b=1)
; RELOAD %60 (slot 4) -> gp29
S_LD_INT gp29, gp0, 4
C_SET_ADDR_REG a2, gp0, gp29   ; %61=C_SET_ADDR_REG(gp0,%60)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%11)
; RELOAD %12 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%12)
S_ADD_INT gp21, gp20, gp17   ; %275=S_ADD_INT(%30,%38)
S_ADD_INT gp22, gp20, gp17   ; %276=S_ADD_INT(%30,%38)
; for 66_h2v_inner_9ac0 in [0, 4) -- hw counter gp23, idx gp24
S_ADDI_INT gp24, gp0, 0
C_LOOP_START gp23, 4
S_SLLI_INT gp25, gp24, 18   ; %76=S_SLLI_INT(%66_h2v_inner_9ac0,18)
S_ADD_INT gp29, gp25, gp5   ; %80=S_ADD_INT(%76,%79)
; STBACK %80 gp29 -> slot 8
S_ST_INT gp29, gp0, 8
S_SLLI_INT gp25, gp24, 19   ; %86=S_SLLI_INT(%66_h2v_inner_9ac0,19)
S_ADD_INT gp29, gp22, gp25   ; %91=S_ADD_INT(%276,%86)
; STBACK %91 gp29 -> slot 9
S_ST_INT gp29, gp0, 9
; RELOAD %80 (slot 8) -> gp29
S_LD_INT gp29, gp0, 8
; RELOAD %91 (slot 9) -> gp30
S_LD_INT gp30, gp0, 9
H_PREFETCH_V gp29, gp30, a2, 1, 0   ; H_PREFETCH_V(%80,%91,%61,1,0)
; idx 66_h2v_inner_9ac0 += 1 (gp24)
S_ADDI_INT gp24, gp24, 1
C_LOOP_END gp23
; dma_h2v_slice SGN_SIN_hbm -> SGN_sh  (grid d=1 s=1 h=1 b=1)
; RELOAD %101 (slot 5) -> gp29
S_LD_INT gp29, gp0, 5
C_SET_ADDR_REG a3, gp0, gp29   ; %102=C_SET_ADDR_REG(gp0,%101)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%11)
; RELOAD %12 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%12)
; for 107_h2v_inner_9d00 in [0, 4) -- hw counter gp22, idx gp23
S_ADDI_INT gp23, gp0, 0
C_LOOP_START gp22, 4
S_SLLI_INT gp24, gp23, 18   ; %117=S_SLLI_INT(%107_h2v_inner_9d00,18)
S_ADD_INT gp25, gp24, gp6   ; %121=S_ADD_INT(%117,%120)
S_SLLI_INT gp24, gp23, 19   ; %127=S_SLLI_INT(%107_h2v_inner_9d00,19)
S_ADD_INT gp29, gp24, gp20   ; %128=S_ADD_INT(%127,%30)
; STBACK %128 gp29 -> slot 10
S_ST_INT gp29, gp0, 10
; RELOAD %128 (slot 10) -> gp29
S_LD_INT gp29, gp0, 10
S_ADD_INT gp24, gp29, gp17   ; %132=S_ADD_INT(%128,%38)
H_PREFETCH_V gp25, gp24, a3, 1, 0   ; H_PREFETCH_V(%121,%132,%102,1,0)
; idx 107_h2v_inner_9d00 += 1 (gp23)
S_ADDI_INT gp23, gp23, 1
C_LOOP_END gp22
; for 137_row1 in [0, 1024) -- hw counter gp22, idx gp23
S_ADDI_INT gp23, gp0, 0
C_LOOP_START gp22, 1024
; v binary v_mul V_MUL_VV dst.parent=__tmp_vec_2 starts=[0, row1, 0, 0] extents=[1, 1, 1, 1024]
S_SLLI_INT gp24, gp23, 10   ; %138=S_SLLI_INT(%137_row1,10)
S_ADD_INT gp25, gp24, gp3   ; %141=S_ADD_INT(%138,%54)
S_ADD_INT gp26, gp24, gp5   ; %144=S_ADD_INT(%138,%79)
V_MUL_VV gp24, gp25, gp26, 0   ; V_MUL_VV(%138,%141,%144,0)
; idx 137_row1 += 1 (gp23)
S_ADDI_INT gp23, gp23, 1
C_LOOP_END gp22
; bmm_wo drain out=vram[2097152] tiles=8
M_BMM_WO gp4, 0   ; M_BMM_WO(%146,0)
; bmm_wo accumulate 8 tiles scratch[2097152] -> dst[14680064] (C_LOOP over 1024 rows)
; for 147_bmm_wo_row_8440 in [0, 1024) -- hw counter gp22, idx gp23
S_ADDI_INT gp23, gp0, 0
C_LOOP_START gp22, 1024
S_SLLI_INT gp24, gp23, 10   ; %148=S_SLLI_INT(%147_bmm_wo_row_8440,10)
S_ADD_INT gp25, gp24, gp7   ; %151=S_ADD_INT(%148,%150)
S_ADD_INT gp26, gp4, gp24   ; %154=S_ADD_INT(%146,%148)
V_ADD_VF gp25, gp26, f0, 0   ; V_ADD_VF(%151,%154,f0,0)
S_ADD_INT gp26, gp24, gp8   ; %161=S_ADD_INT(%148,%160)
V_ADD_VV gp25, gp25, gp26, 0   ; V_ADD_VV(%151,%151,%161,0)
S_ADD_INT gp26, gp24, gp9   ; %168=S_ADD_INT(%148,%167)
V_ADD_VV gp25, gp25, gp26, 0   ; V_ADD_VV(%151,%151,%168,0)
S_ADD_INT gp26, gp24, gp10   ; %175=S_ADD_INT(%148,%174)
V_ADD_VV gp25, gp25, gp26, 0   ; V_ADD_VV(%151,%151,%175,0)
S_ADD_INT gp26, gp24, gp11   ; %182=S_ADD_INT(%148,%181)
V_ADD_VV gp25, gp25, gp26, 0   ; V_ADD_VV(%151,%151,%182,0)
S_ADD_INT gp26, gp24, gp12   ; %189=S_ADD_INT(%148,%188)
V_ADD_VV gp25, gp25, gp26, 0   ; V_ADD_VV(%151,%151,%189,0)
S_ADD_INT gp26, gp1, gp24   ; %196=S_ADD_INT(%11,%148)
V_ADD_VV gp25, gp25, gp26, 0   ; V_ADD_VV(%151,%151,%196,0)
S_ADD_INT gp26, gp24, gp13   ; %203=S_ADD_INT(%148,%202)
V_ADD_VV gp25, gp25, gp26, 0   ; V_ADD_VV(%151,%151,%203,0)
; idx 147_bmm_wo_row_8440 += 1 (gp23)
S_ADDI_INT gp23, gp23, 1
C_LOOP_END gp22
; for 204_row1 in [0, 1024) -- hw counter gp22, idx gp23
S_ADDI_INT gp23, gp0, 0
C_LOOP_START gp22, 1024
; v binary v_mul V_MUL_VV dst.parent=__tmp_vec_3 starts=[0, row1, 0, 0] extents=[1, 1, 1, 1024]
S_SLLI_INT gp24, gp23, 10   ; %205=S_SLLI_INT(%204_row1,10)
S_ADD_INT gp25, gp24, gp2   ; %208=S_ADD_INT(%205,%48)
S_ADD_INT gp26, gp7, gp24   ; %211=S_ADD_INT(%150,%205)
S_ADD_INT gp27, gp6, gp24   ; %214=S_ADD_INT(%120,%205)
V_MUL_VV gp25, gp26, gp27, 0   ; V_MUL_VV(%208,%211,%214,0)
; v binary v_add V_ADD_VV dst.parent=OUT_sh starts=[0, row1, 0, 0] extents=[1, 1, 1, 1024]
S_ADD_INT gp26, gp24, gp14   ; %218=S_ADD_INT(%205,%217)
V_ADD_VV gp26, gp24, gp25, 0   ; V_ADD_VV(%218,%205,%208,0)
; idx 204_row1 += 1 (gp23)
S_ADDI_INT gp23, gp23, 1
C_LOOP_END gp22
; dma_v2h_slice OUT_sh -> Q_OUT_hbm  (grid d=1 s=1 h=1 b=1)
; RELOAD %227 (slot 6) -> gp29
S_LD_INT gp29, gp0, 6
C_SET_ADDR_REG a4, gp0, gp29   ; %228=C_SET_ADDR_REG(gp0,%227)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%11)
; RELOAD %12 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%12)
; for 233_v2h_inner_a750 in [0, 4) -- hw counter gp22, idx gp23
S_ADDI_INT gp23, gp0, 0
C_LOOP_START gp22, 4
S_SLLI_INT gp24, gp23, 18   ; %243=S_SLLI_INT(%233_v2h_inner_a750,18)
S_ADD_INT gp25, gp14, gp24   ; %247=S_ADD_INT(%217,%243)
S_SLLI_INT gp24, gp23, 19   ; %253=S_SLLI_INT(%233_v2h_inner_a750,19)
S_ADD_INT gp26, gp24, gp20   ; %254=S_ADD_INT(%253,%30)
S_ADD_INT gp24, gp26, gp17   ; %258=S_ADD_INT(%254,%38)
H_STORE_V gp25, gp24, a4, 1, 0   ; H_STORE_V(%247,%258,%228,1,0)
; idx 233_v2h_inner_a750 += 1 (gp23)
S_ADDI_INT gp23, gp23, 1
C_LOOP_END gp22
; idx 2_by += 1 (gp19)
S_ADDI_INT gp19, gp19, 1
C_LOOP_END gp18
; idx 1_bx += 1 (gp16)
S_ADDI_INT gp16, gp16, 1
C_LOOP_END gp15
