; PLENA ISA  --  kernel: T_linq
; generated by tilelang_tvm_compiler (PreIsaIR v2 → MIR path)
; ============================================================
S_LUI_INT gp29, 74016   ; %64=S_LUI_INT(74016)
; STBACK %64 gp29 -> slot 0
S_ST_INT gp29, gp0, 0
S_LUI_INT gp1, 1024   ; %67=S_LUI_INT(1024)
S_ADDI_INT gp29, gp0, 2048   ; %68=S_ADDI_INT(%0_gp0,2048)
; STBACK %68 gp29 -> slot 1
S_ST_INT gp29, gp0, 1
S_LUI_INT gp29, 14976   ; %175=S_LUI_INT(14976)
; STBACK %175 gp29 -> slot 2
S_ST_INT gp29, gp0, 2
S_LUI_INT gp29, 13824   ; %9=S_LUI_INT(13824)
; STBACK %9 gp29 -> slot 3
S_ST_INT gp29, gp0, 3
S_LUI_INT gp29, 72864   ; %46=S_LUI_INT(72864)
; STBACK %46 gp29 -> slot 4
S_ST_INT gp29, gp0, 4
S_LUI_INT gp2, 256   ; %55=S_LUI_INT(256)
S_ADDI_INT gp29, gp0, 1024   ; %56=S_ADDI_INT(%0_gp0,1024)
; STBACK %56 gp29 -> slot 5
S_ST_INT gp29, gp0, 5
S_LUI_INT gp3, 2048   ; %58=S_LUI_INT(2048)
S_LUI_INT gp4, 2304   ; %83=S_LUI_INT(2304)
S_LUI_INT gp5, 2816   ; %103=S_LUI_INT(2816)
S_LUI_INT gp6, 512   ; %117=S_LUI_INT(512)
S_LUI_INT gp7, 768   ; %124=S_LUI_INT(768)
S_LUI_INT gp8, 1280   ; %138=S_LUI_INT(1280)
S_LUI_INT gp9, 1536   ; %145=S_LUI_INT(1536)
S_LUI_INT gp10, 1792   ; %152=S_LUI_INT(1792)
S_LUI_INT gp11, 2560   ; %165=S_LUI_INT(2560)
; for 1_bx in [0, 2) -- hw counter gp12, idx gp13
S_ADDI_INT gp13, gp0, 0
C_LOOP_START gp12, 2
S_SLLI_INT gp29, gp13, 21   ; %51=S_SLLI_INT(%1_bx,21)
; STBACK %51 gp29 -> slot 6
S_ST_INT gp29, gp0, 6
S_SLLI_INT gp14, gp13, 10   ; %94=S_SLLI_INT(%1_bx,10)
; for 2_by in [0, 2) -- hw counter gp15, idx gp16
S_ADDI_INT gp16, gp0, 0
C_LOOP_START gp15, 2
S_SLLI_INT gp17, gp16, 21   ; %31=S_SLLI_INT(%2_by,21)
; for 3_k_block in [0, 2) -- hw counter gp18, idx gp19
S_ADDI_INT gp19, gp0, 0
C_LOOP_START gp18, 2
; dma_h2v_slice A_hbm -> A_sh  (grid d=1 s=1 h=1 b=1)
; RELOAD %9 (slot 3) -> gp29
S_LD_INT gp29, gp0, 3
C_SET_ADDR_REG a0, gp0, gp29   ; %10=C_SET_ADDR_REG(gp0,%9)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%67)
; RELOAD %68 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%68)
S_SLLI_INT gp20, gp19, 10   ; %39=S_SLLI_INT(%3_k_block,10)
; for 15_h2v_inner_c80 in [0, 4) -- hw counter gp21, idx gp22
S_ADDI_INT gp22, gp0, 0
C_LOOP_START gp21, 4
S_SLLI_INT gp23, gp22, 18   ; %25=S_SLLI_INT(%15_h2v_inner_c80,18)
S_ADD_INT gp24, gp23, gp3   ; %29=S_ADD_INT(%25,%58)
S_SLLI_INT gp23, gp22, 19   ; %35=S_SLLI_INT(%15_h2v_inner_c80,19)
S_ADD_INT gp25, gp17, gp23   ; %36=S_ADD_INT(%31,%35)
S_ADD_INT gp23, gp25, gp20   ; %40=S_ADD_INT(%36,%39)
H_PREFETCH_V gp24, gp23, a0, 1, 0   ; H_PREFETCH_V(%29,%40,%10,1,0)
; idx 15_h2v_inner_c80 += 1 (gp22)
S_ADDI_INT gp22, gp22, 1
C_LOOP_END gp21
; dma_h2m_slice B_hbm -> B_sh
; RELOAD %46 (slot 4) -> gp29
S_LD_INT gp29, gp0, 4
C_SET_ADDR_REG a1, gp0, gp29   ; %47=C_SET_ADDR_REG(gp0,%46)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%67)
; RELOAD %68 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%68)
; RELOAD %51 (slot 6) -> gp29
S_LD_INT gp29, gp0, 6
S_ADD_INT gp21, gp20, gp29   ; %53=S_ADD_INT(%39,%51)
H_PREFETCH_M gp0, gp21, a1, 1, 0   ; H_PREFETCH_M(%0_gp0,%53,%47,1,0)
C_SET_SCALE_REG gp2   ; C_SET_SCALE_REG(%55)
; RELOAD %56 (slot 5) -> gp29
S_LD_INT gp29, gp0, 5
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%56)
; btmm_mm compute btmm_mm lhs_packed=vram[8388608] rhs_mram=0 (accumulate into hm_accum; drained by bmm_wo)
M_BTMM gp0, gp0, gp3   ; M_BTMM(gp0,%0_gp0,%58)
; idx 3_k_block += 1 (gp19)
S_ADDI_INT gp19, gp19, 1
C_LOOP_END gp18
; dma_h2v_slice BIAS_hbm -> BIAS_sh  (grid d=1 s=1 h=1 b=1)
; RELOAD %64 (slot 0) -> gp29
S_LD_INT gp29, gp0, 0
C_SET_ADDR_REG a2, gp0, gp29   ; %65=C_SET_ADDR_REG(gp0,%64)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%67)
; RELOAD %68 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%68)
; for 70_h2v_inner_1040 in [0, 4) -- hw counter gp18, idx gp19
S_ADDI_INT gp19, gp0, 0
C_LOOP_START gp18, 4
S_SLLI_INT gp20, gp19, 18   ; %80=S_SLLI_INT(%70_h2v_inner_1040,18)
S_ADD_INT gp21, gp20, gp4   ; %84=S_ADD_INT(%80,%83)
S_SLLI_INT gp20, gp19, 19   ; %90=S_SLLI_INT(%70_h2v_inner_1040,19)
S_ADD_INT gp22, gp17, gp20   ; %91=S_ADD_INT(%31,%90)
S_ADD_INT gp20, gp22, gp14   ; %95=S_ADD_INT(%91,%94)
H_PREFETCH_V gp21, gp20, a2, 1, 0   ; H_PREFETCH_V(%84,%95,%65,1,0)
; idx 70_h2v_inner_1040 += 1 (gp19)
S_ADDI_INT gp19, gp19, 1
C_LOOP_END gp18
; bmm_wo drain out=vram[0] tiles=8
M_BMM_WO gp0, 0   ; M_BMM_WO(%0_gp0,0)
; bmm_wo accumulate 8 tiles scratch[0] -> dst[11534336] (C_LOOP over 1024 rows)
; for 100_bmm_wo_row_f680 in [0, 1024) -- hw counter gp18, idx gp19
S_ADDI_INT gp19, gp0, 0
C_LOOP_START gp18, 1024
S_SLLI_INT gp20, gp19, 10   ; %101=S_SLLI_INT(%100_bmm_wo_row_f680,10)
S_ADD_INT gp21, gp20, gp5   ; %104=S_ADD_INT(%101,%103)
V_ADD_VF gp21, gp20, f0, 0   ; V_ADD_VF(%104,%101,f0,0)
S_ADD_INT gp22, gp20, gp2   ; %111=S_ADD_INT(%101,%55)
V_ADD_VV gp21, gp21, gp22, 0   ; V_ADD_VV(%104,%104,%111,0)
S_ADD_INT gp22, gp20, gp6   ; %118=S_ADD_INT(%101,%117)
V_ADD_VV gp21, gp21, gp22, 0   ; V_ADD_VV(%104,%104,%118,0)
S_ADD_INT gp22, gp20, gp7   ; %125=S_ADD_INT(%101,%124)
V_ADD_VV gp21, gp21, gp22, 0   ; V_ADD_VV(%104,%104,%125,0)
S_ADD_INT gp22, gp20, gp1   ; %132=S_ADD_INT(%101,%67)
V_ADD_VV gp21, gp21, gp22, 0   ; V_ADD_VV(%104,%104,%132,0)
S_ADD_INT gp22, gp20, gp8   ; %139=S_ADD_INT(%101,%138)
V_ADD_VV gp21, gp21, gp22, 0   ; V_ADD_VV(%104,%104,%139,0)
S_ADD_INT gp22, gp20, gp9   ; %146=S_ADD_INT(%101,%145)
V_ADD_VV gp21, gp21, gp22, 0   ; V_ADD_VV(%104,%104,%146,0)
S_ADD_INT gp22, gp20, gp10   ; %153=S_ADD_INT(%101,%152)
V_ADD_VV gp21, gp21, gp22, 0   ; V_ADD_VV(%104,%104,%153,0)
; idx 100_bmm_wo_row_f680 += 1 (gp19)
S_ADDI_INT gp19, gp19, 1
C_LOOP_END gp18
; for 154_row1 in [0, 1024) -- hw counter gp18, idx gp19
S_ADDI_INT gp19, gp0, 0
C_LOOP_START gp18, 1024
; v binary v_add V_ADD_VV dst.parent=C_loc starts=[0, row1, 0, 0] extents=[1, 1, 1, 1024]
S_SLLI_INT gp20, gp19, 10   ; %155=S_SLLI_INT(%154_row1,10)
S_ADD_INT gp21, gp5, gp20   ; %158=S_ADD_INT(%103,%155)
S_ADD_INT gp22, gp20, gp4   ; %161=S_ADD_INT(%155,%83)
V_ADD_VV gp21, gp21, gp22, 0   ; V_ADD_VV(%158,%158,%161,0)
; idx 154_row1 += 1 (gp19)
S_ADDI_INT gp19, gp19, 1
C_LOOP_END gp18
; copy_v_to_v src.parent=C_loc -> dst.parent=C_sh extents=[1, 1024, 1, 1024]
; for 162_copy_row_f920 in [0, 1024) -- hw counter gp18, idx gp19
S_ADDI_INT gp19, gp0, 0
C_LOOP_START gp18, 1024
S_SLLI_INT gp20, gp19, 10   ; %163=S_SLLI_INT(%162_copy_row_f920,10)
S_ADD_INT gp21, gp20, gp11   ; %166=S_ADD_INT(%163,%165)
S_ADD_INT gp22, gp5, gp20   ; %169=S_ADD_INT(%103,%163)
V_ADD_VF gp21, gp22, f0, 0   ; V_ADD_VF(%166,%169,f0,0)
; idx 162_copy_row_f920 += 1 (gp19)
S_ADDI_INT gp19, gp19, 1
C_LOOP_END gp18
; dma_v2h_slice C_sh -> C_hbm  (grid d=1 s=1 h=1 b=1)
; RELOAD %175 (slot 2) -> gp29
S_LD_INT gp29, gp0, 2
C_SET_ADDR_REG a3, gp0, gp29   ; %176=C_SET_ADDR_REG(gp0,%175)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%67)
; RELOAD %68 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%68)
; for 181_v2h_inner_1730 in [0, 4) -- hw counter gp18, idx gp19
S_ADDI_INT gp19, gp0, 0
C_LOOP_START gp18, 4
S_SLLI_INT gp20, gp19, 18   ; %191=S_SLLI_INT(%181_v2h_inner_1730,18)
S_ADD_INT gp21, gp11, gp20   ; %195=S_ADD_INT(%165,%191)
S_SLLI_INT gp20, gp19, 19   ; %201=S_SLLI_INT(%181_v2h_inner_1730,19)
S_ADD_INT gp22, gp20, gp17   ; %202=S_ADD_INT(%201,%31)
S_ADD_INT gp20, gp22, gp14   ; %206=S_ADD_INT(%202,%94)
H_STORE_V gp21, gp20, a3, 1, 0   ; H_STORE_V(%195,%206,%176,1,0)
; idx 181_v2h_inner_1730 += 1 (gp19)
S_ADDI_INT gp19, gp19, 1
C_LOOP_END gp18
; idx 2_by += 1 (gp16)
S_ADDI_INT gp16, gp16, 1
C_LOOP_END gp15
; idx 1_bx += 1 (gp13)
S_ADDI_INT gp13, gp13, 1
C_LOOP_END gp12
