; PLENA ISA  --  kernel: layernorm
; generated by tilelang_tvm_compiler (PreIsaIR v2 → MIR path)
; ============================================================
S_LUI_INT gp1, 2048   ; %8=S_LUI_INT(2048)
S_ADDI_INT gp29, gp0, 2048   ; %9=S_ADDI_INT(%0_gp0,2048)
; STBACK %9 gp29 -> slot 0
S_ST_INT gp29, gp0, 0
S_LUI_INT gp29, 39168   ; %41=S_LUI_INT(39168)
; STBACK %41 gp29 -> slot 1
S_ST_INT gp29, gp0, 1
S_LUI_INT gp2, 512   ; %60=S_LUI_INT(512)
S_LUI_INT gp29, 41472   ; %80=S_LUI_INT(41472)
; STBACK %80 gp29 -> slot 2
S_ST_INT gp29, gp0, 2
S_LUI_INT gp3, 1024   ; %99=S_LUI_INT(1024)
S_LUI_INT gp4, 2560   ; %122=S_LUI_INT(2560)
S_LUI_INT gp5, 3072   ; %130=S_LUI_INT(3072)
S_ADDI_INT gp6, gp0, 7200   ; %147=S_ADDI_INT(%0_gp0,7200)
S_LUI_INT gp7, 3584   ; %160=S_LUI_INT(3584)
S_LUI_INT gp8, 3840   ; %167=S_LUI_INT(3840)
S_LUI_INT gp9, 2304   ; %170=S_LUI_INT(2304)
S_ADDI_INT gp10, gp0, 7201   ; %187=S_ADDI_INT(%0_gp0,7201)
S_LUI_INT gp11, 4096   ; %196=S_LUI_INT(4096)
S_LUI_INT gp12, 4352   ; %206=S_LUI_INT(4352)
S_LUI_INT gp13, 2816   ; %212=S_LUI_INT(2816)
S_LUI_INT gp14, 3328   ; %236=S_LUI_INT(3328)
S_LUI_INT gp15, 1536   ; %241=S_LUI_INT(1536)
; for 1_bx in [0, 4) -- hw counter gp16, idx gp17
S_ADDI_INT gp17, gp0, 0
C_LOOP_START gp16, 4
; dma_h2v_slice X_hbm -> X_sh  (grid d=2 s=1 h=1 b=1)
S_SLLI_INT gp18, gp17, 21   ; %24=S_SLLI_INT(%1_bx,21)
; for 2_sl_d_f470_f830 in [0, 2) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2
C_SET_ADDR_REG a0, gp0, gp0   ; %6=C_SET_ADDR_REG(gp0,%0_gp0)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%8)
; RELOAD %9 (slot 0) -> gp29
S_LD_INT gp29, gp0, 0
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%9)
S_SLLI_INT gp21, gp20, 20   ; %12=S_SLLI_INT(%2_sl_d_f470_f830,20)
S_SLLI_INT gp22, gp20, 10   ; %32=S_SLLI_INT(%2_sl_d_f470_f830,10)
; for 11_h2v_inner_b90 in [0, 4) -- hw counter gp23, idx gp24
S_ADDI_INT gp24, gp0, 0
C_LOOP_START gp23, 4
S_SLLI_INT gp25, gp24, 18   ; %21=S_SLLI_INT(%11_h2v_inner_b90,18)
S_ADD_INT gp29, gp21, gp25   ; %22=S_ADD_INT(%12,%21)
; STBACK %22 gp29 -> slot 3
S_ST_INT gp29, gp0, 3
S_SLLI_INT gp25, gp24, 19   ; %28=S_SLLI_INT(%11_h2v_inner_b90,19)
S_ADD_INT gp29, gp18, gp25   ; %29=S_ADD_INT(%24,%28)
; STBACK %29 gp29 -> slot 4
S_ST_INT gp29, gp0, 4
; RELOAD %29 (slot 4) -> gp29
S_LD_INT gp29, gp0, 4
S_ADD_INT gp25, gp29, gp22   ; %33=S_ADD_INT(%29,%32)
; RELOAD %22 (slot 3) -> gp29
S_LD_INT gp29, gp0, 3
H_PREFETCH_V gp29, gp25, a0, 1, 0   ; H_PREFETCH_V(%22,%33,%6,1,0)
; idx 11_h2v_inner_b90 += 1 (gp24)
S_ADDI_INT gp24, gp24, 1
C_LOOP_END gp23
; idx 2_sl_d_f470_f830 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; dma_h2v_slice SCALE_hbm -> SCALE_sh  (grid d=2 s=1 h=1 b=1)
; for 36_sl_d_f6e0_ff80 in [0, 2) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2
; RELOAD %41 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_ADDR_REG a1, gp0, gp29   ; %42=C_SET_ADDR_REG(gp0,%41)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%8)
; RELOAD %9 (slot 0) -> gp29
S_LD_INT gp29, gp0, 0
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%9)
S_SLLI_INT gp21, gp20, 20   ; %48=S_SLLI_INT(%36_sl_d_f6e0_ff80,20)
S_SLLI_INT gp22, gp20, 10   ; %71=S_SLLI_INT(%36_sl_d_f6e0_ff80,10)
; for 47_h2v_inner_dd0 in [0, 4) -- hw counter gp23, idx gp24
S_ADDI_INT gp24, gp0, 0
C_LOOP_START gp23, 4
S_SLLI_INT gp25, gp24, 18   ; %57=S_SLLI_INT(%47_h2v_inner_dd0,18)
S_ADD_INT gp29, gp21, gp25   ; %58=S_ADD_INT(%48,%57)
; STBACK %58 gp29 -> slot 5
S_ST_INT gp29, gp0, 5
; RELOAD %58 (slot 5) -> gp29
S_LD_INT gp29, gp0, 5
S_ADD_INT gp25, gp29, gp2   ; %61=S_ADD_INT(%58,%60)
S_SLLI_INT gp29, gp24, 19   ; %67=S_SLLI_INT(%47_h2v_inner_dd0,19)
; STBACK %67 gp29 -> slot 6
S_ST_INT gp29, gp0, 6
; RELOAD %67 (slot 6) -> gp29
S_LD_INT gp29, gp0, 6
S_ADD_INT gp30, gp18, gp29   ; %68=S_ADD_INT(%24,%67)
; STBACK %68 gp30 -> slot 7
S_ST_INT gp30, gp0, 7
; RELOAD %68 (slot 7) -> gp29
S_LD_INT gp29, gp0, 7
S_ADD_INT gp30, gp29, gp22   ; %72=S_ADD_INT(%68,%71)
; STBACK %72 gp30 -> slot 8
S_ST_INT gp30, gp0, 8
; RELOAD %72 (slot 8) -> gp29
S_LD_INT gp29, gp0, 8
H_PREFETCH_V gp25, gp29, a1, 1, 0   ; H_PREFETCH_V(%61,%72,%42,1,0)
; idx 47_h2v_inner_dd0 += 1 (gp24)
S_ADDI_INT gp24, gp24, 1
C_LOOP_END gp23
; idx 36_sl_d_f6e0_ff80 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; dma_h2v_slice BIAS_hbm -> BIAS_sh  (grid d=2 s=1 h=1 b=1)
; for 75_sl_d_dee0_a030 in [0, 2) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2
; RELOAD %80 (slot 2) -> gp29
S_LD_INT gp29, gp0, 2
C_SET_ADDR_REG a2, gp0, gp29   ; %81=C_SET_ADDR_REG(gp0,%80)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%8)
; RELOAD %9 (slot 0) -> gp29
S_LD_INT gp29, gp0, 0
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%9)
S_SLLI_INT gp21, gp20, 20   ; %87=S_SLLI_INT(%75_sl_d_dee0_a030,20)
S_SLLI_INT gp22, gp20, 10   ; %110=S_SLLI_INT(%75_sl_d_dee0_a030,10)
; for 86_h2v_inner_1010 in [0, 4) -- hw counter gp23, idx gp24
S_ADDI_INT gp24, gp0, 0
C_LOOP_START gp23, 4
S_SLLI_INT gp25, gp24, 18   ; %96=S_SLLI_INT(%86_h2v_inner_1010,18)
S_ADD_INT gp29, gp21, gp25   ; %97=S_ADD_INT(%87,%96)
; STBACK %97 gp29 -> slot 9
S_ST_INT gp29, gp0, 9
; RELOAD %97 (slot 9) -> gp29
S_LD_INT gp29, gp0, 9
S_ADD_INT gp25, gp29, gp3   ; %100=S_ADD_INT(%97,%99)
S_SLLI_INT gp29, gp24, 19   ; %106=S_SLLI_INT(%86_h2v_inner_1010,19)
; STBACK %106 gp29 -> slot 10
S_ST_INT gp29, gp0, 10
; RELOAD %106 (slot 10) -> gp29
S_LD_INT gp29, gp0, 10
S_ADD_INT gp30, gp29, gp22   ; %285=S_ADD_INT(%106,%110)
; STBACK %285 gp30 -> slot 11
S_ST_INT gp30, gp0, 11
; RELOAD %285 (slot 11) -> gp29
S_LD_INT gp29, gp0, 11
S_ADD_INT gp30, gp29, gp18   ; %111=S_ADD_INT(%285,%24)
; STBACK %111 gp30 -> slot 12
S_ST_INT gp30, gp0, 12
; RELOAD %111 (slot 12) -> gp29
S_LD_INT gp29, gp0, 12
H_PREFETCH_V gp25, gp29, a2, 1, 0   ; H_PREFETCH_V(%100,%111,%81,1,0)
; idx 86_h2v_inner_1010 += 1 (gp24)
S_ADDI_INT gp24, gp24, 1
C_LOOP_END gp23
; idx 75_sl_d_dee0_a030 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; copy_v_to_v src.parent=X_sh -> dst.parent=X_loc extents=[1, 1024, 1, 2048]
; for 114_copy_row_a540 in [0, 2048) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2048
S_SLLI_INT gp21, gp20, 10   ; %115=S_SLLI_INT(%114_copy_row_a540,10)
S_ADD_INT gp22, gp21, gp1   ; %118=S_ADD_INT(%115,%8)
V_ADD_VF gp22, gp21, f0, 0   ; V_ADD_VF(%118,%115,f0,0)
; idx 114_copy_row_a540 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; copy_v_to_v src.parent=SCALE_sh -> dst.parent=SC_loc extents=[1, 1024, 1, 2048]
; for 119_copy_row_a5d0 in [0, 2048) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2048
S_SLLI_INT gp21, gp20, 10   ; %120=S_SLLI_INT(%119_copy_row_a5d0,10)
S_ADD_INT gp22, gp21, gp4   ; %123=S_ADD_INT(%120,%122)
S_ADD_INT gp23, gp21, gp2   ; %126=S_ADD_INT(%120,%60)
V_ADD_VF gp22, gp23, f0, 0   ; V_ADD_VF(%123,%126,f0,0)
; idx 119_copy_row_a5d0 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; copy_v_to_v src.parent=BIAS_sh -> dst.parent=BI_loc extents=[1, 1024, 1, 2048]
; for 127_copy_row_e7b0 in [0, 2048) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2048
S_SLLI_INT gp21, gp20, 10   ; %128=S_SLLI_INT(%127_copy_row_e7b0,10)
S_ADD_INT gp22, gp21, gp5   ; %131=S_ADD_INT(%128,%130)
S_ADD_INT gp23, gp21, gp3   ; %134=S_ADD_INT(%128,%99)
V_ADD_VF gp22, gp23, f0, 0   ; V_ADD_VF(%131,%134,f0,0)
; idx 127_copy_row_e7b0 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 135_row in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; fp scalar task fp_zero_at op=zero
S_ADDI_INT gp21, gp20, 32   ; %136=S_ADDI_INT(%135_row,32)
S_ST_FP f0, gp21, 0   ; S_ST_FP(f0,%136,0)
; row scalar task row_reduce_sum_at op=reduce_sum src.parent=X_loc starts=[0, row, 0, 0]
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%136,0)
S_SLLI_INT gp22, gp20, 10   ; %140=S_SLLI_INT(%135_row,10)
; for 138_d_tile_b1d0 in [0, 2) -- hw counter gp23, idx gp24
S_ADDI_INT gp24, gp0, 0
C_LOOP_START gp23, 2
S_SLLI_INT gp25, gp24, 20   ; %139=S_SLLI_INT(%138_d_tile_b1d0,20)
S_ADD_INT gp26, gp25, gp22   ; %141=S_ADD_INT(%139,%140)
S_ADD_INT gp25, gp26, gp1   ; %144=S_ADD_INT(%141,%8)
V_RED_SUM f1, gp25, 0   ; V_RED_SUM(f1,%144,0)
; idx 138_d_tile_b1d0 += 1 (gp24)
S_ADDI_INT gp24, gp24, 1
C_LOOP_END gp23
S_ST_FP f1, gp21, 0   ; S_ST_FP(f1,%136,0)
; fp scalar task fp_mul_at op=mul
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%136,0)
S_LD_FP f2, gp6, 0   ; S_LD_FP(f2,%147,0)
S_MUL_FP f1, f1, f2   ; S_MUL_FP(f1,f1,f2)
S_ADDI_INT gp21, gp20, 1056   ; %148=S_ADDI_INT(%135_row,1056)
S_ST_FP f1, gp21, 0   ; S_ST_FP(f1,%148,0)
; row scalar task row_sub_fp op=sub src.parent=X_loc starts=[0, row, 0, 0]
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%148,0)
; for 150_d_tile_b230 in [0, 2) -- hw counter gp21, idx gp23
S_ADDI_INT gp23, gp0, 0
C_LOOP_START gp21, 2
S_SLLI_INT gp24, gp23, 20   ; %151=S_SLLI_INT(%150_d_tile_b230,20)
S_ADD_INT gp25, gp22, gp24   ; %153=S_ADD_INT(%140,%151)
S_ADD_INT gp24, gp25, gp1   ; %156=S_ADD_INT(%153,%8)
V_SUB_VF gp24, gp24, f1, 0, 0   ; V_SUB_VF(%156,%156,f1,0,0)
; idx 150_d_tile_b230 += 1 (gp23)
S_ADDI_INT gp23, gp23, 1
C_LOOP_END gp21
; idx 135_row += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 157_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; v binary v_mul V_MUL_VV dst.parent=SQ_loc starts=[0, row1, 0, 0] extents=[1, 1, 1, 2048]
S_SLLI_INT gp21, gp20, 10   ; %158=S_SLLI_INT(%157_row1,10)
S_ADD_INT gp22, gp21, gp7   ; %161=S_ADD_INT(%158,%160)
S_ADD_INT gp23, gp21, gp1   ; %164=S_ADD_INT(%158,%8)
V_MUL_VV gp22, gp23, gp23, 0   ; V_MUL_VV(%161,%164,%164,0)
S_ADD_INT gp22, gp21, gp8   ; %168=S_ADD_INT(%158,%167)
S_ADD_INT gp23, gp21, gp9   ; %171=S_ADD_INT(%158,%170)
V_MUL_VV gp22, gp23, gp23, 0   ; V_MUL_VV(%168,%171,%171,0)
; idx 157_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 172_row in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; fp scalar task fp_zero_at op=zero
S_ADDI_INT gp21, gp20, 2080   ; %173=S_ADDI_INT(%172_row,2080)
S_ST_FP f0, gp21, 0   ; S_ST_FP(f0,%173,0)
; row scalar task row_reduce_sum_at op=reduce_sum src.parent=SQ_loc starts=[0, row, 0, 0]
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%173,0)
S_SLLI_INT gp22, gp20, 10   ; %177=S_SLLI_INT(%172_row,10)
; for 175_d_tile_b200 in [0, 2) -- hw counter gp23, idx gp24
S_ADDI_INT gp24, gp0, 0
C_LOOP_START gp23, 2
S_SLLI_INT gp25, gp24, 20   ; %176=S_SLLI_INT(%175_d_tile_b200,20)
S_ADD_INT gp26, gp7, gp25   ; %286=S_ADD_INT(%160,%176)
S_ADD_INT gp25, gp26, gp22   ; %181=S_ADD_INT(%286,%177)
V_RED_SUM f1, gp25, 0   ; V_RED_SUM(f1,%181,0)
; idx 175_d_tile_b200 += 1 (gp24)
S_ADDI_INT gp24, gp24, 1
C_LOOP_END gp23
S_ST_FP f1, gp21, 0   ; S_ST_FP(f1,%173,0)
; fp scalar task fp_mul_at op=mul
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%173,0)
S_LD_FP f2, gp6, 0   ; S_LD_FP(f2,%147,0)
S_MUL_FP f1, f1, f2   ; S_MUL_FP(f1,f1,f2)
S_ADDI_INT gp21, gp20, 3104   ; %185=S_ADDI_INT(%172_row,3104)
S_ST_FP f1, gp21, 0   ; S_ST_FP(f1,%185,0)
; fp scalar task fp_add_at op=add
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%185,0)
S_LD_FP f2, gp10, 0   ; S_LD_FP(f2,%187,0)
S_ADD_FP f1, f1, f2   ; S_ADD_FP(f1,f1,f2)
S_ADDI_INT gp21, gp20, 4128   ; %188=S_ADDI_INT(%172_row,4128)
S_ST_FP f1, gp21, 0   ; S_ST_FP(f1,%188,0)
; fp scalar task fp_sqrt_at op=sqrt
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%188,0)
S_SQRT_FP f1, f1   ; S_SQRT_FP(f1,f1)
S_ADDI_INT gp21, gp20, 5152   ; %190=S_ADDI_INT(%172_row,5152)
S_ST_FP f1, gp21, 0   ; S_ST_FP(f1,%190,0)
; fp scalar task fp_reci_at op=reci
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%190,0)
S_RECI_FP f1, f1   ; S_RECI_FP(f1,f1)
S_ADDI_INT gp21, gp20, 6176   ; %192=S_ADDI_INT(%172_row,6176)
S_ST_FP f1, gp21, 0   ; S_ST_FP(f1,%192,0)
; idx 172_row += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 193_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; v binary v_mul V_MUL_VV dst.parent=Y_loc starts=[0, row1, 0, 0] extents=[1, 1, 1, 2048]
S_SLLI_INT gp21, gp20, 10   ; %194=S_SLLI_INT(%193_row1,10)
S_ADD_INT gp22, gp21, gp11   ; %197=S_ADD_INT(%194,%196)
S_ADD_INT gp23, gp21, gp1   ; %200=S_ADD_INT(%194,%8)
S_ADD_INT gp24, gp4, gp21   ; %203=S_ADD_INT(%122,%194)
V_MUL_VV gp22, gp23, gp24, 0   ; V_MUL_VV(%197,%200,%203,0)
S_ADD_INT gp22, gp21, gp12   ; %207=S_ADD_INT(%194,%206)
S_ADD_INT gp23, gp9, gp21   ; %210=S_ADD_INT(%170,%194)
S_ADD_INT gp24, gp21, gp13   ; %213=S_ADD_INT(%194,%212)
V_MUL_VV gp22, gp23, gp24, 0   ; V_MUL_VV(%207,%210,%213,0)
; idx 193_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 214_row in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; row scalar task row_mul_fp op=mul src.parent=Y_loc starts=[0, row, 0, 0]
S_ADDI_INT gp21, gp20, 6176   ; %215=S_ADDI_INT(%214_row,6176)
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%215,0)
S_SLLI_INT gp21, gp20, 10   ; %218=S_SLLI_INT(%214_row,10)
; for 216_d_tile_ac30 in [0, 2) -- hw counter gp22, idx gp23
S_ADDI_INT gp23, gp0, 0
C_LOOP_START gp22, 2
S_SLLI_INT gp24, gp23, 20   ; %217=S_SLLI_INT(%216_d_tile_ac30,20)
S_ADD_INT gp25, gp11, gp24   ; %288=S_ADD_INT(%196,%217)
S_ADD_INT gp24, gp25, gp21   ; %222=S_ADD_INT(%288,%218)
V_MUL_VF gp24, gp24, f1, 0   ; V_MUL_VF(%222,%222,f1,0)
; idx 216_d_tile_ac30 += 1 (gp23)
S_ADDI_INT gp23, gp23, 1
C_LOOP_END gp22
; idx 214_row += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 223_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; v binary v_add V_ADD_VV dst.parent=Y_loc starts=[0, row1, 0, 0] extents=[1, 1, 1, 2048]
S_SLLI_INT gp21, gp20, 10   ; %224=S_SLLI_INT(%223_row1,10)
S_ADD_INT gp22, gp11, gp21   ; %227=S_ADD_INT(%196,%224)
S_ADD_INT gp23, gp5, gp21   ; %230=S_ADD_INT(%130,%224)
V_ADD_VV gp22, gp22, gp23, 0   ; V_ADD_VV(%227,%227,%230,0)
S_ADD_INT gp22, gp12, gp21   ; %234=S_ADD_INT(%206,%224)
S_ADD_INT gp23, gp21, gp14   ; %237=S_ADD_INT(%224,%236)
V_ADD_VV gp22, gp22, gp23, 0   ; V_ADD_VV(%234,%234,%237,0)
; idx 223_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; copy_v_to_v src.parent=Y_loc -> dst.parent=Y_sh extents=[1, 1024, 1, 2048]
; for 238_copy_row_ae10 in [0, 2048) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2048
S_SLLI_INT gp21, gp20, 10   ; %239=S_SLLI_INT(%238_copy_row_ae10,10)
S_ADD_INT gp22, gp21, gp15   ; %242=S_ADD_INT(%239,%241)
S_ADD_INT gp23, gp11, gp21   ; %245=S_ADD_INT(%196,%239)
V_ADD_VF gp22, gp23, f0, 0   ; V_ADD_VF(%242,%245,f0,0)
; idx 238_copy_row_ae10 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; dma_v2h_slice Y_sh -> Y_hbm  (grid d=2 s=1 h=1 b=1)
; for 246_sl_d_ec00_9fa0 in [0, 2) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2
C_SET_ADDR_REG a3, gp0, gp9   ; %252=C_SET_ADDR_REG(gp0,%170)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%8)
; RELOAD %9 (slot 0) -> gp29
S_LD_INT gp29, gp0, 0
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%9)
S_SLLI_INT gp21, gp20, 20   ; %258=S_SLLI_INT(%246_sl_d_ec00_9fa0,20)
S_SLLI_INT gp22, gp20, 10   ; %281=S_SLLI_INT(%246_sl_d_ec00_9fa0,10)
S_ADD_INT gp23, gp15, gp21   ; %300=S_ADD_INT(%241,%258)
S_ADD_INT gp24, gp15, gp21   ; %301=S_ADD_INT(%241,%258)
; for 257_v2h_inner_24e0 in [0, 4) -- hw counter gp21, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp21, 4
S_SLLI_INT gp26, gp25, 18   ; %267=S_SLLI_INT(%257_v2h_inner_24e0,18)
S_ADD_INT gp29, gp24, gp26   ; %271=S_ADD_INT(%301,%267)
; STBACK %271 gp29 -> slot 13
S_ST_INT gp29, gp0, 13
S_SLLI_INT gp26, gp25, 19   ; %277=S_SLLI_INT(%257_v2h_inner_24e0,19)
S_ADD_INT gp29, gp18, gp26   ; %278=S_ADD_INT(%24,%277)
; STBACK %278 gp29 -> slot 14
S_ST_INT gp29, gp0, 14
; RELOAD %278 (slot 14) -> gp29
S_LD_INT gp29, gp0, 14
S_ADD_INT gp26, gp29, gp22   ; %282=S_ADD_INT(%278,%281)
; RELOAD %271 (slot 13) -> gp29
S_LD_INT gp29, gp0, 13
H_STORE_V gp29, gp26, a3, 1, 0   ; H_STORE_V(%271,%282,%252,1,0)
; idx 257_v2h_inner_24e0 += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp21
; idx 246_sl_d_ec00_9fa0 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; idx 1_bx += 1 (gp17)
S_ADDI_INT gp17, gp17, 1
C_LOOP_END gp16
