; PLENA ISA  --  kernel: qknorm_q
; generated by tilelang_tvm_compiler (PreIsaIR v2 → MIR path)
; ============================================================
S_LUI_INT gp29, 6912   ; %8=S_LUI_INT(6912)
; STBACK %8 gp29 -> slot 0
S_ST_INT gp29, gp0, 0
S_LUI_INT gp29, 2048   ; %11=S_LUI_INT(2048)
; STBACK %11 gp29 -> slot 1
S_ST_INT gp29, gp0, 1
S_ADDI_INT gp29, gp0, 2048   ; %12=S_ADDI_INT(%0_gp0,2048)
; STBACK %12 gp29 -> slot 2
S_ST_INT gp29, gp0, 2
S_LUI_INT gp29, 62208   ; %46=S_LUI_INT(62208)
; STBACK %46 gp29 -> slot 3
S_ST_INT gp29, gp0, 3
S_LUI_INT gp29, 16128   ; %193=S_LUI_INT(16128)
; STBACK %193 gp29 -> slot 4
S_ST_INT gp29, gp0, 4
S_LUI_INT gp1, 256   ; %65=S_LUI_INT(256)
S_LUI_INT gp2, 768   ; %85=S_LUI_INT(768)
S_LUI_INT gp3, 1024   ; %90=S_LUI_INT(1024)
S_LUI_INT gp4, 1280   ; %98=S_LUI_INT(1280)
S_LUI_INT gp5, 1536   ; %155=S_LUI_INT(1536)
S_LUI_INT gp6, 512   ; %183=S_LUI_INT(512)
S_ADDI_INT gp7, gp0, 1   ; %108=S_ADDI_INT(%0_gp0,1)
S_ADDI_INT gp8, gp0, 40992   ; %129=S_ADDI_INT(%0_gp0,40992)
S_ADDI_INT gp9, gp0, 40993   ; %136=S_ADDI_INT(%0_gp0,40993)
; for 1_bx in [0, 4) -- hw counter gp10, idx gp11
S_ADDI_INT gp11, gp0, 0
C_LOOP_START gp10, 4
S_SLLI_INT gp12, gp11, 21   ; %27=S_SLLI_INT(%1_bx,21)
; for 2_by_number in [0, 2) -- hw counter gp13, idx gp14
S_ADDI_INT gp14, gp0, 0
C_LOOP_START gp13, 2
; dma_h2v_slice X_hbm -> X_sh  (grid d=1 s=1 h=1 b=1)
; RELOAD %8 (slot 0) -> gp29
S_LD_INT gp29, gp0, 0
C_SET_ADDR_REG a0, gp0, gp29   ; %9=C_SET_ADDR_REG(gp0,%8)
; RELOAD %11 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_SCALE_REG gp29   ; C_SET_SCALE_REG(%11)
; RELOAD %12 (slot 2) -> gp29
S_LD_INT gp29, gp0, 2
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%12)
S_SLLI_INT gp15, gp14, 10   ; %33=S_SLLI_INT(%2_by_number,10)
; for 14_h2v_inner_b050 in [0, 4) -- hw counter gp16, idx gp17
S_ADDI_INT gp17, gp0, 0
C_LOOP_START gp16, 4
S_SLLI_INT gp18, gp17, 18   ; %24=S_SLLI_INT(%14_h2v_inner_b050,18)
S_SLLI_INT gp19, gp17, 19   ; %31=S_SLLI_INT(%14_h2v_inner_b050,19)
S_ADD_INT gp20, gp12, gp19   ; %32=S_ADD_INT(%27,%31)
S_ADD_INT gp19, gp20, gp15   ; %34=S_ADD_INT(%32,%33)
H_PREFETCH_V gp18, gp19, a0, 1, 0   ; H_PREFETCH_V(%24,%34,%9,1,0)
; idx 14_h2v_inner_b050 += 1 (gp17)
S_ADDI_INT gp17, gp17, 1
C_LOOP_END gp16
; dma_h2v_slice SCALE_hbm -> SCALE_sh  (grid d=1 s=1 h=1 b=1)
; RELOAD %46 (slot 3) -> gp29
S_LD_INT gp29, gp0, 3
C_SET_ADDR_REG a1, gp0, gp29   ; %47=C_SET_ADDR_REG(gp0,%46)
; RELOAD %11 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_SCALE_REG gp29   ; C_SET_SCALE_REG(%11)
; RELOAD %12 (slot 2) -> gp29
S_LD_INT gp29, gp0, 2
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%12)
S_ADD_INT gp16, gp12, gp15   ; %253=S_ADD_INT(%27,%33)
S_ADD_INT gp17, gp12, gp15   ; %255=S_ADD_INT(%27,%33)
; for 52_h2v_inner_b290 in [0, 4) -- hw counter gp18, idx gp19
S_ADDI_INT gp19, gp0, 0
C_LOOP_START gp18, 4
S_SLLI_INT gp20, gp19, 18   ; %62=S_SLLI_INT(%52_h2v_inner_b290,18)
S_ADD_INT gp21, gp20, gp1   ; %66=S_ADD_INT(%62,%65)
S_SLLI_INT gp20, gp19, 19   ; %72=S_SLLI_INT(%52_h2v_inner_b290,19)
S_ADD_INT gp22, gp17, gp20   ; %75=S_ADD_INT(%255,%72)
H_PREFETCH_V gp21, gp22, a1, 1, 0   ; H_PREFETCH_V(%66,%75,%47,1,0)
; idx 52_h2v_inner_b290 += 1 (gp19)
S_ADDI_INT gp19, gp19, 1
C_LOOP_END gp18
; copy_v_to_v src.parent=X_sh -> dst.parent=X_loc extents=[1, 1024, 8, 128]
; for 82_copy_row_31a0 in [0, 1024) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 1024
S_SLLI_INT gp19, gp18, 10   ; %83=S_SLLI_INT(%82_copy_row_31a0,10)
S_ADD_INT gp20, gp19, gp2   ; %86=S_ADD_INT(%83,%85)
V_ADD_VF gp20, gp19, f0, 0   ; V_ADD_VF(%86,%83,f0,0)
; idx 82_copy_row_31a0 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; copy_v_to_v src.parent=SCALE_sh -> dst.parent=SC_loc extents=[1, 1024, 8, 128]
; for 87_copy_row_3350 in [0, 1024) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 1024
S_SLLI_INT gp19, gp18, 10   ; %88=S_SLLI_INT(%87_copy_row_3350,10)
S_ADD_INT gp20, gp19, gp3   ; %91=S_ADD_INT(%88,%90)
S_ADD_INT gp21, gp1, gp19   ; %94=S_ADD_INT(%65,%88)
V_ADD_VF gp20, gp21, f0, 0   ; V_ADD_VF(%91,%94,f0,0)
; idx 87_copy_row_3350 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; for 95_row1 in [0, 1024) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 1024
; v binary v_mul V_MUL_VV dst.parent=SQ_loc starts=[0, row1, 0, 0] extents=[1, 1, 8, 128]
S_SLLI_INT gp19, gp18, 10   ; %96=S_SLLI_INT(%95_row1,10)
S_ADD_INT gp20, gp19, gp4   ; %99=S_ADD_INT(%96,%98)
S_ADD_INT gp21, gp2, gp19   ; %102=S_ADD_INT(%85,%96)
V_MUL_VV gp20, gp21, gp21, 0   ; V_MUL_VV(%99,%102,%102,0)
; idx 95_row1 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; for 103_by_phase in [0, 8) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 8
S_SLLI_INT gp19, gp18, 10   ; %105=S_SLLI_INT(%103_by_phase,10)
S_SRLI_INT gp20, gp18, 3   ; %109=S_SRLI_INT(%103_by_phase,3)
S_SLLI_INT gp21, gp20, 3   ; %110=S_SLLI_INT(%109,3)
S_SUB_INT gp22, gp18, gp21   ; %111=S_SUB_INT(%103_by_phase,%110)
S_SLL_INT gp21, gp7, gp22   ; %112=S_SLL_INT(%108,%111)
S_SLLI_INT gp22, gp20, 20   ; %117=S_SLLI_INT(%109,20)
; for 104_row in [0, 1024) -- hw counter gp20, idx gp23
S_ADDI_INT gp23, gp0, 0
C_LOOP_START gp20, 1024
; fp scalar task fp_zero_at op=zero
S_ADD_INT gp24, gp23, gp19   ; %106=S_ADD_INT(%104_row,%105)
S_ADDI_INT gp25, gp24, 32   ; %107=S_ADDI_INT(%106,32)
S_ST_FP f0, gp25, 0   ; S_ST_FP(f0,%107,0)
; row scalar task row_reduce_sum_at op=reduce_sum src.parent=SQ_loc starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp21   ; C_SET_V_MASK_REG(%112)
S_LD_FP f1, gp25, 0   ; S_LD_FP(f1,%107,0)
S_SLLI_INT gp26, gp23, 10   ; %118=S_SLLI_INT(%104_row,10)
S_ADD_INT gp27, gp22, gp26   ; %119=S_ADD_INT(%117,%118)
S_ADD_INT gp26, gp27, gp4   ; %122=S_ADD_INT(%119,%98)
V_RED_SUM f1, gp26, 1   ; V_RED_SUM(f1,%122,1)
S_ST_FP f1, gp25, 0   ; S_ST_FP(f1,%107,0)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; fp scalar task fp_mul_at op=mul
S_LD_FP f1, gp25, 0   ; S_LD_FP(f1,%107,0)
S_LD_FP f2, gp8, 0   ; S_LD_FP(f2,%129,0)
S_MUL_FP f1, f1, f2   ; S_MUL_FP(f1,f1,f2)
S_ADDI_INT gp25, gp24, 8224   ; %132=S_ADDI_INT(%106,8224)
S_ST_FP f1, gp25, 0   ; S_ST_FP(f1,%132,0)
; fp scalar task fp_add_at op=add
S_LD_FP f1, gp25, 0   ; S_LD_FP(f1,%132,0)
S_LD_FP f2, gp9, 0   ; S_LD_FP(f2,%136,0)
S_ADD_FP f1, f1, f2   ; S_ADD_FP(f1,f1,f2)
S_ADDI_INT gp25, gp24, 16416   ; %139=S_ADDI_INT(%106,16416)
S_ST_FP f1, gp25, 0   ; S_ST_FP(f1,%139,0)
; fp scalar task fp_sqrt_at op=sqrt
S_LD_FP f1, gp25, 0   ; S_LD_FP(f1,%139,0)
S_SQRT_FP f1, f1   ; S_SQRT_FP(f1,f1)
S_ADDI_INT gp25, gp24, 24608   ; %145=S_ADDI_INT(%106,24608)
S_ST_FP f1, gp25, 0   ; S_ST_FP(f1,%145,0)
; fp scalar task fp_reci_at op=reci
S_LD_FP f1, gp25, 0   ; S_LD_FP(f1,%145,0)
S_RECI_FP f1, f1   ; S_RECI_FP(f1,f1)
S_ADDI_INT gp25, gp24, 32800   ; %151=S_ADDI_INT(%106,32800)
S_ST_FP f1, gp25, 0   ; S_ST_FP(f1,%151,0)
; idx 104_row += 1 (gp23)
S_ADDI_INT gp23, gp23, 1
C_LOOP_END gp20
; idx 103_by_phase += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; for 152_row1 in [0, 1024) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 1024
; v binary v_mul V_MUL_VV dst.parent=Y_loc starts=[0, row1, 0, 0] extents=[1, 1, 8, 128]
S_SLLI_INT gp19, gp18, 10   ; %153=S_SLLI_INT(%152_row1,10)
S_ADD_INT gp20, gp19, gp5   ; %156=S_ADD_INT(%153,%155)
S_ADD_INT gp21, gp19, gp2   ; %159=S_ADD_INT(%153,%85)
S_ADD_INT gp22, gp19, gp3   ; %162=S_ADD_INT(%153,%90)
V_MUL_VV gp20, gp21, gp22, 0   ; V_MUL_VV(%156,%159,%162,0)
; idx 152_row1 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; for 163_by_phase in [0, 8) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 8
S_SRLI_INT gp19, gp18, 3   ; %166=S_SRLI_INT(%163_by_phase,3)
S_SLLI_INT gp20, gp19, 3   ; %167=S_SLLI_INT(%166,3)
S_SUB_INT gp21, gp18, gp20   ; %168=S_SUB_INT(%163_by_phase,%167)
S_SLL_INT gp20, gp7, gp21   ; %169=S_SLL_INT(%108,%168)
S_SLLI_INT gp21, gp18, 10   ; %170=S_SLLI_INT(%163_by_phase,10)
S_SLLI_INT gp22, gp19, 20   ; %174=S_SLLI_INT(%166,20)
S_ADD_INT gp19, gp5, gp22   ; %254=S_ADD_INT(%155,%174)
S_ADD_INT gp23, gp5, gp22   ; %256=S_ADD_INT(%155,%174)
; for 164_row in [0, 1024) -- hw counter gp22, idx gp24
S_ADDI_INT gp24, gp0, 0
C_LOOP_START gp22, 1024
; row scalar task row_mul_fp op=mul src.parent=Y_loc starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp20   ; C_SET_V_MASK_REG(%169)
S_ADD_INT gp25, gp24, gp21   ; %171=S_ADD_INT(%164_row,%170)
S_ADDI_INT gp26, gp25, 32800   ; %172=S_ADDI_INT(%171,32800)
S_LD_FP f1, gp26, 0   ; S_LD_FP(f1,%172,0)
S_SLLI_INT gp25, gp24, 10   ; %175=S_SLLI_INT(%164_row,10)
S_ADD_INT gp26, gp23, gp25   ; %179=S_ADD_INT(%256,%175)
V_MUL_VF gp26, gp26, f1, 1   ; V_MUL_VF(%179,%179,f1,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; idx 164_row += 1 (gp24)
S_ADDI_INT gp24, gp24, 1
C_LOOP_END gp22
; idx 163_by_phase += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; copy_v_to_v src.parent=Y_loc -> dst.parent=Y_sh extents=[1, 1024, 8, 128]
; for 180_copy_row_1b20 in [0, 1024) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 1024
S_SLLI_INT gp20, gp18, 10   ; %181=S_SLLI_INT(%180_copy_row_1b20,10)
S_ADD_INT gp21, gp20, gp6   ; %184=S_ADD_INT(%181,%183)
S_ADD_INT gp22, gp5, gp20   ; %187=S_ADD_INT(%155,%181)
V_ADD_VF gp21, gp22, f0, 0   ; V_ADD_VF(%184,%187,f0,0)
; idx 180_copy_row_1b20 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; dma_v2h_slice Y_sh -> Y_hbm  (grid d=1 s=1 h=1 b=1)
; RELOAD %193 (slot 4) -> gp29
S_LD_INT gp29, gp0, 4
C_SET_ADDR_REG a2, gp0, gp29   ; %194=C_SET_ADDR_REG(gp0,%193)
; RELOAD %11 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_SCALE_REG gp29   ; C_SET_SCALE_REG(%11)
; RELOAD %12 (slot 2) -> gp29
S_LD_INT gp29, gp0, 2
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%12)
; for 199_v2h_inner_4410 in [0, 4) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 4
S_SLLI_INT gp20, gp18, 18   ; %209=S_SLLI_INT(%199_v2h_inner_4410,18)
S_ADD_INT gp21, gp6, gp20   ; %213=S_ADD_INT(%183,%209)
S_SLLI_INT gp20, gp18, 19   ; %219=S_SLLI_INT(%199_v2h_inner_4410,19)
S_ADD_INT gp22, gp20, gp12   ; %220=S_ADD_INT(%219,%27)
S_ADD_INT gp20, gp22, gp15   ; %222=S_ADD_INT(%220,%33)
H_STORE_V gp21, gp20, a2, 1, 0   ; H_STORE_V(%213,%222,%194,1,0)
; idx 199_v2h_inner_4410 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; idx 2_by_number += 1 (gp14)
S_ADDI_INT gp14, gp14, 1
C_LOOP_END gp13
; idx 1_bx += 1 (gp11)
S_ADDI_INT gp11, gp11, 1
C_LOOP_END gp10
