; PLENA ISA  --  kernel: T_norm1
; generated by tilelang_tvm_compiler (PreIsaIR v2 → MIR path)
; ============================================================
S_LUI_INT gp29, 1152   ; %7=S_LUI_INT(1152)
; STBACK %7 gp29 -> slot 0
S_ST_INT gp29, gp0, 0
S_LUI_INT gp1, 1024   ; %10=S_LUI_INT(1024)
S_ADDI_INT gp29, gp0, 2048   ; %11=S_ADDI_INT(%0_gp0,2048)
; STBACK %11 gp29 -> slot 1
S_ST_INT gp29, gp0, 1
S_LUI_INT gp29, 68256   ; %43=S_LUI_INT(68256)
; STBACK %43 gp29 -> slot 2
S_ST_INT gp29, gp0, 2
S_LUI_INT gp2, 512   ; %62=S_LUI_INT(512)
S_LUI_INT gp29, 69408   ; %82=S_LUI_INT(69408)
; STBACK %82 gp29 -> slot 3
S_ST_INT gp29, gp0, 3
S_LUI_INT gp3, 2048   ; %119=S_LUI_INT(2048)
S_LUI_INT gp4, 2560   ; %124=S_LUI_INT(2560)
S_LUI_INT gp5, 3072   ; %132=S_LUI_INT(3072)
S_ADDI_INT gp6, gp0, 7200   ; %149=S_ADDI_INT(%0_gp0,7200)
S_LUI_INT gp7, 3584   ; %162=S_LUI_INT(3584)
S_LUI_INT gp8, 3840   ; %169=S_LUI_INT(3840)
S_LUI_INT gp9, 2304   ; %172=S_LUI_INT(2304)
S_ADDI_INT gp10, gp0, 7201   ; %189=S_ADDI_INT(%0_gp0,7201)
S_LUI_INT gp11, 4096   ; %198=S_LUI_INT(4096)
S_LUI_INT gp12, 4352   ; %208=S_LUI_INT(4352)
S_LUI_INT gp13, 2816   ; %214=S_LUI_INT(2816)
S_LUI_INT gp14, 3328   ; %238=S_LUI_INT(3328)
S_LUI_INT gp15, 1536   ; %243=S_LUI_INT(1536)
S_LUI_INT gp29, 12672   ; %253=S_LUI_INT(12672)
; STBACK %253 gp29 -> slot 4
S_ST_INT gp29, gp0, 4
; for 1_bx in [0, 2) -- hw counter gp16, idx gp17
S_ADDI_INT gp17, gp0, 0
C_LOOP_START gp16, 2
; dma_h2v_slice X_hbm -> X_sh  (grid d=2 s=1 h=1 b=1)
S_SLLI_INT gp18, gp17, 21   ; %26=S_SLLI_INT(%1_bx,21)
; for 2_sl_d_6c00_6b40 in [0, 2) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2
; RELOAD %7 (slot 0) -> gp29
S_LD_INT gp29, gp0, 0
C_SET_ADDR_REG a0, gp0, gp29   ; %8=C_SET_ADDR_REG(gp0,%7)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%10)
; RELOAD %11 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%11)
S_SLLI_INT gp21, gp20, 20   ; %14=S_SLLI_INT(%2_sl_d_6c00_6b40,20)
S_SLLI_INT gp22, gp20, 10   ; %34=S_SLLI_INT(%2_sl_d_6c00_6b40,10)
; for 13_h2v_inner_650 in [0, 4) -- hw counter gp23, idx gp24
S_ADDI_INT gp24, gp0, 0
C_LOOP_START gp23, 4
S_SLLI_INT gp25, gp24, 18   ; %23=S_SLLI_INT(%13_h2v_inner_650,18)
S_ADD_INT gp29, gp21, gp25   ; %24=S_ADD_INT(%14,%23)
; STBACK %24 gp29 -> slot 5
S_ST_INT gp29, gp0, 5
S_SLLI_INT gp25, gp24, 19   ; %30=S_SLLI_INT(%13_h2v_inner_650,19)
S_ADD_INT gp29, gp18, gp25   ; %31=S_ADD_INT(%26,%30)
; STBACK %31 gp29 -> slot 6
S_ST_INT gp29, gp0, 6
; RELOAD %31 (slot 6) -> gp29
S_LD_INT gp29, gp0, 6
S_ADD_INT gp25, gp29, gp22   ; %35=S_ADD_INT(%31,%34)
; RELOAD %24 (slot 5) -> gp29
S_LD_INT gp29, gp0, 5
H_PREFETCH_V gp29, gp25, a0, 1, 0   ; H_PREFETCH_V(%24,%35,%8,1,0)
; idx 13_h2v_inner_650 += 1 (gp24)
S_ADDI_INT gp24, gp24, 1
C_LOOP_END gp23
; idx 2_sl_d_6c00_6b40 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; dma_h2v_slice SCALE_hbm -> SCALE_sh  (grid d=2 s=1 h=1 b=1)
; for 38_sl_d_76b0_7f80 in [0, 2) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2
; RELOAD %43 (slot 2) -> gp29
S_LD_INT gp29, gp0, 2
C_SET_ADDR_REG a1, gp0, gp29   ; %44=C_SET_ADDR_REG(gp0,%43)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%10)
; RELOAD %11 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%11)
S_SLLI_INT gp21, gp20, 20   ; %50=S_SLLI_INT(%38_sl_d_76b0_7f80,20)
S_SLLI_INT gp22, gp20, 10   ; %73=S_SLLI_INT(%38_sl_d_76b0_7f80,10)
; for 49_h2v_inner_890 in [0, 4) -- hw counter gp23, idx gp24
S_ADDI_INT gp24, gp0, 0
C_LOOP_START gp23, 4
S_SLLI_INT gp25, gp24, 18   ; %59=S_SLLI_INT(%49_h2v_inner_890,18)
S_ADD_INT gp29, gp21, gp25   ; %60=S_ADD_INT(%50,%59)
; STBACK %60 gp29 -> slot 7
S_ST_INT gp29, gp0, 7
; RELOAD %60 (slot 7) -> gp29
S_LD_INT gp29, gp0, 7
S_ADD_INT gp25, gp29, gp2   ; %63=S_ADD_INT(%60,%62)
S_SLLI_INT gp29, gp24, 19   ; %69=S_SLLI_INT(%49_h2v_inner_890,19)
; STBACK %69 gp29 -> slot 8
S_ST_INT gp29, gp0, 8
; RELOAD %69 (slot 8) -> gp29
S_LD_INT gp29, gp0, 8
S_ADD_INT gp30, gp18, gp29   ; %70=S_ADD_INT(%26,%69)
; STBACK %70 gp30 -> slot 9
S_ST_INT gp30, gp0, 9
; RELOAD %70 (slot 9) -> gp29
S_LD_INT gp29, gp0, 9
S_ADD_INT gp30, gp29, gp22   ; %74=S_ADD_INT(%70,%73)
; STBACK %74 gp30 -> slot 10
S_ST_INT gp30, gp0, 10
; RELOAD %74 (slot 10) -> gp29
S_LD_INT gp29, gp0, 10
H_PREFETCH_V gp25, gp29, a1, 1, 0   ; H_PREFETCH_V(%63,%74,%44,1,0)
; idx 49_h2v_inner_890 += 1 (gp24)
S_ADDI_INT gp24, gp24, 1
C_LOOP_END gp23
; idx 38_sl_d_76b0_7f80 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; dma_h2v_slice BIAS_hbm -> BIAS_sh  (grid d=2 s=1 h=1 b=1)
; for 77_sl_d_4440_7e30 in [0, 2) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2
; RELOAD %82 (slot 3) -> gp29
S_LD_INT gp29, gp0, 3
C_SET_ADDR_REG a2, gp0, gp29   ; %83=C_SET_ADDR_REG(gp0,%82)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%10)
; RELOAD %11 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%11)
S_SLLI_INT gp21, gp20, 20   ; %89=S_SLLI_INT(%77_sl_d_4440_7e30,20)
S_SLLI_INT gp22, gp20, 10   ; %112=S_SLLI_INT(%77_sl_d_4440_7e30,10)
S_ADD_INT gp23, gp1, gp21   ; %329=S_ADD_INT(%10,%89)
S_ADD_INT gp24, gp1, gp21   ; %332=S_ADD_INT(%10,%89)
; for 88_h2v_inner_ad0 in [0, 4) -- hw counter gp21, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp21, 4
S_SLLI_INT gp26, gp25, 18   ; %98=S_SLLI_INT(%88_h2v_inner_ad0,18)
S_ADD_INT gp29, gp24, gp26   ; %102=S_ADD_INT(%332,%98)
; STBACK %102 gp29 -> slot 11
S_ST_INT gp29, gp0, 11
S_SLLI_INT gp26, gp25, 19   ; %108=S_SLLI_INT(%88_h2v_inner_ad0,19)
S_ADD_INT gp29, gp26, gp22   ; %290=S_ADD_INT(%108,%112)
; STBACK %290 gp29 -> slot 12
S_ST_INT gp29, gp0, 12
; RELOAD %290 (slot 12) -> gp29
S_LD_INT gp29, gp0, 12
S_ADD_INT gp26, gp29, gp18   ; %113=S_ADD_INT(%290,%26)
; RELOAD %102 (slot 11) -> gp29
S_LD_INT gp29, gp0, 11
H_PREFETCH_V gp29, gp26, a2, 1, 0   ; H_PREFETCH_V(%102,%113,%83,1,0)
; idx 88_h2v_inner_ad0 += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp21
; idx 77_sl_d_4440_7e30 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; copy_v_to_v src.parent=X_sh -> dst.parent=X_loc extents=[1, 1024, 1, 2048]
; for 116_copy_row_2090 in [0, 2048) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2048
S_SLLI_INT gp21, gp20, 10   ; %117=S_SLLI_INT(%116_copy_row_2090,10)
S_ADD_INT gp22, gp21, gp3   ; %120=S_ADD_INT(%117,%119)
V_ADD_VF gp22, gp21, f0, 0   ; V_ADD_VF(%120,%117,f0,0)
; idx 116_copy_row_2090 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; copy_v_to_v src.parent=SCALE_sh -> dst.parent=SC_loc extents=[1, 1024, 1, 2048]
; for 121_copy_row_2120 in [0, 2048) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2048
S_SLLI_INT gp21, gp20, 10   ; %122=S_SLLI_INT(%121_copy_row_2120,10)
S_ADD_INT gp22, gp21, gp4   ; %125=S_ADD_INT(%122,%124)
S_ADD_INT gp24, gp21, gp2   ; %128=S_ADD_INT(%122,%62)
V_ADD_VF gp22, gp24, f0, 0   ; V_ADD_VF(%125,%128,f0,0)
; idx 121_copy_row_2120 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; copy_v_to_v src.parent=BIAS_sh -> dst.parent=BI_loc extents=[1, 1024, 1, 2048]
; for 129_copy_row_7380 in [0, 2048) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2048
S_SLLI_INT gp21, gp20, 10   ; %130=S_SLLI_INT(%129_copy_row_7380,10)
S_ADD_INT gp22, gp21, gp5   ; %133=S_ADD_INT(%130,%132)
S_ADD_INT gp24, gp1, gp21   ; %136=S_ADD_INT(%10,%130)
V_ADD_VF gp22, gp24, f0, 0   ; V_ADD_VF(%133,%136,f0,0)
; idx 129_copy_row_7380 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 137_row in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; fp scalar task fp_zero_at op=zero
S_ADDI_INT gp21, gp20, 32   ; %138=S_ADDI_INT(%137_row,32)
S_ST_FP f0, gp21, 0   ; S_ST_FP(f0,%138,0)
; row scalar task row_reduce_sum_at op=reduce_sum src.parent=X_loc starts=[0, row, 0, 0]
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%138,0)
S_SLLI_INT gp22, gp20, 10   ; %142=S_SLLI_INT(%137_row,10)
; for 140_d_tile_2cf0 in [0, 2) -- hw counter gp24, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp24, 2
S_SLLI_INT gp26, gp25, 20   ; %141=S_SLLI_INT(%140_d_tile_2cf0,20)
S_ADD_INT gp27, gp3, gp26   ; %291=S_ADD_INT(%119,%141)
S_ADD_INT gp26, gp27, gp22   ; %146=S_ADD_INT(%291,%142)
V_RED_SUM f1, gp26, 0   ; V_RED_SUM(f1,%146,0)
; idx 140_d_tile_2cf0 += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp24
S_ST_FP f1, gp21, 0   ; S_ST_FP(f1,%138,0)
; fp scalar task fp_mul_at op=mul
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%138,0)
S_LD_FP f2, gp6, 0   ; S_LD_FP(f2,%149,0)
S_MUL_FP f1, f1, f2   ; S_MUL_FP(f1,f1,f2)
S_ADDI_INT gp21, gp20, 1056   ; %150=S_ADDI_INT(%137_row,1056)
S_ST_FP f1, gp21, 0   ; S_ST_FP(f1,%150,0)
; row scalar task row_sub_fp op=sub src.parent=X_loc starts=[0, row, 0, 0]
S_LD_FP f1, gp21, 0   ; S_LD_FP(f1,%150,0)
S_ADD_INT gp21, gp3, gp22   ; %330=S_ADD_INT(%119,%142)
S_ADD_INT gp24, gp3, gp22   ; %333=S_ADD_INT(%119,%142)
; for 152_d_tile_2d50 in [0, 2) -- hw counter gp22, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp22, 2
S_SLLI_INT gp26, gp25, 20   ; %153=S_SLLI_INT(%152_d_tile_2d50,20)
S_ADD_INT gp27, gp24, gp26   ; %158=S_ADD_INT(%333,%153)
V_SUB_VF gp27, gp27, f1, 0, 0   ; V_SUB_VF(%158,%158,f1,0,0)
; idx 152_d_tile_2d50 += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp22
; idx 137_row += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 159_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; v binary v_mul V_MUL_VV dst.parent=SQ_loc starts=[0, row1, 0, 0] extents=[1, 1, 1, 2048]
S_SLLI_INT gp22, gp20, 10   ; %160=S_SLLI_INT(%159_row1,10)
S_ADD_INT gp24, gp22, gp7   ; %163=S_ADD_INT(%160,%162)
S_ADD_INT gp25, gp3, gp22   ; %166=S_ADD_INT(%119,%160)
V_MUL_VV gp24, gp25, gp25, 0   ; V_MUL_VV(%163,%166,%166,0)
S_ADD_INT gp24, gp22, gp8   ; %170=S_ADD_INT(%160,%169)
S_ADD_INT gp25, gp22, gp9   ; %173=S_ADD_INT(%160,%172)
V_MUL_VV gp24, gp25, gp25, 0   ; V_MUL_VV(%170,%173,%173,0)
; idx 159_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 174_row in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; fp scalar task fp_zero_at op=zero
S_ADDI_INT gp22, gp20, 2080   ; %175=S_ADDI_INT(%174_row,2080)
S_ST_FP f0, gp22, 0   ; S_ST_FP(f0,%175,0)
; row scalar task row_reduce_sum_at op=reduce_sum src.parent=SQ_loc starts=[0, row, 0, 0]
S_LD_FP f1, gp22, 0   ; S_LD_FP(f1,%175,0)
S_SLLI_INT gp24, gp20, 10   ; %179=S_SLLI_INT(%174_row,10)
; for 177_d_tile_2d20 in [0, 2) -- hw counter gp25, idx gp26
S_ADDI_INT gp26, gp0, 0
C_LOOP_START gp25, 2
S_SLLI_INT gp27, gp26, 20   ; %178=S_SLLI_INT(%177_d_tile_2d20,20)
S_ADD_INT gp28, gp7, gp27   ; %293=S_ADD_INT(%162,%178)
S_ADD_INT gp27, gp28, gp24   ; %183=S_ADD_INT(%293,%179)
V_RED_SUM f1, gp27, 0   ; V_RED_SUM(f1,%183,0)
; idx 177_d_tile_2d20 += 1 (gp26)
S_ADDI_INT gp26, gp26, 1
C_LOOP_END gp25
S_ST_FP f1, gp22, 0   ; S_ST_FP(f1,%175,0)
; fp scalar task fp_mul_at op=mul
S_LD_FP f1, gp22, 0   ; S_LD_FP(f1,%175,0)
S_LD_FP f2, gp6, 0   ; S_LD_FP(f2,%149,0)
S_MUL_FP f1, f1, f2   ; S_MUL_FP(f1,f1,f2)
S_ADDI_INT gp22, gp20, 3104   ; %187=S_ADDI_INT(%174_row,3104)
S_ST_FP f1, gp22, 0   ; S_ST_FP(f1,%187,0)
; fp scalar task fp_add_at op=add
S_LD_FP f1, gp22, 0   ; S_LD_FP(f1,%187,0)
S_LD_FP f2, gp10, 0   ; S_LD_FP(f2,%189,0)
S_ADD_FP f1, f1, f2   ; S_ADD_FP(f1,f1,f2)
S_ADDI_INT gp22, gp20, 4128   ; %190=S_ADDI_INT(%174_row,4128)
S_ST_FP f1, gp22, 0   ; S_ST_FP(f1,%190,0)
; fp scalar task fp_sqrt_at op=sqrt
S_LD_FP f1, gp22, 0   ; S_LD_FP(f1,%190,0)
S_SQRT_FP f1, f1   ; S_SQRT_FP(f1,f1)
S_ADDI_INT gp22, gp20, 5152   ; %192=S_ADDI_INT(%174_row,5152)
S_ST_FP f1, gp22, 0   ; S_ST_FP(f1,%192,0)
; fp scalar task fp_reci_at op=reci
S_LD_FP f1, gp22, 0   ; S_LD_FP(f1,%192,0)
S_RECI_FP f1, f1   ; S_RECI_FP(f1,f1)
S_ADDI_INT gp22, gp20, 6176   ; %194=S_ADDI_INT(%174_row,6176)
S_ST_FP f1, gp22, 0   ; S_ST_FP(f1,%194,0)
; idx 174_row += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 195_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; v binary v_mul V_MUL_VV dst.parent=Y_loc starts=[0, row1, 0, 0] extents=[1, 1, 1, 2048]
S_SLLI_INT gp22, gp20, 10   ; %196=S_SLLI_INT(%195_row1,10)
S_ADD_INT gp24, gp22, gp11   ; %199=S_ADD_INT(%196,%198)
S_ADD_INT gp25, gp3, gp22   ; %202=S_ADD_INT(%119,%196)
S_ADD_INT gp26, gp4, gp22   ; %205=S_ADD_INT(%124,%196)
V_MUL_VV gp24, gp25, gp26, 0   ; V_MUL_VV(%199,%202,%205,0)
S_ADD_INT gp24, gp22, gp12   ; %209=S_ADD_INT(%196,%208)
S_ADD_INT gp25, gp9, gp22   ; %212=S_ADD_INT(%172,%196)
S_ADD_INT gp26, gp22, gp13   ; %215=S_ADD_INT(%196,%214)
V_MUL_VV gp24, gp25, gp26, 0   ; V_MUL_VV(%209,%212,%215,0)
; idx 195_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 216_row in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; row scalar task row_mul_fp op=mul src.parent=Y_loc starts=[0, row, 0, 0]
S_ADDI_INT gp22, gp20, 6176   ; %217=S_ADDI_INT(%216_row,6176)
S_LD_FP f1, gp22, 0   ; S_LD_FP(f1,%217,0)
S_SLLI_INT gp22, gp20, 10   ; %220=S_SLLI_INT(%216_row,10)
; for 218_d_tile_2750 in [0, 2) -- hw counter gp24, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp24, 2
S_SLLI_INT gp26, gp25, 20   ; %219=S_SLLI_INT(%218_d_tile_2750,20)
S_ADD_INT gp27, gp11, gp26   ; %297=S_ADD_INT(%198,%219)
S_ADD_INT gp26, gp27, gp22   ; %224=S_ADD_INT(%297,%220)
V_MUL_VF gp26, gp26, f1, 0   ; V_MUL_VF(%224,%224,f1,0)
; idx 218_d_tile_2750 += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp24
; idx 216_row += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 225_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; v binary v_add V_ADD_VV dst.parent=Y_loc starts=[0, row1, 0, 0] extents=[1, 1, 1, 2048]
S_SLLI_INT gp22, gp20, 10   ; %226=S_SLLI_INT(%225_row1,10)
S_ADD_INT gp24, gp11, gp22   ; %229=S_ADD_INT(%198,%226)
S_ADD_INT gp25, gp5, gp22   ; %232=S_ADD_INT(%132,%226)
V_ADD_VV gp24, gp24, gp25, 0   ; V_ADD_VV(%229,%229,%232,0)
S_ADD_INT gp24, gp12, gp22   ; %236=S_ADD_INT(%208,%226)
S_ADD_INT gp25, gp22, gp14   ; %239=S_ADD_INT(%226,%238)
V_ADD_VV gp24, gp24, gp25, 0   ; V_ADD_VV(%236,%236,%239,0)
; idx 225_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; copy_v_to_v src.parent=Y_loc -> dst.parent=Y_sh extents=[1, 1024, 1, 2048]
; for 240_copy_row_2930 in [0, 2048) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2048
S_SLLI_INT gp22, gp20, 10   ; %241=S_SLLI_INT(%240_copy_row_2930,10)
S_ADD_INT gp24, gp22, gp15   ; %244=S_ADD_INT(%241,%243)
S_ADD_INT gp25, gp11, gp22   ; %247=S_ADD_INT(%198,%241)
V_ADD_VF gp24, gp25, f0, 0   ; V_ADD_VF(%244,%247,f0,0)
; idx 240_copy_row_2930 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; dma_v2h_slice Y_sh -> Y_hbm  (grid d=2 s=1 h=1 b=1)
; for 248_sl_d_7920_5ca0 in [0, 2) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 2
; RELOAD %253 (slot 4) -> gp29
S_LD_INT gp29, gp0, 4
C_SET_ADDR_REG a3, gp0, gp29   ; %254=C_SET_ADDR_REG(gp0,%253)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%10)
; RELOAD %11 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%11)
S_SLLI_INT gp22, gp20, 20   ; %260=S_SLLI_INT(%248_sl_d_7920_5ca0,20)
S_SLLI_INT gp24, gp20, 10   ; %283=S_SLLI_INT(%248_sl_d_7920_5ca0,10)
S_ADD_INT gp25, gp15, gp22   ; %331=S_ADD_INT(%243,%260)
S_ADD_INT gp26, gp15, gp22   ; %334=S_ADD_INT(%243,%260)
; for 259_v2h_inner_1fd0 in [0, 4) -- hw counter gp22, idx gp27
S_ADDI_INT gp27, gp0, 0
C_LOOP_START gp22, 4
S_SLLI_INT gp28, gp27, 18   ; %269=S_SLLI_INT(%259_v2h_inner_1fd0,18)
S_ADD_INT gp29, gp26, gp28   ; %273=S_ADD_INT(%334,%269)
; STBACK %273 gp29 -> slot 13
S_ST_INT gp29, gp0, 13
S_SLLI_INT gp28, gp27, 19   ; %279=S_SLLI_INT(%259_v2h_inner_1fd0,19)
S_ADD_INT gp29, gp18, gp28   ; %280=S_ADD_INT(%26,%279)
; STBACK %280 gp29 -> slot 14
S_ST_INT gp29, gp0, 14
; RELOAD %280 (slot 14) -> gp29
S_LD_INT gp29, gp0, 14
S_ADD_INT gp28, gp29, gp24   ; %284=S_ADD_INT(%280,%283)
; RELOAD %273 (slot 13) -> gp29
S_LD_INT gp29, gp0, 13
H_STORE_V gp29, gp28, a3, 1, 0   ; H_STORE_V(%273,%284,%254,1,0)
; idx 259_v2h_inner_1fd0 += 1 (gp27)
S_ADDI_INT gp27, gp27, 1
C_LOOP_END gp22
; idx 248_sl_d_7920_5ca0 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; idx 1_bx += 1 (gp17)
S_ADDI_INT gp17, gp17, 1
C_LOOP_END gp16
