; PLENA ISA  --  kernel: concat_q
; generated by tilelang_tvm_compiler (PreIsaIR v2 → MIR path)
; ============================================================
S_LUI_INT gp1, 20736   ; %9=S_LUI_INT(20736)
S_LUI_INT gp2, 1024   ; %12=S_LUI_INT(1024)
S_ADDI_INT gp3, gp0, 2048   ; %13=S_ADDI_INT(%0_gp0,2048)
S_LUI_INT gp4, 23040   ; %47=S_LUI_INT(23040)
S_LUI_INT gp5, 2048   ; %50=S_LUI_INT(2048)
S_LUI_INT gp6, 10368   ; %85=S_LUI_INT(10368)
; for 1_bx in [0, 4) -- hw counter gp7, idx gp8
S_ADDI_INT gp8, gp0, 0
C_LOOP_START gp7, 4
; for 2_sb in [0, 2) -- hw counter gp9, idx gp10
S_ADDI_INT gp10, gp0, 0
C_LOOP_START gp9, 2
S_SLLI_INT gp11, gp10, 21   ; %28=S_SLLI_INT(%2_sb,21)
; for 3_fb in [0, 2) -- hw counter gp12, idx gp13
S_ADDI_INT gp13, gp0, 0
C_LOOP_START gp12, 2
; dma_h2v_slice A_hbm -> sh  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a0, gp0, gp1   ; %10=C_SET_ADDR_REG(gp0,%9)
C_SET_SCALE_REG gp2   ; C_SET_SCALE_REG(%12)
C_SET_STRIDE_REG gp3   ; C_SET_STRIDE_REG(%13)
S_SLLI_INT gp14, gp13, 10   ; %36=S_SLLI_INT(%3_fb,10)
; for 15_h2v_inner_c0b0 in [0, 4) -- hw counter gp15, idx gp16
S_ADDI_INT gp16, gp0, 0
C_LOOP_START gp15, 4
S_SLLI_INT gp17, gp16, 18   ; %25=S_SLLI_INT(%15_h2v_inner_c0b0,18)
S_SLLI_INT gp18, gp16, 19   ; %32=S_SLLI_INT(%15_h2v_inner_c0b0,19)
S_ADD_INT gp19, gp11, gp18   ; %33=S_ADD_INT(%28,%32)
S_ADD_INT gp18, gp19, gp14   ; %37=S_ADD_INT(%33,%36)
H_PREFETCH_V gp17, gp18, a0, 1, 0   ; H_PREFETCH_V(%25,%37,%10,1,0)
; idx 15_h2v_inner_c0b0 += 1 (gp16)
S_ADDI_INT gp16, gp16, 1
C_LOOP_END gp15
; dma_v2h_slice sh -> Y_hbm  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a1, gp0, gp4   ; %48=C_SET_ADDR_REG(gp0,%47)
C_SET_SCALE_REG gp5   ; C_SET_SCALE_REG(%50)
C_SET_STRIDE_REG gp3   ; C_SET_STRIDE_REG(%13)
S_ADD_INT gp15, gp11, gp14   ; %173=S_ADD_INT(%28,%36)
S_ADD_INT gp16, gp11, gp14   ; %174=S_ADD_INT(%28,%36)
; for 53_v2h_inner_c2f0 in [0, 4) -- hw counter gp17, idx gp18
S_ADDI_INT gp18, gp0, 0
C_LOOP_START gp17, 4
S_SLLI_INT gp19, gp18, 18   ; %63=S_SLLI_INT(%53_v2h_inner_c2f0,18)
S_SLLI_INT gp20, gp18, 19   ; %70=S_SLLI_INT(%53_v2h_inner_c2f0,19)
S_ADD_INT gp21, gp16, gp20   ; %75=S_ADD_INT(%174,%70)
H_STORE_V gp19, gp21, a1, 1, 0   ; H_STORE_V(%63,%75,%48,1,0)
; idx 53_v2h_inner_c2f0 += 1 (gp18)
S_ADDI_INT gp18, gp18, 1
C_LOOP_END gp17
; dma_h2v_slice B_hbm -> sh  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a2, gp0, gp6   ; %86=C_SET_ADDR_REG(gp0,%85)
C_SET_SCALE_REG gp2   ; C_SET_SCALE_REG(%12)
C_SET_STRIDE_REG gp3   ; C_SET_STRIDE_REG(%13)
; for 91_h2v_inner_c530 in [0, 4) -- hw counter gp16, idx gp17
S_ADDI_INT gp17, gp0, 0
C_LOOP_START gp16, 4
S_SLLI_INT gp18, gp17, 18   ; %101=S_SLLI_INT(%91_h2v_inner_c530,18)
S_SLLI_INT gp19, gp17, 19   ; %108=S_SLLI_INT(%91_h2v_inner_c530,19)
S_ADD_INT gp20, gp19, gp11   ; %109=S_ADD_INT(%108,%28)
S_ADD_INT gp19, gp20, gp14   ; %113=S_ADD_INT(%109,%36)
H_PREFETCH_V gp18, gp19, a2, 1, 0   ; H_PREFETCH_V(%101,%113,%86,1,0)
; idx 91_h2v_inner_c530 += 1 (gp17)
S_ADDI_INT gp17, gp17, 1
C_LOOP_END gp16
; dma_v2h_slice sh -> Y_hbm  (grid d=1 s=1 h=1 b=1)
C_SET_ADDR_REG a3, gp0, gp4   ; %124=C_SET_ADDR_REG(gp0,%47)
C_SET_SCALE_REG gp5   ; C_SET_SCALE_REG(%50)
C_SET_STRIDE_REG gp3   ; C_SET_STRIDE_REG(%13)
; for 129_v2h_inner_c770 in [0, 4) -- hw counter gp16, idx gp17
S_ADDI_INT gp17, gp0, 0
C_LOOP_START gp16, 4
S_SLLI_INT gp18, gp17, 18   ; %139=S_SLLI_INT(%129_v2h_inner_c770,18)
S_SLLI_INT gp19, gp17, 19   ; %146=S_SLLI_INT(%129_v2h_inner_c770,19)
S_ADD_INT gp20, gp2, gp19   ; %160=S_ADD_INT(%12,%146)
S_ADD_INT gp19, gp20, gp11   ; %161=S_ADD_INT(%160,%28)
S_ADD_INT gp20, gp19, gp14   ; %158=S_ADD_INT(%161,%36)
H_STORE_V gp18, gp20, a3, 1, 0   ; H_STORE_V(%139,%158,%124,1,0)
; idx 129_v2h_inner_c770 += 1 (gp17)
S_ADDI_INT gp17, gp17, 1
C_LOOP_END gp16
; idx 3_fb += 1 (gp13)
S_ADDI_INT gp13, gp13, 1
C_LOOP_END gp12
; idx 2_sb += 1 (gp10)
S_ADDI_INT gp10, gp10, 1
C_LOOP_END gp9
; idx 1_bx += 1 (gp8)
S_ADDI_INT gp8, gp8, 1
C_LOOP_END gp7
