`timescale 1ns / 1ps

`include "precision.svh"
`include "configuration.svh"
`include "operation.svh"

// Thin simulation-only boundary around the production VectorMachine.  The
// wrapper does not add registers: a cocotb edge that asserts op+valid is the
// full-machine timing start, while v_wreq/s_out_valid are the architectural
// result-ready events generated by the real top-level module.
module vector_machine_timing_wrapper
    import precision_pkg::*;
    import configuration_pkg::*;
    import instruction_pkg::*;
(
    input  logic clk,
    input  logic rst,
    input  logic [3:0] element_op,
    input  logic [2:0] reduction_op,
    input  logic broadcast_fp2,
    input  logic [VLEN-1:0][V_FP_EXP_WIDTH + V_FP_MANT_WIDTH:0] v_a,
    input  logic v_a_valid,
    input  logic [VLEN-1:0][V_FP_EXP_WIDTH + V_FP_MANT_WIDTH:0] v_b,
    input  logic v_b_valid,
    input  logic [V_FP_EXP_WIDTH + V_FP_MANT_WIDTH:0] scalar_in,
    input  logic scalar_in_valid,
    input  logic [FP_OPERAND_WIDTH-1:0] scalar_target,
    input  logic [ON_CHIP_ADDR_WIDTH-1:0] result_waddr,
    input  logic result_waddr_update,
    output logic vector_result_ready,
    output logic reduction_result_ready,
    output logic leaf_element_ready,
    output logic leaf_reduction_ready,
    output logic element_launch,
    output logic [ON_CHIP_ADDR_WIDTH-1:0] committed_waddr,
    output logic [V_FP_EXP_WIDTH + V_FP_MANT_WIDTH:0] committed_lane0
);
    logic [VLEN-1:0][V_FP_EXP_WIDTH + V_FP_MANT_WIDTH:0] v_out;
    logic [V_FP_EXP_WIDTH + V_FP_MANT_WIDTH:0] s_out;
    logic [FP_OPERAND_WIDTH-1:0] s_out_rd;

    vector_machine dut (
        .clk                 (clk),
        .rst                 (rst),
        .broadcast_fp2       (broadcast_fp2),
        .element_v_control   (V_ELEMENT_OP'(element_op)),
        .reduct_v_control    (V_REDUCT_OP'(reduction_op)),
        .v_a_in              (v_a),
        .v_a_valid           (v_a_valid),
        .v_b_in              (v_b),
        .v_b_valid           (v_b_valid),
        .s_in                (scalar_in),
        .s_in_valid          (scalar_in_valid),
        .s_wtarget           (scalar_target),
        .result_waddr        (result_waddr),
        .result_waddr_update (result_waddr_update),
        .v_out               (v_out),
        .v_waddr             (committed_waddr),
        .v_wreq              (vector_result_ready),
        .s_out               (s_out),
        .s_out_valid         (reduction_result_ready),
        .s_out_rd            (s_out_rd)
    );

    // These observation-only hierarchical taps quantify the latency added by
    // VectorMachine buffering/tracking around each leaf compute unit.
    assign leaf_element_ready   = dut.element_v_out_valid;
    assign leaf_reduction_ready = dut.reduction_unit.s_out_valid;
    assign element_launch       = dut.elem_push;
    // v_wreq is sampled after the committing clock edge. At that point the
    // combinational result_v_out may already have deasserted, while p1 holds
    // the exact value captured by that commit edge.
    assign committed_lane0      = dut.p1_result_v_out[0];
endmodule
