"""B1/B16 controlled Vector alternatives and native Matrix-state candidate.

Costs execute Compiler-generated control/addresses and actual Ramulator
requests. This is not full-model execution or silicon measurement. Raw memory
traces are temporary, generated by the bounded backend and removed after use.
"""
import argparse
from dataclasses import replace
import hashlib
import json
from pathlib import Path
from .ltile_dma import DmaBackend
from .ltile_platform import ExecutionProfile
from .ltile_services import Services
from .projection_campaign import write_csv
from .vector_recurrence import resources


def run(args):
    output=args.output.resolve();output.mkdir(parents=True,exist_ok=True)
    backend=DmaBackend(args.memory_root/"ltile_memory",args.memory_root/"ramulator.json",args.memory_root/"cache")
    controllers=len(json.loads((args.memory_root/"ramulator.json").read_text())["memory_system"]["controllers"])
    rows=[];stage_rows=[];cases=[]
    for kind in args.models:
        for batch in args.batches:
            for level in args.levels:
                for alu in (args.alus if 1<=level<=4 else ["shared"]):
                    profile=ExecutionProfile(hbm_controllers=controllers,projection_schedule="transposed",projection_k_tile=1024)
                    profile=replace(profile,machine=replace(profile.machine,lanes=args.lanes,vector_rec_alu=alu,vector_rec_alu_latency=args.alu_latency))
                    service=Services(args.compiler_root,profile,backend,output/"cache")
                    control="old_isa" if level==0 else "fsm" if level==5 else "row"
                    result=service.layer(kind,batch,control,supply="native" if level==5 else "packed",vector_candidate_level=level if 1<=level<=4 else 0)
                    name=f"{kind}_b{batch}_level{level}_{alu}"
                    path=output/(name+".json")
                    result["experiment"]=dict(level=level,alu=alu,units="cycles; entire batch one-token sublayer at modeled1GHz",arithmetic="original BF16instructionboundaries" if level==0 else "FP32fusedupdate/BF16products/tree/stateRN",resources=resources(level,profile.machine) if 1<=level<=4 else {"candidate":"ordinaryVector" if level==0 else "nativeMatrixL_TILE"},scope="not fullmodel, realweights, taskquality, RTL/PPA or GPU")
                    path.write_text(json.dumps(result,separators=(",",":"))+"\n")
                    row=dict(model=kind,batch=batch,level=level,alu=alu,lanes=args.lanes,**result["components"],
                        ms=result["components"]["total"]/1e6,hbm_read_bytes=result["hbm_read_bytes"],hbm_write_bytes=result["hbm_write_bytes"],
                        hbm_allocated_bytes=result["metadata"]["hbm_allocated_bytes"],assembly_sha256=result["assembly_sha256"],
                        result=path.name,result_sha256=hashlib.sha256(path.read_bytes()).hexdigest())
                    categories={s["name"]:s["category"] for s in result["metadata"]["stages"]}
                    for stage in result["sections"]:
                        stage_rows.append(dict(model=kind,batch=batch,level=level,alu=alu,category=categories[stage["name"]],**stage))
                    recurrent=[s for s in result["sections"] if categories[s["name"]] in ("recurrence","coefficient_layout")]
                    row["recurrence_plus_layout_cycles"]=sum(s["total"] for s in recurrent)
                    rows.append(row);cases.append(dict(name=name,result_sha256=row["result_sha256"]))
                    write_csv(output/"ladder.csv",rows);write_csv(output/"stages.csv",stage_rows)
                    print(json.dumps(row),flush=True)
    manifest=dict(clock_hz=10**9,models=args.models,batches=args.batches,levels=args.levels,alus=args.alus,lanes=args.lanes,
        source_sha256=Services(args.compiler_root,profile,backend,output/"cache").sources,
        memory=backend.identity,cases=cases,
        baseline="same software K1024transposed projection and commonMatrixview substrate; not bestunmodifiedPLENA",
        verification="representative numerical machinechecks separate; fullshape costs analyticalcompiledprogram/Ramulator")
    (output/"manifest.json").write_text(json.dumps(manifest,indent=2)+"\n")
    return rows


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output",type=Path,required=True);p.add_argument("--memory-root",type=Path,required=True)
    p.add_argument("--compiler-root",type=Path,required=True)
    p.add_argument("--models",nargs="+",choices=["mamba","kda"],default=["mamba","kda"])
    p.add_argument("--batches",nargs="+",type=int,default=[1,16]);p.add_argument("--levels",nargs="+",type=int,default=list(range(6)))
    p.add_argument("--alus",nargs="+",choices=["shared","dedicated"],default=["shared","dedicated"])
    p.add_argument("--alu-latency",type=int,default=2)
    p.add_argument("--lanes",type=int,choices=[128,256,512],default=256)
    run(p.parse_args())


if __name__=="__main__":main()
