; PLENA ISA  --  kernel: gelu
; generated by tilelang_tvm_compiler (PreIsaIR v2 → MIR path)
; ============================================================
S_LUI_INT gp29, 13824   ; %8=S_LUI_INT(13824)
; STBACK %8 gp29 -> slot 0
S_ST_INT gp29, gp0, 0
S_LUI_INT gp1, 2048   ; %11=S_LUI_INT(2048)
S_ADDI_INT gp29, gp0, 2048   ; %12=S_ADDI_INT(%0_gp0,2048)
; STBACK %12 gp29 -> slot 1
S_ST_INT gp29, gp0, 1
S_LUI_INT gp29, 27648   ; %319=S_LUI_INT(27648)
; STBACK %319 gp29 -> slot 2
S_ST_INT gp29, gp0, 2
S_LUI_INT gp2, 768   ; %27=S_LUI_INT(768)
S_LUI_INT gp3, 256   ; %64=S_LUI_INT(256)
S_LUI_INT gp4, 512   ; %71=S_LUI_INT(512)
S_LUI_INT gp5, 1024   ; %309=S_LUI_INT(1024)
S_ADDI_INT gp6, gp0, 1   ; %51=S_ADDI_INT(%0_gp0,1)
S_ADDI_INT gp7, gp0, 32   ; %56=S_ADDI_INT(%0_gp0,32)
S_ADDI_INT gp8, gp0, 33   ; %93=S_ADDI_INT(%0_gp0,33)
S_ADDI_INT gp9, gp0, 34   ; %126=S_ADDI_INT(%0_gp0,34)
S_ADDI_INT gp10, gp0, 35   ; %149=S_ADDI_INT(%0_gp0,35)
S_ADDI_INT gp11, gp0, 36   ; %194=S_ADDI_INT(%0_gp0,36)
S_ADDI_INT gp12, gp0, 37   ; %262=S_ADDI_INT(%0_gp0,37)
; for 1_bx in [0, 4) -- hw counter gp13, idx gp14
S_ADDI_INT gp14, gp0, 0
C_LOOP_START gp13, 4
S_SLLI_INT gp15, gp14, 21   ; %30=S_SLLI_INT(%1_bx,21)
; for 2_by_number in [0, 2) -- hw counter gp16, idx gp17
S_ADDI_INT gp17, gp0, 0
C_LOOP_START gp16, 2
; dma_h2v_slice X_hbm -> X_sh  (grid d=1 s=1 h=1 b=1)
; RELOAD %8 (slot 0) -> gp29
S_LD_INT gp29, gp0, 0
C_SET_ADDR_REG a0, gp0, gp29   ; %9=C_SET_ADDR_REG(gp0,%8)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%11)
; RELOAD %12 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%12)
S_SLLI_INT gp18, gp17, 10   ; %36=S_SLLI_INT(%2_by_number,10)
; for 14_h2v_inner_b6e0 in [0, 4) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 4
S_SLLI_INT gp21, gp20, 18   ; %24=S_SLLI_INT(%14_h2v_inner_b6e0,18)
S_ADD_INT gp22, gp21, gp2   ; %28=S_ADD_INT(%24,%27)
S_SLLI_INT gp21, gp20, 19   ; %34=S_SLLI_INT(%14_h2v_inner_b6e0,19)
S_ADD_INT gp23, gp15, gp21   ; %35=S_ADD_INT(%30,%34)
S_ADD_INT gp21, gp23, gp18   ; %37=S_ADD_INT(%35,%36)
H_PREFETCH_V gp22, gp21, a0, 1, 0   ; H_PREFETCH_V(%28,%37,%9,1,0)
; idx 14_h2v_inner_b6e0 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 44_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; copy_v_to_v src.parent=X_sh -> dst.parent=__tmp_vec_13 extents=[1, 1, 8, 128]
S_SLLI_INT gp21, gp20, 10   ; %45=S_SLLI_INT(%44_row1,10)
S_ADD_INT gp22, gp2, gp21   ; %48=S_ADD_INT(%27,%45)
V_ADD_VF gp21, gp22, f0, 0   ; V_ADD_VF(%45,%48,f0,0)
; idx 44_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 49_by_phase in [0, 8) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 8
S_SRLI_INT gp21, gp20, 3   ; %52=S_SRLI_INT(%49_by_phase,3)
S_SLLI_INT gp22, gp21, 3   ; %53=S_SLLI_INT(%52,3)
S_SUB_INT gp23, gp20, gp22   ; %54=S_SUB_INT(%49_by_phase,%53)
S_SLL_INT gp22, gp6, gp23   ; %55=S_SLL_INT(%51,%54)
S_SLLI_INT gp23, gp21, 20   ; %58=S_SLLI_INT(%52,20)
; for 50_row in [0, 1024) -- hw counter gp21, idx gp24
S_ADDI_INT gp24, gp0, 0
C_LOOP_START gp21, 1024
; row scalar task row_mul_fp op=mul src.parent=__tmp_vec_13 starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp22   ; C_SET_V_MASK_REG(%55)
S_LD_FP f1, gp7, 0   ; S_LD_FP(f1,%56,0)
S_SLLI_INT gp25, gp24, 10   ; %59=S_SLLI_INT(%50_row,10)
S_ADD_INT gp26, gp23, gp25   ; %60=S_ADD_INT(%58,%59)
V_MUL_VF gp26, gp26, f1, 1   ; V_MUL_VF(%60,%60,f1,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; idx 50_row += 1 (gp24)
S_ADDI_INT gp24, gp24, 1
C_LOOP_END gp21
; idx 49_by_phase += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 61_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; v binary v_mul V_MUL_VV dst.parent=__tmp_vec_14 starts=[0, row1, 0, 0] extents=[1, 1, 8, 128]
S_SLLI_INT gp21, gp20, 10   ; %62=S_SLLI_INT(%61_row1,10)
S_ADD_INT gp22, gp21, gp3   ; %65=S_ADD_INT(%62,%64)
S_ADD_INT gp23, gp2, gp21   ; %68=S_ADD_INT(%27,%62)
V_MUL_VV gp22, gp23, gp23, 0   ; V_MUL_VV(%65,%68,%68,0)
; v binary v_mul V_MUL_VV dst.parent=__tmp_vec_15 starts=[0, row1, 0, 0] extents=[1, 1, 8, 128]
S_ADD_INT gp24, gp21, gp4   ; %72=S_ADD_INT(%62,%71)
V_MUL_VV gp24, gp22, gp23, 0   ; V_MUL_VV(%72,%65,%68,0)
; copy_v_to_v src.parent=__tmp_vec_15 -> dst.parent=__tmp_vec_14 extents=[1, 1, 8, 128]
V_ADD_VF gp22, gp24, f0, 0   ; V_ADD_VF(%65,%72,f0,0)
; idx 61_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 86_by_phase in [0, 8) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 8
S_SRLI_INT gp21, gp20, 3   ; %89=S_SRLI_INT(%86_by_phase,3)
S_SLLI_INT gp22, gp21, 3   ; %90=S_SLLI_INT(%89,3)
S_SUB_INT gp23, gp20, gp22   ; %91=S_SUB_INT(%86_by_phase,%90)
S_SLL_INT gp22, gp6, gp23   ; %92=S_SLL_INT(%51,%91)
S_SLLI_INT gp23, gp21, 20   ; %95=S_SLLI_INT(%89,20)
S_ADD_INT gp21, gp3, gp23   ; %367=S_ADD_INT(%64,%95)
S_ADD_INT gp24, gp3, gp23   ; %368=S_ADD_INT(%64,%95)
; for 87_row in [0, 1024) -- hw counter gp23, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp23, 1024
; row scalar task row_mul_fp op=mul src.parent=__tmp_vec_14 starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp22   ; C_SET_V_MASK_REG(%92)
S_LD_FP f1, gp8, 0   ; S_LD_FP(f1,%93,0)
S_SLLI_INT gp26, gp25, 10   ; %96=S_SLLI_INT(%87_row,10)
S_ADD_INT gp27, gp24, gp26   ; %100=S_ADD_INT(%368,%96)
V_MUL_VF gp27, gp27, f1, 1   ; V_MUL_VF(%100,%100,f1,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; idx 87_row += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp23
; idx 86_by_phase += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 101_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; v binary v_add V_ADD_VV dst.parent=__tmp_vec_15 starts=[0, row1, 0, 0] extents=[1, 1, 8, 128]
S_SLLI_INT gp22, gp20, 10   ; %102=S_SLLI_INT(%101_row1,10)
S_ADD_INT gp23, gp22, gp4   ; %105=S_ADD_INT(%102,%71)
S_ADD_INT gp24, gp22, gp2   ; %108=S_ADD_INT(%102,%27)
S_ADD_INT gp25, gp22, gp3   ; %111=S_ADD_INT(%102,%64)
V_ADD_VV gp23, gp24, gp25, 0   ; V_ADD_VV(%105,%108,%111,0)
; copy_v_to_v src.parent=__tmp_vec_15 -> dst.parent=__tmp_vec_14 extents=[1, 1, 8, 128]
V_ADD_VF gp25, gp23, f0, 0   ; V_ADD_VF(%111,%105,f0,0)
; idx 101_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 119_by_phase in [0, 8) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 8
S_SRLI_INT gp22, gp20, 3   ; %122=S_SRLI_INT(%119_by_phase,3)
S_SLLI_INT gp23, gp22, 3   ; %123=S_SLLI_INT(%122,3)
S_SUB_INT gp24, gp20, gp23   ; %124=S_SUB_INT(%119_by_phase,%123)
S_SLL_INT gp23, gp6, gp24   ; %125=S_SLL_INT(%51,%124)
S_SLLI_INT gp24, gp22, 20   ; %128=S_SLLI_INT(%122,20)
; for 120_row in [0, 1024) -- hw counter gp22, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp22, 1024
; row scalar task row_mul_fp op=mul src.parent=__tmp_vec_14 starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp23   ; C_SET_V_MASK_REG(%125)
S_LD_FP f1, gp9, 0   ; S_LD_FP(f1,%126,0)
S_SLLI_INT gp26, gp25, 10   ; %129=S_SLLI_INT(%120_row,10)
S_ADD_INT gp27, gp24, gp26   ; %130=S_ADD_INT(%128,%129)
S_ADD_INT gp26, gp27, gp3   ; %133=S_ADD_INT(%130,%64)
V_MUL_VF gp26, gp26, f1, 1   ; V_MUL_VF(%133,%133,f1,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; idx 120_row += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp22
; idx 119_by_phase += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 134_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; copy_v_to_v src.parent=__tmp_vec_14 -> dst.parent=__tmp_vec_15 extents=[1, 1, 8, 128]
S_SLLI_INT gp22, gp20, 10   ; %135=S_SLLI_INT(%134_row1,10)
S_ADD_INT gp23, gp22, gp4   ; %138=S_ADD_INT(%135,%71)
S_ADD_INT gp24, gp22, gp3   ; %141=S_ADD_INT(%135,%64)
V_ADD_VF gp23, gp24, f0, 0   ; V_ADD_VF(%138,%141,f0,0)
; idx 134_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 142_by_phase in [0, 8) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 8
S_SRLI_INT gp22, gp20, 3   ; %145=S_SRLI_INT(%142_by_phase,3)
S_SLLI_INT gp23, gp22, 3   ; %146=S_SLLI_INT(%145,3)
S_SUB_INT gp24, gp20, gp23   ; %147=S_SUB_INT(%142_by_phase,%146)
S_SLL_INT gp23, gp6, gp24   ; %148=S_SLL_INT(%51,%147)
S_SLLI_INT gp24, gp22, 20   ; %151=S_SLLI_INT(%145,20)
; for 143_row in [0, 1024) -- hw counter gp22, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp22, 1024
; row scalar task row_mul_fp op=mul src.parent=__tmp_vec_15 starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp23   ; C_SET_V_MASK_REG(%148)
S_LD_FP f1, gp10, 0   ; S_LD_FP(f1,%149,0)
S_SLLI_INT gp26, gp25, 10   ; %152=S_SLLI_INT(%143_row,10)
S_ADD_INT gp27, gp24, gp26   ; %153=S_ADD_INT(%151,%152)
S_ADD_INT gp26, gp27, gp4   ; %156=S_ADD_INT(%153,%71)
V_MUL_VF gp26, gp26, f1, 1   ; V_MUL_VF(%156,%156,f1,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; idx 143_row += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp22
; idx 142_by_phase += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 157_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; copy_v_to_v src.parent=__tmp_vec_15 -> dst.parent=__tmp_vec_14 extents=[1, 1, 8, 128]
S_SLLI_INT gp22, gp20, 10   ; %158=S_SLLI_INT(%157_row1,10)
S_ADD_INT gp23, gp22, gp3   ; %161=S_ADD_INT(%158,%64)
S_ADD_INT gp24, gp22, gp4   ; %164=S_ADD_INT(%158,%71)
V_ADD_VF gp23, gp24, f0, 0   ; V_ADD_VF(%161,%164,f0,0)
; idx 157_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 165_by_phase in [0, 8) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 8
S_SRLI_INT gp22, gp20, 3   ; %168=S_SRLI_INT(%165_by_phase,3)
S_SLLI_INT gp23, gp22, 3   ; %169=S_SLLI_INT(%168,3)
S_SUB_INT gp24, gp20, gp23   ; %170=S_SUB_INT(%165_by_phase,%169)
S_SLL_INT gp23, gp6, gp24   ; %171=S_SLL_INT(%51,%170)
S_SLLI_INT gp24, gp22, 20   ; %173=S_SLLI_INT(%168,20)
; for 166_row in [0, 1024) -- hw counter gp22, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp22, 1024
; row scalar task row_exp op=exp src.parent=__tmp_vec_14 starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp23   ; C_SET_V_MASK_REG(%171)
S_SLLI_INT gp26, gp25, 10   ; %174=S_SLLI_INT(%166_row,10)
S_ADD_INT gp27, gp24, gp26   ; %175=S_ADD_INT(%173,%174)
S_ADD_INT gp26, gp27, gp3   ; %178=S_ADD_INT(%175,%64)
V_EXP_V gp26, gp26, 1   ; V_EXP_V(%178,%178,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; idx 166_row += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp22
; idx 165_by_phase += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 179_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; copy_v_to_v src.parent=__tmp_vec_14 -> dst.parent=__tmp_vec_15 extents=[1, 1, 8, 128]
S_SLLI_INT gp22, gp20, 10   ; %180=S_SLLI_INT(%179_row1,10)
S_ADD_INT gp23, gp22, gp4   ; %183=S_ADD_INT(%180,%71)
S_ADD_INT gp24, gp22, gp3   ; %186=S_ADD_INT(%180,%64)
V_ADD_VF gp23, gp24, f0, 0   ; V_ADD_VF(%183,%186,f0,0)
; idx 179_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 187_by_phase in [0, 8) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 8
S_SRLI_INT gp22, gp20, 3   ; %190=S_SRLI_INT(%187_by_phase,3)
S_SLLI_INT gp23, gp22, 3   ; %191=S_SLLI_INT(%190,3)
S_SUB_INT gp24, gp20, gp23   ; %192=S_SUB_INT(%187_by_phase,%191)
S_SLL_INT gp23, gp6, gp24   ; %193=S_SLL_INT(%51,%192)
S_SLLI_INT gp24, gp22, 20   ; %196=S_SLLI_INT(%190,20)
; for 188_row in [0, 1024) -- hw counter gp22, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp22, 1024
; row scalar task row_add_fp op=add src.parent=__tmp_vec_15 starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp23   ; C_SET_V_MASK_REG(%193)
S_LD_FP f1, gp11, 0   ; S_LD_FP(f1,%194,0)
S_SLLI_INT gp26, gp25, 10   ; %197=S_SLLI_INT(%188_row,10)
S_ADD_INT gp27, gp24, gp26   ; %198=S_ADD_INT(%196,%197)
S_ADD_INT gp26, gp27, gp4   ; %201=S_ADD_INT(%198,%71)
V_ADD_VF gp26, gp26, f1, 1   ; V_ADD_VF(%201,%201,f1,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; idx 188_row += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp22
; idx 187_by_phase += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 202_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; copy_v_to_v src.parent=__tmp_vec_15 -> dst.parent=__tmp_vec_14 extents=[1, 1, 8, 128]
S_SLLI_INT gp22, gp20, 10   ; %203=S_SLLI_INT(%202_row1,10)
S_ADD_INT gp23, gp22, gp3   ; %206=S_ADD_INT(%203,%64)
S_ADD_INT gp24, gp22, gp4   ; %209=S_ADD_INT(%203,%71)
V_ADD_VF gp23, gp24, f0, 0   ; V_ADD_VF(%206,%209,f0,0)
; idx 202_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 210_by_phase in [0, 8) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 8
S_SRLI_INT gp22, gp20, 3   ; %213=S_SRLI_INT(%210_by_phase,3)
S_SLLI_INT gp23, gp22, 3   ; %214=S_SLLI_INT(%213,3)
S_SUB_INT gp24, gp20, gp23   ; %215=S_SUB_INT(%210_by_phase,%214)
S_SLL_INT gp23, gp6, gp24   ; %216=S_SLL_INT(%51,%215)
S_SLLI_INT gp24, gp22, 20   ; %218=S_SLLI_INT(%213,20)
; for 211_row in [0, 1024) -- hw counter gp22, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp22, 1024
; row scalar task row_reci op=reci src.parent=__tmp_vec_14 starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp23   ; C_SET_V_MASK_REG(%216)
S_SLLI_INT gp26, gp25, 10   ; %219=S_SLLI_INT(%211_row,10)
S_ADD_INT gp27, gp24, gp26   ; %220=S_ADD_INT(%218,%219)
S_ADD_INT gp26, gp27, gp3   ; %223=S_ADD_INT(%220,%64)
V_RECI_V gp26, gp26, 1   ; V_RECI_V(%223,%223,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; idx 211_row += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp22
; idx 210_by_phase += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 224_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; copy_v_to_v src.parent=__tmp_vec_14 -> dst.parent=__tmp_vec_15 extents=[1, 1, 8, 128]
S_SLLI_INT gp22, gp20, 10   ; %225=S_SLLI_INT(%224_row1,10)
S_ADD_INT gp23, gp22, gp4   ; %228=S_ADD_INT(%225,%71)
S_ADD_INT gp24, gp22, gp3   ; %231=S_ADD_INT(%225,%64)
V_ADD_VF gp23, gp24, f0, 0   ; V_ADD_VF(%228,%231,f0,0)
; idx 224_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 232_by_phase in [0, 8) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 8
S_SRLI_INT gp22, gp20, 3   ; %235=S_SRLI_INT(%232_by_phase,3)
S_SLLI_INT gp23, gp22, 3   ; %236=S_SLLI_INT(%235,3)
S_SUB_INT gp24, gp20, gp23   ; %237=S_SUB_INT(%232_by_phase,%236)
S_SLL_INT gp23, gp6, gp24   ; %238=S_SLL_INT(%51,%237)
S_SLLI_INT gp24, gp22, 20   ; %241=S_SLLI_INT(%235,20)
; for 233_row in [0, 1024) -- hw counter gp22, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp22, 1024
; row scalar task row_mul_fp op=mul src.parent=__tmp_vec_15 starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp23   ; C_SET_V_MASK_REG(%238)
S_LD_FP f1, gp10, 0   ; S_LD_FP(f1,%149,0)
S_SLLI_INT gp26, gp25, 10   ; %242=S_SLLI_INT(%233_row,10)
S_ADD_INT gp27, gp24, gp26   ; %243=S_ADD_INT(%241,%242)
S_ADD_INT gp26, gp27, gp4   ; %246=S_ADD_INT(%243,%71)
V_MUL_VF gp26, gp26, f1, 1   ; V_MUL_VF(%246,%246,f1,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; idx 233_row += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp22
; idx 232_by_phase += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 247_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; copy_v_to_v src.parent=__tmp_vec_15 -> dst.parent=__tmp_vec_14 extents=[1, 1, 8, 128]
S_SLLI_INT gp22, gp20, 10   ; %248=S_SLLI_INT(%247_row1,10)
S_ADD_INT gp23, gp22, gp3   ; %251=S_ADD_INT(%248,%64)
S_ADD_INT gp24, gp22, gp4   ; %254=S_ADD_INT(%248,%71)
V_ADD_VF gp23, gp24, f0, 0   ; V_ADD_VF(%251,%254,f0,0)
; idx 247_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 255_by_phase in [0, 8) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 8
S_SRLI_INT gp22, gp20, 3   ; %258=S_SRLI_INT(%255_by_phase,3)
S_SLLI_INT gp23, gp22, 3   ; %259=S_SLLI_INT(%258,3)
S_SUB_INT gp24, gp20, gp23   ; %260=S_SUB_INT(%255_by_phase,%259)
S_SLL_INT gp23, gp6, gp24   ; %261=S_SLL_INT(%51,%260)
S_SLLI_INT gp24, gp22, 20   ; %264=S_SLLI_INT(%258,20)
; for 256_row in [0, 1024) -- hw counter gp22, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp22, 1024
; row scalar task row_mul_fp op=mul src.parent=__tmp_vec_14 starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp23   ; C_SET_V_MASK_REG(%261)
S_LD_FP f1, gp12, 0   ; S_LD_FP(f1,%262,0)
S_SLLI_INT gp26, gp25, 10   ; %265=S_SLLI_INT(%256_row,10)
S_ADD_INT gp27, gp24, gp26   ; %266=S_ADD_INT(%264,%265)
S_ADD_INT gp26, gp27, gp3   ; %269=S_ADD_INT(%266,%64)
V_MUL_VF gp26, gp26, f1, 1   ; V_MUL_VF(%269,%269,f1,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; row scalar task row_add_fp op=add src.parent=__tmp_vec_14 starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp23   ; C_SET_V_MASK_REG(%261)
S_LD_FP f1, gp11, 0   ; S_LD_FP(f1,%194,0)
V_ADD_VF gp26, gp26, f1, 1   ; V_ADD_VF(%269,%269,f1,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; idx 256_row += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp22
; idx 255_by_phase += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 283_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; copy_v_to_v src.parent=__tmp_vec_14 -> dst.parent=__tmp_vec_15 extents=[1, 1, 8, 128]
S_SLLI_INT gp22, gp20, 10   ; %284=S_SLLI_INT(%283_row1,10)
S_ADD_INT gp23, gp22, gp4   ; %287=S_ADD_INT(%284,%71)
S_ADD_INT gp24, gp22, gp3   ; %290=S_ADD_INT(%284,%64)
V_ADD_VF gp23, gp24, f0, 0   ; V_ADD_VF(%287,%290,f0,0)
; idx 283_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 291_by_phase in [0, 8) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 8
S_SRLI_INT gp22, gp20, 3   ; %294=S_SRLI_INT(%291_by_phase,3)
S_SLLI_INT gp23, gp22, 3   ; %295=S_SLLI_INT(%294,3)
S_SUB_INT gp24, gp20, gp23   ; %296=S_SUB_INT(%291_by_phase,%295)
S_SLL_INT gp23, gp6, gp24   ; %297=S_SLL_INT(%51,%296)
S_SLLI_INT gp24, gp22, 20   ; %300=S_SLLI_INT(%294,20)
; for 292_row in [0, 1024) -- hw counter gp22, idx gp25
S_ADDI_INT gp25, gp0, 0
C_LOOP_START gp22, 1024
; row scalar task row_add_fp op=add src.parent=__tmp_vec_15 starts=[0, row, by_phase, 0]
C_SET_V_MASK_REG gp23   ; C_SET_V_MASK_REG(%297)
S_LD_FP f1, gp11, 0   ; S_LD_FP(f1,%194,0)
S_SLLI_INT gp26, gp25, 10   ; %301=S_SLLI_INT(%292_row,10)
S_ADD_INT gp27, gp24, gp26   ; %302=S_ADD_INT(%300,%301)
S_ADD_INT gp26, gp27, gp4   ; %305=S_ADD_INT(%302,%71)
V_ADD_VF gp26, gp26, f1, 1   ; V_ADD_VF(%305,%305,f1,1)
C_SET_V_MASK_REG gp0   ; C_SET_V_MASK_REG(%0_gp0)
; idx 292_row += 1 (gp25)
S_ADDI_INT gp25, gp25, 1
C_LOOP_END gp22
; idx 291_by_phase += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; for 306_row1 in [0, 1024) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 1024
; v binary v_mul V_MUL_VV dst.parent=Y_sh starts=[0, row1, 0, 0] extents=[1, 1, 8, 128]
S_SLLI_INT gp22, gp20, 10   ; %307=S_SLLI_INT(%306_row1,10)
S_ADD_INT gp23, gp22, gp5   ; %310=S_ADD_INT(%307,%309)
S_ADD_INT gp24, gp22, gp4   ; %313=S_ADD_INT(%307,%71)
V_MUL_VV gp23, gp22, gp24, 0   ; V_MUL_VV(%310,%307,%313,0)
; idx 306_row1 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; dma_v2h_slice Y_sh -> Y_hbm  (grid d=1 s=1 h=1 b=1)
; RELOAD %319 (slot 2) -> gp29
S_LD_INT gp29, gp0, 2
C_SET_ADDR_REG a1, gp0, gp29   ; %320=C_SET_ADDR_REG(gp0,%319)
C_SET_SCALE_REG gp1   ; C_SET_SCALE_REG(%11)
; RELOAD %12 (slot 1) -> gp29
S_LD_INT gp29, gp0, 1
C_SET_STRIDE_REG gp29   ; C_SET_STRIDE_REG(%12)
; for 325_v2h_inner_9970 in [0, 4) -- hw counter gp19, idx gp20
S_ADDI_INT gp20, gp0, 0
C_LOOP_START gp19, 4
S_SLLI_INT gp22, gp20, 18   ; %335=S_SLLI_INT(%325_v2h_inner_9970,18)
S_ADD_INT gp23, gp5, gp22   ; %339=S_ADD_INT(%309,%335)
S_SLLI_INT gp22, gp20, 19   ; %345=S_SLLI_INT(%325_v2h_inner_9970,19)
S_ADD_INT gp24, gp15, gp22   ; %346=S_ADD_INT(%30,%345)
S_ADD_INT gp22, gp24, gp18   ; %348=S_ADD_INT(%346,%36)
H_STORE_V gp23, gp22, a1, 1, 0   ; H_STORE_V(%339,%348,%320,1,0)
; idx 325_v2h_inner_9970 += 1 (gp20)
S_ADDI_INT gp20, gp20, 1
C_LOOP_END gp19
; idx 2_by_number += 1 (gp17)
S_ADDI_INT gp17, gp17, 1
C_LOOP_END gp16
; idx 1_bx += 1 (gp14)
S_ADDI_INT gp14, gp14, 1
C_LOOP_END gp13
